// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

// Independent expected-origin oracle used by the authenticated policy probe.

/// Independent oracle for the production registry exposed by the authenticated
/// AY executable.  Do not derive any string in this table from `UnknownOrigin`
/// or `UnknownReason`: doing so would let the producer and validator drift in
/// lockstep and manufacture a false PASS.
#[derive(Clone, Copy)]
struct ExpectedOrigin {
    origin: UnknownOrigin,
    origin_code: &'static str,
    reason: UnknownReason,
    reason_code: &'static str,
    reason_name: &'static str,
    reason_smtlib: &'static str,
    production_chokepoint: &'static str,
    trigger_kind: &'static str,
    fixture: &'static str,
}

const EXPECTED_ORIGINS: [ExpectedOrigin; 19] = [
    ExpectedOrigin {
        origin: UnknownOrigin::SolveDeadline,
        origin_code: "solve_deadline",
        reason: UnknownReason::Timeout,
        reason_code: "timeout",
        reason_name: "Timeout",
        reason_smtlib: "timeout",
        production_chokepoint: "executor/check_sat.rs::should_abort_theory_loop",
        trigger_kind: "natural-public-query",
        fixture: "natural.check-sat.zero-deadline",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::DeterministicResourceBudget,
        origin_code: "deterministic_resource_budget",
        reason: UnknownReason::ResourceLimit,
        reason_code: "resource_limit",
        reason_name: "Resource limit",
        reason_smtlib: "resourceout",
        production_chokepoint: "executor/theories/model_helpers.rs::record_sat_unknown_reason",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.deterministic-resource-budget.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::MemoryBudget,
        origin_code: "memory_budget",
        reason: UnknownReason::MemoryLimit,
        reason_code: "memory_limit",
        reason_name: "Memory limit",
        reason_smtlib: "memout",
        production_chokepoint: "executor/check_sat.rs::should_abort_theory_loop",
        trigger_kind: "natural-public-query",
        fixture: "natural.check-sat.one-byte-memory-limit",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::InterruptFlag,
        origin_code: "interrupt_flag",
        reason: UnknownReason::Interrupted,
        reason_code: "interrupted",
        reason_name: "Interrupted",
        reason_smtlib: "interrupted",
        production_chokepoint: "executor/check_sat.rs::should_abort_theory_loop",
        trigger_kind: "natural-public-query",
        fixture: "natural.check-sat.pre-set-interrupt",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::IncompleteSolverLane,
        origin_code: "incomplete_solver_lane",
        reason: UnknownReason::Incomplete,
        reason_code: "incomplete",
        reason_name: "Incomplete",
        reason_smtlib: "incomplete",
        production_chokepoint: "executor/check_sat.rs::check_sat_guarded",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.incomplete-solver-lane.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::VerdictCertification,
        origin_code: "verdict_certification",
        reason: UnknownReason::SelfCheckRejected,
        reason_code: "self_check_rejected",
        reason_name: "Self-check REJECTED a computed verdict",
        reason_smtlib: "(incomplete self-check-rejected)",
        production_chokepoint: "executor/unsat_cert.rs::reject_uncertified_verdict_for_publication",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.verdict-certification.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::EmatchingRoundBudget,
        origin_code: "ematching_round_budget",
        reason: UnknownReason::QuantifierRoundLimit,
        reason_code: "quantifier_round_limit",
        reason_name: "Quantifier round limit",
        reason_smtlib: "(incomplete quantifier-round-limit)",
        production_chokepoint: "executor/quantifier_loop/result_mapping.rs::map_quantifier_result",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.ematching-round-budget.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::DeferredInstantiation,
        origin_code: "deferred_instantiation",
        reason: UnknownReason::QuantifierDeferred,
        reason_code: "quantifier_deferred",
        reason_name: "Quantifier deferred",
        reason_smtlib: "(incomplete quantifier-deferred)",
        production_chokepoint: "executor/quantifier_loop/result_mapping.rs::map_quantifier_result",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.deferred-instantiation.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::UnhandledQuantifier,
        origin_code: "unhandled_quantifier",
        reason: UnknownReason::QuantifierUnhandled,
        reason_code: "quantifier_unhandled",
        reason_name: "Quantifier unhandled",
        reason_smtlib: "(incomplete quantifier-unhandled)",
        production_chokepoint: "executor/quantifier_loop/result_mapping.rs::map_quantifier_result",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.unhandled-quantifier.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::CegqiRefinement,
        origin_code: "cegqi_refinement",
        reason: UnknownReason::QuantifierCegqiIncomplete,
        reason_code: "quantifier_cegqi_incomplete",
        reason_name: "Quantifier CEGQI incomplete",
        reason_smtlib: "(incomplete quantifier-cegqi)",
        production_chokepoint:
            "executor/quantifier_loop/cegqi_refinement.rs::try_cegqi_arith_refinement",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.cegqi-refinement.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::ExistentialEmatching,
        origin_code: "existential_ematching",
        reason: UnknownReason::QuantifierEmatchingExistsIncomplete,
        reason_code: "quantifier_ematching_exists_incomplete",
        reason_name: "Quantifier E-matching exists incomplete",
        reason_smtlib: "(incomplete quantifier-ematching-exists)",
        production_chokepoint: "executor/quantifier_loop/result_mapping.rs::map_quantifier_result",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.existential-ematching.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::TheorySplitBudget,
        origin_code: "theory_split_budget",
        reason: UnknownReason::SplitLimit,
        reason_code: "split_limit",
        reason_name: "Split limit",
        reason_smtlib: "incomplete",
        production_chokepoint: "pipeline_incremental_split_assume_macros.rs::split_loop",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.theory-split-budget.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::UnsupportedExpressionSplit,
        origin_code: "unsupported_expression_split",
        reason: UnknownReason::ExpressionSplit,
        reason_code: "expression_split",
        reason_name: "Expression split",
        reason_smtlib: "incomplete",
        production_chokepoint:
            "pipeline_incremental_split_eager_shared_macros.rs::create_expression_split_atoms",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.unsupported-expression-split.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::UnsupportedFeature,
        origin_code: "unsupported_feature",
        reason: UnknownReason::Unsupported,
        reason_code: "unsupported",
        reason_name: "Unsupported",
        reason_smtlib: "unsupported",
        production_chokepoint: "executor.rs::execute_stack_guarded",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.unsupported-feature.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::UnsupportedArithmeticFragment,
        origin_code: "unsupported_arithmetic_fragment",
        reason: UnknownReason::UnsupportedArithmetic,
        reason_code: "unsupported_arithmetic",
        reason_name: "Unsupported arithmetic",
        reason_smtlib: "(unsupported arithmetic)",
        production_chokepoint: "executor/check_sat.rs::contains_symbolic_integer_power",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.unsupported-arithmetic-fragment.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::UnsupportedMixedCollection,
        origin_code: "unsupported_mixed_collection",
        reason: UnknownReason::UnsupportedMixedCollection,
        reason_code: "unsupported_mixed_collection",
        reason_name: "Unsupported mixed collection",
        reason_smtlib: "(unsupported mixed-collection)",
        production_chokepoint: "executor/theories/seq.rs::solve_seq_auflia",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.unsupported-mixed-collection.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::ExecutorFailure,
        origin_code: "executor_failure",
        reason: UnknownReason::InternalError,
        reason_code: "internal_error",
        reason_name: "Internal error",
        reason_smtlib: "internal-error",
        production_chokepoint: "api/solving/check.rs::record_executor_failure_unknown",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.executor-failure.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::UntaggedSolverUnknown,
        origin_code: "untagged_solver_unknown",
        reason: UnknownReason::Unknown,
        reason_code: "unknown",
        reason_name: "Unknown",
        reason_smtlib: "unknown",
        production_chokepoint:
            "executor/lifecycle/unknown_publication.rs::finalize_unknown_publication",
        trigger_kind: "authoritative-origin-publication-fault-injection",
        fixture: "fault.untagged-solver-unknown.authoritative-publication",
    },
    ExpectedOrigin {
        origin: UnknownOrigin::TerminalTrust,
        origin_code: "terminal_trust",
        reason: UnknownReason::ProofTrusted,
        reason_code: "proof_trusted",
        reason_name: "Strict proofs WITHHELD a trust-bearing UNSAT",
        reason_smtlib: "(incomplete proof-trusted)",
        production_chokepoint:
            "executor/unsat_cert.rs::decline_trust_bearing_unsat_under_strict_proofs",
        trigger_kind: "natural-public-query",
        fixture: "natural.check-sat.strict-proof-terminal-trust",
    },
];
