import AySoundness.Firewall
/-! Auto-generated by AY: bit-blast UNSAT for `(not (= (bvadd a b) (bvadd a b)))`, grounded in the verified
    firewall `AySoundness.firewall_combined_unsat` + `lratCheck_sound`. -/
namespace AySoundness.CombinedBvBlastChain
open AySoundness

/-- A gate-respecting assignment: `α` plus, per gate, a proof that the
    output bit equals `gateEval` of its inputs. -/
structure Val where
  α : Nat → Bool
  respects_0 : α 5 = false
  respects_1 : α 6 = (Bool.xor (Bool.xor (α 1) (α 3)) (α 5))
  respects_2 : α 7 = (((α 1) && (α 3)) || ((α 5) && Bool.xor (α 1) (α 3)))
  respects_3 : α 8 = (Bool.xor (Bool.xor (α 2) (α 4)) (α 7))
  respects_4 : α 9 = (!(Bool.xor (α 6) (α 6)))
  respects_5 : α 10 = (!(Bool.xor (α 8) (α 8)))

def atomVal (m : Val) (n : Nat) : Bool := m.α n

/-- A witness assignment (topological gate eval over all-false inputs): it
    certifies `Val` is inhabited, so `no_model` below is non-vacuous. -/
def wα : Nat → Bool := fun n => match n with
  | 5 => false
  | 6 => false
  | 7 => false
  | 8 => false
  | 9 => true
  | 10 => true
  | _ => false

theorem val_inhabited : Nonempty Val :=
  ⟨{ α := wα, respects_0 := by decide, respects_1 := by decide, respects_2 := by decide, respects_3 := by decide, respects_4 := by decide, respects_5 := by decide }⟩

def original : List (Cid × Clause) := [(30, [-9, -10])]
def lemmas : List (Cid × Clause) := [(1, [-5]), (2, [-6, 1, 3, 5]), (3, [6, -1, 3, 5]), (4, [6, 1, -3, 5]), (5, [-6, -1, -3, 5]), (6, [6, 1, 3, -5]), (7, [-6, -1, 3, -5]), (8, [-6, 1, -3, -5]), (9, [6, -1, -3, -5]), (10, [-7, 1, 3, 5]), (11, [-7, -1, 3, 5]), (12, [-7, 1, -3, 5]), (13, [7, -1, -3, 5]), (14, [-7, 1, 3, -5]), (15, [7, -1, 3, -5]), (16, [7, 1, -3, -5]), (17, [7, -1, -3, -5]), (18, [-8, 2, 4, 7]), (19, [8, -2, 4, 7]), (20, [8, 2, -4, 7]), (21, [-8, -2, -4, 7]), (22, [8, 2, 4, -7]), (23, [-8, -2, 4, -7]), (24, [-8, 2, -4, -7]), (25, [8, -2, -4, -7]), (26, [9, 6]), (27, [9, -6]), (28, [10, 8]), (29, [10, -8])]

def proof : List (Cid × Clause × List Int) := [
  (31, [9], [27, 26]),
  (32, [10], [29, 28]),
  (33, [-10], [30, 31]),
  (34, [], [33, 32])
]

/-- Every gate Tseitin clause holds under any gate-respecting assignment:
    per clause, case-split that gate's inputs and apply its `respects_*`. -/
theorem lemmas_valid :
    ∀ cl ∈ clauses lemmas, ∀ m : Val, clauseSat (atomVal m) cl = true := by
  intro cl hcl m
  simp only [clauses, lemmas, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hcl
  rcases hcl with h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h | h
  · subst h; simp_all [clauseSat, litSat, atomVal, m.respects_0]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_2]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_2]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_2]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_2]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_2]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_2]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_2]
  · subst h; cases hv0 : (m.α 1) <;> cases hv2 : (m.α 3) <;> cases hv4 : (m.α 5) <;> simp_all [clauseSat, litSat, atomVal, m.respects_2]
  · subst h; cases hv1 : (m.α 2) <;> cases hv3 : (m.α 4) <;> cases hv6 : (m.α 7) <;> simp_all [clauseSat, litSat, atomVal, m.respects_3]
  · subst h; cases hv1 : (m.α 2) <;> cases hv3 : (m.α 4) <;> cases hv6 : (m.α 7) <;> simp_all [clauseSat, litSat, atomVal, m.respects_3]
  · subst h; cases hv1 : (m.α 2) <;> cases hv3 : (m.α 4) <;> cases hv6 : (m.α 7) <;> simp_all [clauseSat, litSat, atomVal, m.respects_3]
  · subst h; cases hv1 : (m.α 2) <;> cases hv3 : (m.α 4) <;> cases hv6 : (m.α 7) <;> simp_all [clauseSat, litSat, atomVal, m.respects_3]
  · subst h; cases hv1 : (m.α 2) <;> cases hv3 : (m.α 4) <;> cases hv6 : (m.α 7) <;> simp_all [clauseSat, litSat, atomVal, m.respects_3]
  · subst h; cases hv1 : (m.α 2) <;> cases hv3 : (m.α 4) <;> cases hv6 : (m.α 7) <;> simp_all [clauseSat, litSat, atomVal, m.respects_3]
  · subst h; cases hv1 : (m.α 2) <;> cases hv3 : (m.α 4) <;> cases hv6 : (m.α 7) <;> simp_all [clauseSat, litSat, atomVal, m.respects_3]
  · subst h; cases hv1 : (m.α 2) <;> cases hv3 : (m.α 4) <;> cases hv6 : (m.α 7) <;> simp_all [clauseSat, litSat, atomVal, m.respects_3]
  · subst h; cases hv5 : (m.α 6) <;> cases hv5 : (m.α 6) <;> simp_all [clauseSat, litSat, atomVal, m.respects_4]
  · subst h; cases hv5 : (m.α 6) <;> cases hv5 : (m.α 6) <;> simp_all [clauseSat, litSat, atomVal, m.respects_4]
  · subst h; cases hv7 : (m.α 8) <;> cases hv7 : (m.α 8) <;> simp_all [clauseSat, litSat, atomVal, m.respects_5]
  · subst h; cases hv7 : (m.α 8) <;> cases hv7 : (m.α 8) <;> simp_all [clauseSat, litSat, atomVal, m.respects_5]

/-- No gate-respecting assignment satisfies the obligation — bit-blasting
    through the verified firewall (per-gate validity + `lratCheck`). -/
theorem no_model : ∀ m : Val, ¬ Sat (atomVal m) (clauses original) :=
  firewall_combined_unsat (original := original) (lemmas := lemmas) (proof := proof)
    atomVal (by decide) (by decide) lemmas_valid (by decide)

end AySoundness.CombinedBvBlastChain
