import AySoundness.Firewall
/-! Auto-generated by AY: bit-blast UNSAT for `(not (= (bvand a b) (bvand a b)))`, grounded in the verified
    firewall `AySoundness.firewall_combined_unsat` + `lratCheck_sound`. -/
namespace AySoundness.CombinedBvBlastRendered
open AySoundness

/-- A gate-respecting assignment: `α` plus, per gate, a proof that the
    output bit equals `gateEval` of its inputs. -/
structure Val where
  α : Nat → Bool
  respects_0 : α 3 = ((α 1) && (α 2))
  respects_1 : α 4 = (!(Bool.xor (α 3) (α 3)))

def atomVal (m : Val) (n : Nat) : Bool := m.α n

/-- A witness assignment (topological gate eval over all-false inputs): it
    certifies `Val` is inhabited, so `no_model` below is non-vacuous. -/
def wα : Nat → Bool := fun n => match n with
  | 3 => false
  | 4 => true
  | _ => false

theorem val_inhabited : Nonempty Val :=
  ⟨{ α := wα, respects_0 := by decide, respects_1 := by decide }⟩

def original : List (Cid × Clause) := [(7, [-4])]
def lemmas : List (Cid × Clause) := [(1, [-3, 1, 2]), (2, [-3, -1, 2]), (3, [-3, 1, -2]), (4, [3, -1, -2]), (5, [4, 3]), (6, [4, -3])]

def proof : List (Cid × Clause × List Int) := [
  (8, [4], [6, 5]),
  (9, [], [7, 8])
]

/-- Every gate Tseitin clause holds under any gate-respecting assignment:
    per clause, case-split that gate's inputs and apply its `respects_*`. -/
theorem lemmas_valid :
    ∀ cl ∈ clauses lemmas, ∀ m : Val, clauseSat (atomVal m) cl = true := by
  intro cl hcl m
  simp only [clauses, lemmas, List.map_cons, List.map_nil, List.mem_cons,
    List.not_mem_nil, or_false] at hcl
  rcases hcl with h | h | h | h | h | h
  · subst h; cases hv0 : (m.α 1) <;> cases hv1 : (m.α 2) <;> simp_all [clauseSat, litSat, atomVal, m.respects_0]
  · subst h; cases hv0 : (m.α 1) <;> cases hv1 : (m.α 2) <;> simp_all [clauseSat, litSat, atomVal, m.respects_0]
  · subst h; cases hv0 : (m.α 1) <;> cases hv1 : (m.α 2) <;> simp_all [clauseSat, litSat, atomVal, m.respects_0]
  · subst h; cases hv0 : (m.α 1) <;> cases hv1 : (m.α 2) <;> simp_all [clauseSat, litSat, atomVal, m.respects_0]
  · subst h; cases hv2 : (m.α 3) <;> cases hv2 : (m.α 3) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]
  · subst h; cases hv2 : (m.α 3) <;> cases hv2 : (m.α 3) <;> simp_all [clauseSat, litSat, atomVal, m.respects_1]

/-- No gate-respecting assignment satisfies the obligation — bit-blasting
    through the verified firewall (per-gate validity + `lratCheck`). -/
theorem no_model : ∀ m : Val, ¬ Sat (atomVal m) (clauses original) :=
  firewall_combined_unsat (original := original) (lemmas := lemmas) (proof := proof)
    atomVal (by decide) (by decide) lemmas_valid (by decide)

end AySoundness.CombinedBvBlastRendered
