/-
  Soundness of EUF congruence-closure equality reasoning (uninterpreted
  functions + equality), a core theory validator alongside Farkas (LIA/LRA) and
  the LRAT/RUP checker.

  ay's EUF / congruence-closure engine derives equalities `a = b` from a set of
  assumed equalities by the rules of an equivalence relation (reflexivity,
  symmetry, transitivity) closed under CONGRUENCE: if `aᵢ = bᵢ` pointwise, then
  `f a₁ … aₙ = f b₁ … bₙ`. The conflict it reports is a derived `a = b` together
  with an asserted `a ≠ b`.

  We prove the soundness PRINCIPLE here (`der_sound`): in EVERY interpretation
  that satisfies the assumed equalities, any derived equality holds — because the
  interpretation evaluates `app f args` as `Fn f (args.map ev)`, so function
  application RESPECTS structure and pointwise-equal arguments yield equal
  results. The conflict corollary (`der_conflict_unsat`) then says a derived
  `a = b` makes an asserted `a ≠ b` unsatisfiable.

  The derivability relation is purely syntactic (it never looks at any model);
  soundness is the statement that it is contained in semantic equality for every
  model. The `Example` section congruence-derives a real two-step fact and
  kernel-checks both the derivation and the soundness instance. Pure Lean 4 core
  (no Mathlib).
-/
namespace AySoundness.Euf

/-! ## Term language: atoms and (uninterpreted) function applications. -/

inductive Tm where
  | atom (n : Nat)
  | app  (f : Nat) (args : List Tm)

/-! ## Interpretations over an arbitrary value type `V`.

    `A` interprets atoms, `Fn` interprets function symbols on argument-value
    lists. Evaluation `ev` is total and structural: `app f args` evaluates to
    `Fn f` applied to the list of evaluated arguments — this is exactly what
    makes congruence sound (equal argument values give equal results). -/

structure Interp (V : Type) where
  A  : Nat → V
  Fn : Nat → List V → V

-- Evaluation. Defined mutually with the list-map so it is structurally
-- recursive (avoids `List.map ev` well-founded-recursion issues, and keeps
-- everything reducible by `decide`/`simp`).
mutual
  def ev {V : Type} (I : Interp V) : Tm → V
    | .atom n     => I.A n
    | .app f args => I.Fn f (evList I args)
  def evList {V : Type} (I : Interp V) : List Tm → List V
    | []      => []
    | t :: ts => ev I t :: evList I ts
end

/-- `evList` agrees with mapping `ev`; the bridge relating pointwise argument
    equality to list equality. -/
theorem evList_eq_map {V : Type} (I : Interp V) :
    ∀ ts : List Tm, evList I ts = ts.map (ev I)
  | []      => rfl
  | t :: ts => by simp [evList, List.map, evList_eq_map I ts]

/-! ## Derivability: an equivalence relation generated by `eqs`, closed under
    congruence. `DerAll` is the pointwise lifting of `Der` to argument lists,
    used by the `cong` rule. Both purely syntactic. -/

mutual
  inductive Der (eqs : List (Tm × Tm)) : Tm → Tm → Prop where
    | assum {a b : Tm} : (a, b) ∈ eqs → Der eqs a b
    | refl  (a : Tm)   : Der eqs a a
    | symm  {a b : Tm} : Der eqs a b → Der eqs b a
    | trans {a b c : Tm} : Der eqs a b → Der eqs b c → Der eqs a c
    | cong  {f : Nat} {args args' : List Tm} :
        DerAll eqs args args' → Der eqs (.app f args) (.app f args')
  /-- Pointwise derivability on argument lists (same length, pointwise `Der`). -/
  inductive DerAll (eqs : List (Tm × Tm)) : List Tm → List Tm → Prop where
    | nil  : DerAll eqs [] []
    | cons {a b : Tm} {as bs : List Tm} :
        Der eqs a b → DerAll eqs as bs → DerAll eqs (a :: as) (b :: bs)
end

/-! ## Soundness: derivability ⊆ semantic equality, in every model of `eqs`. -/

/-- The assumptions hold in `I`: every assumed equality is true semantically. -/
def Models {V : Type} (I : Interp V) (eqs : List (Tm × Tm)) : Prop :=
  ∀ p ∈ eqs, ev I p.1 = ev I p.2

/-- **EUF soundness (main theorem).** In any interpretation satisfying the
    assumed equalities, every derived equality holds. Proved by the mutual
    recursor of `Der`/`DerAll` (`Der.rec`), with the `DerAll` motive
    `evList I as = evList I bs`: the `cong` case uses that `ev (app f args)` is
    `Fn f` of the evaluated args, so equal argument-value lists give equal
    results. -/
theorem der_sound {V : Type} {I : Interp V} {eqs : List (Tm × Tm)}
    (hM : Models I eqs) {a b : Tm} (d : Der eqs a b) : ev I a = ev I b := by
  refine Der.rec
    (motive_1 := fun a b _ => ev I a = ev I b)
    (motive_2 := fun as bs _ => evList I as = evList I bs)
    ?assum ?refl ?symm ?trans ?cong ?nil ?cons d
  case assum => intro a b h; exact hM _ h
  case refl => intro a; rfl
  case symm => intro a b _ ih; exact ih.symm
  case trans => intro a b c _ _ ih1 ih2; exact ih1.trans ih2
  case cong =>
    intro f args args' _ ihAll
    show I.Fn f (evList I args) = I.Fn f (evList I args')
    rw [ihAll]
  case nil => rfl
  case cons =>
    intro a b as bs _ _ ihHead ihTail
    show ev I a :: evList I as = ev I b :: evList I bs
    rw [ihHead, ihTail]

/-- Pointwise soundness on argument lists, exported (same mutual recursion). -/
theorem derAll_sound {V : Type} {I : Interp V} {eqs : List (Tm × Tm)}
    (hM : Models I eqs) {as bs : List Tm} (d : DerAll eqs as bs) :
    evList I as = evList I bs := by
  refine DerAll.rec
    (motive_1 := fun a b _ => ev I a = ev I b)
    (motive_2 := fun as bs _ => evList I as = evList I bs)
    ?assum ?refl ?symm ?trans ?cong ?nil ?cons d
  case assum => intro a b h; exact hM _ h
  case refl => intro a; rfl
  case symm => intro a b _ ih; exact ih.symm
  case trans => intro a b c _ _ ih1 ih2; exact ih1.trans ih2
  case cong =>
    intro f args args' _ ihAll
    show I.Fn f (evList I args) = I.Fn f (evList I args')
    rw [ihAll]
  case nil => rfl
  case cons =>
    intro a b as bs _ _ ihHead ihTail
    show ev I a :: evList I as = ev I b :: evList I bs
    rw [ihHead, ihTail]

/-! ## Conflict corollary: a derived equality refutes an asserted disequality. -/

/-- **EUF conflict soundness.** If `Der eqs a b` is derivable, then there is no
    interpretation that satisfies all the assumed equalities yet makes `a ≠ b`.
    This is exactly the unsatisfiability of the conflict `{eqs, a ≠ b}` that the
    congruence-closure engine reports. -/
theorem der_conflict_unsat {V : Type} {eqs : List (Tm × Tm)} {a b : Tm}
    (d : Der eqs a b) :
    ¬ ∃ I : Interp V, Models I eqs ∧ ev I a ≠ ev I b := by
  rintro ⟨I, hM, hne⟩
  exact hne (der_sound hM d)

/-! ## Concrete example (kernel-checked).

    Atoms `x = atom 0`, `y = atom 1`, `z = atom 2`; function symbol `f = 0`.
    Assumptions  `eqs = [(x, y), (y, z)]`  i.e. `x = y` and `y = z`.

    We DERIVE  `app f [x] = app f [z]`  by:
      1. `trans` of the two assumptions:        `x = z`,
      2. `cong` (one argument) through `f`:      `f x = f z`.
    Then `der_conflict_unsat` shows asserting `f x ≠ f z` on top of the
    assumptions is unsatisfiable — a real congruence-closure conflict. -/

namespace Example

/-- `x`, `y`, `z` and the function symbol `f`. -/
def x : Tm := .atom 0
def y : Tm := .atom 1
def z : Tm := .atom 2
def f : Nat := 0
def eqs : List (Tm × Tm) := [(x, y), (y, z)]

/-- Step 1: `x = z` by transitivity of the two assumptions, going through `y`.
    Memberships are built from list constructors (no `DecidableEq Tm` needed). -/
def der_xz : Der eqs x z :=
  Der.trans (b := y)
    (Der.assum (a := x) (b := y) List.mem_cons_self)                      -- (x, y) ∈ eqs
    (Der.assum (a := y) (b := z) (List.mem_cons_of_mem _ List.mem_cons_self)) -- (y, z) ∈ eqs

/-- Step 2: `f x = f z` by single-argument congruence. -/
def der_fxfz : Der eqs (.app f [x]) (.app f [z]) :=
  Der.cong (DerAll.cons der_xz DerAll.nil)

/-- The derived congruence equality refutes an asserted disequality: there is no
    interpretation (over any value type) satisfying `x = y`, `y = z` yet making
    `f x ≠ f z`. This is the unsatisfiability of the congruence-closure
    conflict. -/
theorem fxfz_conflict_unsat {V : Type} :
    ¬ ∃ I : Interp V, Models I eqs ∧ ev I (.app f [x]) ≠ ev I (.app f [z]) :=
  der_conflict_unsat der_fxfz

/-- A concrete witness that the assumptions are genuinely satisfiable (so the
    soundness statement is NON-vacuous: there are models of `eqs`, and in each
    the derived equality holds). The interpretation collapses `0,1,2` to the same
    value, so both assumptions hold; `f` is the identity-on-head. -/
def witness : Interp Nat where
  A  := fun _ => 7
  Fn := fun _ vs => vs.headD 0

theorem witness_models : Models witness eqs := by
  intro p hp
  -- both assumed pairs evaluate to `7 = 7` under `witness`.
  rcases List.mem_cons.mp hp with h | h
  · subst h; rfl
  · rcases List.mem_cons.mp h with h | h
    · subst h; rfl
    · exact absurd h (by simp)

/-- And in that model the derived equality really holds (instance of `der_sound`),
    evaluating both sides to `7`. -/
theorem witness_derived_holds :
    ev witness (.app f [x]) = ev witness (.app f [z]) :=
  der_sound witness_models der_fxfz

/-- Kernel-checked sanity: both sides compute to `7`. -/
example : ev witness (.app f [x]) = 7 ∧ ev witness (.app f [z]) = 7 := by decide

end Example

end AySoundness.Euf