// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

//! Parser-level SyGuS command support.
//!
//! The frontend keeps grammar expansions as raw S-expressions for now. SyGuS
//! grammars allow nonterminal references and constructor forms such as
//! `(Constant Int)` that are not ordinary SMT terms until a synthesis engine
//! interprets the grammar.

use crate::sexp::{ParseError, SExpr};

use super::Sort;

/// A SyGuS grammar attached to `synth-fun` or `synth-inv`.
#[derive(Debug, Clone, PartialEq)]
pub struct SygusGrammar {
    /// Nonterminal definitions in declaration order.
    pub nonterminals: Vec<SygusGrammarRule>,
}

/// One SyGuS nonterminal definition.
#[derive(Debug, Clone, PartialEq)]
pub struct SygusGrammarRule {
    /// Nonterminal symbol name.
    pub name: String,
    /// Sort generated by this nonterminal.
    pub sort: Sort,
    /// Raw production alternatives.
    pub expansions: Vec<SExpr>,
}

impl SygusGrammar {
    pub(crate) fn from_sexp(sexp: &SExpr) -> Result<Self, ParseError> {
        let entries = sexp
            .as_list()
            .ok_or_else(|| ParseError::new("SyGuS grammar must be a list"))?;
        if entries.is_empty() {
            return Err(ParseError::new("SyGuS grammar requires nonterminals"));
        }

        let mut nonterminals = Vec::with_capacity(entries.len());
        for entry in entries {
            let parts = entry
                .as_list()
                .ok_or_else(|| ParseError::new("SyGuS grammar rule must be a list"))?;
            if parts.len() != 3 {
                return Err(ParseError::new(
                    "SyGuS grammar rule must be (name sort (expansion+))",
                ));
            }

            let name = parts[0]
                .as_symbol()
                .ok_or_else(|| ParseError::new("SyGuS grammar rule name must be a symbol"))?;
            let sort = Sort::from_sexp(&parts[1])?;
            let expansions = parts[2]
                .as_list()
                .ok_or_else(|| ParseError::new("SyGuS grammar expansions must be a list"))?;
            if expansions.is_empty() {
                return Err(ParseError::new(
                    "SyGuS grammar rule requires at least one expansion",
                ));
            }

            nonterminals.push(SygusGrammarRule {
                name: name.to_string(),
                sort,
                expansions: expansions.to_vec(),
            });
        }

        Ok(Self { nonterminals })
    }
}
