// Copyright 2026 Andrew Yates
// SPDX-License-Identifier: Apache-2.0

#![forbid(unsafe_code)]
//! AY Seq - Generic sequence theory solver
//!
//! Implements the theory of parametric sequences `(Seq T)` for arbitrary
//! element types. This is distinct from the string theory: `Sort::String`
//! continues to use the specialized string solver, while `Sort::Seq(T)` uses
//! this solver.
//!
//! ## Axioms handled by this crate
//!
//! - **Unit injectivity**: `seq.unit(a) = seq.unit(b) → a = b`
//! - **Unit-empty conflict**: `seq.unit(x) ≠ seq.empty`
//!
//! Length and nth axioms (length of unit/empty/concat, length non-negative,
//! nth of unit) are generated by the DPLL(T) adapter in
//! `ay-dpll/src/executor/theories/seq.rs`.
#![warn(missing_docs)]
#![warn(clippy::all)]

mod theory_impl;
#[cfg(kani)]
mod verification;

// #8529: Use deterministic hash maps in all builds.
use ay_core::kani_compat::DetHashMap as HashMap;
use ay_core::term::{Constant, TermData, TermId, TermStore};
use ay_core::{
    DiscoveredEquality, EqualityPropagationResult, TheoryLit, TheoryPropagation, TheoryResult,
    TheorySolver,
};
use num_bigint::BigInt;

/// Model for the sequence theory — maps Seq-sorted variables to concrete
/// sequences of element values (formatted strings).
#[derive(Debug, Clone, Default)]
pub struct SeqModel {
    /// Maps Seq-sorted variable term IDs to their concrete sequence of
    /// element values (as formatted strings).
    pub values: HashMap<TermId, Vec<String>>,
}

/// Sequence theory solver.
///
/// Handles unit injectivity and unit-empty conflict detection.
/// Eagerly propagates equalities from `seq.unit` congruence.
pub struct SeqSolver<'a> {
    terms: &'a TermStore,
    /// Current Boolean assignments: atom → value.
    assigns: HashMap<TermId, bool>,
    /// Trail for backtracking: (atom, previous_value).
    trail: Vec<(TermId, Option<bool>)>,
    /// Scope markers (trail positions for push/pop).
    scopes: Vec<usize>,
    /// Cached seq.unit terms: unit_term → element_arg.
    unit_cache: HashMap<TermId, TermId>,
    /// Cached seq.len terms: len_term → sequence_arg.
    len_cache: HashMap<TermId, TermId>,
    /// Cached seq.++ terms: concat_term → [arg1, arg2, ...].
    concat_cache: HashMap<TermId, Vec<TermId>>,
    /// Cached seq.empty terms (zero-arity apps).
    empty_cache: Vec<TermId>,
    /// Cached seq.nth terms: nth_term → (seq_arg, index_arg).
    nth_cache: HashMap<TermId, (TermId, TermId)>,
    /// Equality atoms: eq_term → (lhs, rhs).
    equality_cache: HashMap<TermId, (TermId, TermId)>,
    /// Pending propagations.
    pending_propagations: Vec<TheoryPropagation>,
    /// Pending equalities for Nelson-Oppen.
    pending_equalities: Vec<DiscoveredEquality>,
    /// Shared equalities received from Nelson-Oppen exchange (EUF → Seq).
    /// Each entry is (lhs, rhs, reason). Checked by `check()` for
    /// unit-empty conflicts and unit injectivity. See #5951.
    shared_equalities: Vec<(TermId, TermId, Vec<TheoryLit>)>,
    /// Trail of shared equality indices for backtracking.
    shared_eq_scopes: Vec<usize>,
    /// Dirty flag: need to re-check.
    dirty: bool,
}

impl<'a> SeqSolver<'a> {
    /// Create a new sequence solver with a reference to the term store.
    pub fn new(terms: &'a TermStore) -> Self {
        Self {
            terms,
            assigns: HashMap::default(),
            trail: Vec::new(),
            scopes: Vec::new(),
            unit_cache: HashMap::default(),
            len_cache: HashMap::default(),
            concat_cache: HashMap::default(),
            empty_cache: Vec::new(),
            nth_cache: HashMap::default(),
            equality_cache: HashMap::default(),
            pending_propagations: Vec::new(),
            pending_equalities: Vec::new(),
            shared_equalities: Vec::new(),
            shared_eq_scopes: Vec::new(),
            dirty: false,
        }
    }

    /// Returns all cached unit term IDs.
    pub fn unit_terms(&self) -> impl Iterator<Item = TermId> + '_ {
        self.unit_cache.keys().copied()
    }

    /// Returns the element argument for a unit term, if cached.
    pub fn unit_element(&self, term: TermId) -> Option<TermId> {
        self.unit_cache.get(&term).copied()
    }

    /// Returns all cached empty term IDs.
    pub fn empty_terms(&self) -> impl Iterator<Item = TermId> + '_ {
        self.empty_cache.iter().copied()
    }

    /// Extract a model for Seq-sorted variables.
    ///
    /// Builds concrete sequence values from asserted equalities and the
    /// structure of unit/concat/empty terms.
    pub fn extract_model(&self) -> SeqModel {
        let mut values = HashMap::default();

        // For each Seq-sorted variable, try to determine its concrete value
        // from asserted equalities.
        for (&eq_term, &(lhs, rhs)) in &self.equality_cache {
            if self.assigns.get(&eq_term) != Some(&true) {
                continue;
            }
            Self::try_insert_seq_value(&mut values, lhs, rhs, self.terms, self);
            Self::try_insert_seq_value(&mut values, rhs, lhs, self.terms, self);
        }

        // Also check shared equalities from Nelson-Oppen exchange (EUF → Seq).
        // These are equalities discovered by EUF congruence/transitivity that
        // involve Seq-sorted terms but were never direct assertion atoms.
        for (lhs, rhs, _reason) in &self.shared_equalities {
            Self::try_insert_seq_value(&mut values, *lhs, *rhs, self.terms, self);
            Self::try_insert_seq_value(&mut values, *rhs, *lhs, self.terms, self);
        }

        SeqModel { values }
    }

    /// If `candidate` is a Seq-sorted variable and `value_term` can be
    /// concretized, insert the mapping into `values`.
    fn try_insert_seq_value(
        values: &mut HashMap<TermId, Vec<String>>,
        candidate: TermId,
        value_term: TermId,
        terms: &TermStore,
        solver: &Self,
    ) {
        if let TermData::Var(_, _) = terms.get(candidate) {
            if terms.sort(candidate).is_seq() {
                if let Some(elems) = solver.extract_seq_value(value_term) {
                    values.insert(candidate, elems);
                }
            }
        }
    }

    /// Try to extract a concrete sequence value from a term.
    /// Returns `Some(vec_of_element_strings)` for constructible terms,
    /// `None` for symbolic terms that can't be concretized.
    fn extract_seq_value(&self, term: TermId) -> Option<Vec<String>> {
        // seq.empty → []
        if self.empty_cache.contains(&term) {
            return Some(Vec::new());
        }
        // seq.unit(x) → [format(x)]
        if let Some(&elem) = self.unit_cache.get(&term) {
            return Some(vec![self.format_term_value(elem)]);
        }
        // seq.++(a, b) → extract(a) ++ extract(b)
        if let Some(args) = self.concat_cache.get(&term) {
            let mut result = Vec::new();
            for &arg in args {
                let sub = self.extract_seq_value(arg)?;
                result.extend(sub);
            }
            return Some(result);
        }
        None
    }

    /// Format a term's value for SMT-LIB model output.
    fn format_term_value(&self, term: TermId) -> String {
        match self.terms.get(term) {
            TermData::Const(c) => match c {
                Constant::Bool(b) => format!("{b}"),
                Constant::Int(n) => {
                    if *n < BigInt::from(0) {
                        format!("(- {})", -n)
                    } else {
                        format!("{n}")
                    }
                }
                Constant::Rational(r) => {
                    let n = r.0.numer();
                    let d = r.0.denom();
                    if *d == BigInt::from(1) {
                        format!("{n}")
                    } else {
                        format!("(/ {n} {d})")
                    }
                }
                Constant::BitVec { value, width } => {
                    format!("(_ bv{value} {width})")
                }
                Constant::String(s) => format!("\"{s}\""),
                _ => format!("{c:?}"),
            },
            TermData::Var(name, _) => name.clone(),
            _ => format!("t{}", term.0),
        }
    }

    /// Register a term and its subterms in the solver's caches.
    fn cache_term(&mut self, term: TermId) {
        if let TermData::App(sym, args) = self.terms.get(term) {
            let name = sym.name();
            match name {
                "seq.unit" if args.len() == 1 => {
                    self.unit_cache.insert(term, args[0]);
                }
                "seq.len" if args.len() == 1 => {
                    self.len_cache.insert(term, args[0]);
                }
                "seq.++" if args.len() >= 2 => {
                    let sub_args = args.clone();
                    self.concat_cache.insert(term, sub_args.clone());
                    // Recursively cache concat arguments so extract_seq_value
                    // can resolve nested seq.unit / seq.empty / seq.++ terms.
                    for arg in sub_args {
                        self.cache_term(arg);
                    }
                }
                "seq.empty" if args.is_empty() && !self.empty_cache.contains(&term) => {
                    self.empty_cache.push(term);
                }
                "seq.nth" if args.len() == 2 => {
                    self.nth_cache.insert(term, (args[0], args[1]));
                }
                "=" if args.len() == 2 => {
                    // Cache equality atoms involving Seq sorts.
                    // Recursively cache both sides so extract_model can
                    // concretize the Seq value from the equality.
                    let lhs_sort = self.terms.sort(args[0]);
                    let rhs_sort = self.terms.sort(args[1]);
                    if lhs_sort.is_seq() || rhs_sort.is_seq() {
                        let lhs = args[0];
                        let rhs = args[1];
                        self.equality_cache.insert(term, (lhs, rhs));
                        self.cache_term(lhs);
                        self.cache_term(rhs);
                    }
                }
                _ => {}
            }
        }
    }

    /// Check for unit injectivity: seq.unit(a) = seq.unit(b) → a = b.
    /// Produces Nelson-Oppen equalities.
    fn check_unit_injectivity(&mut self) {
        // From directly asserted equality atoms.
        for (&eq_term, &(lhs, rhs)) in &self.equality_cache {
            if self.assigns.get(&eq_term) != Some(&true) {
                continue;
            }
            if let (Some(&elem_a), Some(&elem_b)) =
                (self.unit_cache.get(&lhs), self.unit_cache.get(&rhs))
            {
                if elem_a != elem_b {
                    self.pending_equalities.push(DiscoveredEquality {
                        lhs: elem_a,
                        rhs: elem_b,
                        reason: vec![TheoryLit {
                            term: eq_term,
                            value: true,
                        }],
                    });
                }
            }
        }

        // From shared equalities received via Nelson-Oppen (#5951).
        let shared = std::mem::take(&mut self.shared_equalities);
        for &(lhs, rhs, ref reason) in &shared {
            if let (Some(&elem_a), Some(&elem_b)) =
                (self.unit_cache.get(&lhs), self.unit_cache.get(&rhs))
            {
                if elem_a != elem_b {
                    self.pending_equalities.push(DiscoveredEquality {
                        lhs: elem_a,
                        rhs: elem_b,
                        reason: reason.clone(),
                    });
                }
            }
        }
        self.shared_equalities = shared;
    }

    /// Flatten a sequence built only from `seq.unit` / `seq.empty` / `seq.++`
    /// into the list of its element terms (the argument of each `seq.unit`).
    ///
    /// Returns `false` if `term` contains any non-structural sub-sequence — a
    /// variable, an uninterpreted seq, `seq.extract`, etc. — in which case the
    /// length and elements are not statically determined and no sound positional
    /// reasoning is possible. `seq.empty` contributes no elements.
    fn flatten_seq(&self, term: TermId, out: &mut Vec<TermId>) -> bool {
        match self.terms.get(term) {
            TermData::App(sym, args) => match sym.name() {
                "seq.unit" if args.len() == 1 => {
                    out.push(args[0]);
                    true
                }
                "seq.empty" if args.is_empty() => true,
                "seq.++" if args.len() >= 2 => {
                    for &arg in args {
                        if !self.flatten_seq(arg, out) {
                            return false;
                        }
                    }
                    true
                }
                _ => false,
            },
            _ => false,
        }
    }

    /// Flatten nested `seq.++` into the ordered top-level operand list. Each
    /// non-concat operand (symbolic seq, `seq.unit`, `seq.empty`) is a leaf:
    /// `(a++b)++c` and `a++(b++c)` both flatten to `[a, b, c]`. Unlike
    /// [`Self::flatten_seq`], operands need not be element-determined, so this
    /// works for symbolic sequences (used for structural concat equality —
    /// associativity over opaque operands).
    fn flatten_concat_operands(&self, term: TermId, out: &mut Vec<TermId>) {
        if let TermData::App(sym, args) = self.terms.get(term) {
            if sym.name() == "seq.++" && args.len() >= 2 {
                for &arg in args {
                    self.flatten_concat_operands(arg, out);
                }
                return;
            }
        }
        out.push(term);
    }

    /// Whether two element terms are provably equal: identical term IDs, or two
    /// equal constants.
    fn elem_provably_eq(&self, a: TermId, b: TermId) -> bool {
        if a == b {
            return true;
        }
        matches!(
            (self.terms.get(a), self.terms.get(b)),
            (TermData::Const(ca), TermData::Const(cb)) if ca == cb
        )
    }

    /// Decide equality between sequences built from `seq.unit` / `seq.empty` /
    /// `seq.++` (concat extensionality).
    ///
    /// Two such structural sequences are equal iff they have the same length and
    /// equal elements at every index. Without this rule `seq.++` is an
    /// uninterpreted function in EUF (congruence is forward-only), so
    /// `(seq.++ (seq.unit 1) (seq.unit 2)) = (seq.++ (seq.unit 1) (seq.unit 3))`
    /// is wrongly satisfiable. For each cached equality atom with at least one
    /// `seq.++` side whose *both* sides flatten to fully-determined element
    /// lists:
    ///
    /// * asserted **true** → a length mismatch, or a position whose two elements
    ///   are distinct constants, is an immediate conflict; any other differing
    ///   position propagates a positional element equality (Nelson-Oppen), which
    ///   unit injectivity / EUF / LIA then resolve;
    /// * asserted **false** → if the two element lists are provably equal
    ///   position-by-position, the disequality is itself a conflict.
    ///
    /// Plain `seq.unit = seq.unit` / `seq.unit = seq.empty` atoms are left to
    /// [`Self::check_unit_injectivity`] / [`Self::check_unit_empty_conflict`] to
    /// avoid emitting duplicate propagations.
    fn check_concat_equality(&mut self) -> Option<Vec<TheoryLit>> {
        // Snapshot assigned equality atoms so we can call `&self` helpers and
        // push pending equalities without holding a borrow on `equality_cache`.
        let atoms: Vec<(TermId, TermId, TermId, bool)> = self
            .equality_cache
            .iter()
            .filter_map(|(&eq_term, &(lhs, rhs))| {
                self.assigns
                    .get(&eq_term)
                    .map(|&value| (eq_term, lhs, rhs, value))
            })
            .collect();

        for (eq_term, lhs, rhs, value) in atoms {
            // Only handle atoms that involve a concat; plain unit/empty atoms are
            // already covered by the unit rules.
            if !self.concat_cache.contains_key(&lhs) && !self.concat_cache.contains_key(&rhs) {
                continue;
            }

            // Structural concat equality (handles SYMBOLIC operands, which the
            // element-level `flatten_seq` below cannot). Flatten nested `seq.++`
            // to the ordered top-level operand list: `(a++b)++c` and `a++(b++c)`
            // both flatten to `[a, b, c]`. Identical operand lists ⇒ the two
            // sequences are equal by associativity of concat, regardless of
            // element determinacy. SOUND: same operands in the same order denote
            // the same sequence (this does NOT claim commutativity, and differing
            // lengths/orders fall through). A `false`-asserted atom over
            // structurally identical concats is therefore a conflict; this is
            // what lets symbolic `(a++b)++c == a++(b++c)` verify (#2779).
            let mut lo = Vec::new();
            let mut ro = Vec::new();
            self.flatten_concat_operands(lhs, &mut lo);
            self.flatten_concat_operands(rhs, &mut ro);
            if lo == ro {
                if !value {
                    return Some(vec![TheoryLit {
                        term: eq_term,
                        value: false,
                    }]);
                }
                // Asserted equal and structurally equal: consistent, nothing to
                // propagate. (Element-level handling below would be redundant.)
                continue;
            }

            let mut le = Vec::new();
            let mut re = Vec::new();
            if !self.flatten_seq(lhs, &mut le) || !self.flatten_seq(rhs, &mut re) {
                continue;
            }

            if value {
                if le.len() != re.len() {
                    return Some(vec![TheoryLit {
                        term: eq_term,
                        value: true,
                    }]);
                }
                for (&a, &b) in le.iter().zip(re.iter()) {
                    if a == b {
                        continue;
                    }
                    if let (TermData::Const(ca), TermData::Const(cb)) =
                        (self.terms.get(a), self.terms.get(b))
                    {
                        if ca != cb {
                            // Two distinct constants at the same index — the two
                            // sequences cannot be equal.
                            return Some(vec![TheoryLit {
                                term: eq_term,
                                value: true,
                            }]);
                        }
                        continue;
                    }
                    // Symbolic element(s): propagate the positional equality.
                    self.pending_equalities.push(DiscoveredEquality {
                        lhs: a,
                        rhs: b,
                        reason: vec![TheoryLit {
                            term: eq_term,
                            value: true,
                        }],
                    });
                }
            } else if le.len() == re.len()
                && le
                    .iter()
                    .zip(re.iter())
                    .all(|(&a, &b)| self.elem_provably_eq(a, b))
            {
                // Asserted distinct, but the two element lists are provably equal.
                return Some(vec![TheoryLit {
                    term: eq_term,
                    value: false,
                }]);
            }
        }

        None
    }

    /// Check for basic conflict: seq.unit(a) = seq.empty is unsat.
    fn check_unit_empty_conflict(&self) -> Option<Vec<TheoryLit>> {
        // Check directly asserted equality atoms.
        for (&eq_term, &(lhs, rhs)) in &self.equality_cache {
            if self.assigns.get(&eq_term) != Some(&true) {
                continue;
            }
            let lhs_is_unit = self.unit_cache.contains_key(&lhs);
            let rhs_is_unit = self.unit_cache.contains_key(&rhs);
            let lhs_is_empty = self.empty_cache.contains(&lhs);
            let rhs_is_empty = self.empty_cache.contains(&rhs);

            if (lhs_is_unit && rhs_is_empty) || (rhs_is_unit && lhs_is_empty) {
                return Some(vec![TheoryLit {
                    term: eq_term,
                    value: true,
                }]);
            }
        }

        // Check shared equalities received via Nelson-Oppen (#5951).
        for (lhs, rhs, reason) in &self.shared_equalities {
            let lhs_is_unit = self.unit_cache.contains_key(lhs);
            let rhs_is_unit = self.unit_cache.contains_key(rhs);
            let lhs_is_empty = self.empty_cache.contains(lhs);
            let rhs_is_empty = self.empty_cache.contains(rhs);

            if (lhs_is_unit && rhs_is_empty) || (rhs_is_unit && lhs_is_empty) {
                return Some(reason.clone());
            }
        }

        None
    }
}

#[cfg(test)]
#[path = "lib_tests.rs"]
mod tests;
