// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

//! Stable names and storage slots for engine tuning knobs.

mod kind;

pub(crate) use kind::Knob;

impl Knob {
    /// The environment variable that overrides this knob. B38: none — every
    /// knob is CLI/typed-carrier only, and the env snapshot layer this fed
    /// is inert (its removal is the follow-up commit).
    #[cfg(test)]
    pub(crate) const fn env(self) -> Option<&'static str> {
        let _ = self;
        None
    }

    /// Stable printable name used in diagnostics and configuration errors.
    pub(crate) const fn label(self) -> &'static str {
        match self {
            Self::NoVub => "no-vub",
            Self::NoMirGenint => "no-mir-genint",
            Self::NoSepScreen => "no-sep-screen",
            Self::NoFtFast => "no-ft-fast",
            Self::NoFtranFast => "no-ftran-fast",
            Self::NoFtranNzFast => "no-ftrannz-fast",
            Self::NoCountsort => "no-countsort",
            Self::NoCoefTighten => "no-coef-tighten",
            Self::NoOrbitope => "no-orbitope",
            Self::FtGrowthTol => "ft-growth-tol",
            Self::DualAnatomy => "dual-anatomy",
            Self::VerifyAfter => "verify-after",
            Self::NoFusedRt => "no-fused-rt",
            Self::NoRtKind => "no-rt-kind",
            Self::IterProfile => "iter-profile",
            Self::NoRtBitsKey => "no-rt-bits-key",
            Self::NoWideBloom => "no-wide-bloom",
            Self::NoEtaReuse => "no-eta-reuse",
            Self::NoDevex => "no-devex",
            Self::NoColdDual => "no-cold-dual",
            Self::NoTriCrash => "no-tri-crash",
            Self::ChainDevex => "chain-devex",
            Self::NoCutoff => "no-cutoff",
            Self::NoNodeLu => "no-node-lu",
            Self::NoTallLu => "no-tall-lu",
            Self::NoTallColdDual => "no-tall-cold-dual",
            Self::NoDualChurnBand => "no-dual-churn-band",
            Self::DualBloomCap => "dual-bloom-cap",
            Self::NoFlowcoverAgg => "no-flowcover-agg",
            Self::NoGiExt => "no-gi-ext",
            Self::NoBottleneckExt => "no-bottleneck-ext",
            Self::NoClique => "no-clique",
            Self::NoOddCycle => "no-odd-cycle",
            Self::NoCoverExt => "no-cover-ext",
            Self::NoFlowcover => "no-flowcover",
            Self::NoSnap => "no-snap",
            Self::NoSplns => "no-splns",
            Self::NoMsWalk => "no-ms-walk",
            Self::NoSweepProve => "no-sweep-prove",
            Self::NoRinsRescue => "no-rins-rescue",
            Self::NoSym => "no-sym",
            Self::SubmipBb => "submip-best-bound",
            Self::ZeroHalf => "zero-half",
            Self::OddCycle => "odd-cycle",
            Self::FlipReach => "flip-reach",
            Self::PropSweeps => "prop-sweeps",
            Self::PropQueue => "prop-queue",
            Self::SplnsExposed => "splns-exposed",
            Self::SplnsBudget => "splns-budget",
            Self::SplnsStall => "splns-stall",
            Self::MsWalkMoves => "ms-walk-moves",
            Self::GubMeasEvery => "gub-meas-every",
            Self::DiagCostPerturb => "diag-cost-perturb",
            Self::FcMode => "fc-mode",
            Self::FlipSolve => "flip-solve",
            Self::NoCertDecouple => "no-cert-decouple",
            Self::NoGubBranch => "no-gub-branch",
            Self::NoDedupCols => "no-dedup-cols",
            Self::NoBinaryComplementSub => "no-binary-complement-sub",
            Self::NoLbAct => "no-lb-act",
            Self::NoGiDfs => "no-gi-dfs",
            Self::NoImplCut => "no-impl-cut",
            Self::NoImplTab => "no-impl-tab",
            Self::NoKnapRedirect => "no-knap-redirect",
            Self::NoDiveSkip => "no-dive-skip",
            Self::NoCutFma => "no-cut-fma",
            Self::NoOddLift => "no-odd-lift",
            Self::NoStrongcg => "no-strongcg",
            Self::DenseGmiLu => "dense-gmi-lu",
            Self::NoChainShape => "no-chain-shape",
            Self::NoChainPreorder => "no-chain-preorder",
            Self::NoBumpLu => "no-bump-lu",
            Self::DualBypassMode => "dual-bypass-mode",
            Self::EagerPerturbMode => "eager-perturb-mode",
            Self::HarrisRt => "harris-rt",
            Self::SymBranchBand => "sym-branch-band",
            Self::Rins => "rins",
            Self::DualfixAll => "dualfix-all",
            Self::ImpliedBound => "implied-bound",
            Self::LiftedCover => "lifted-cover",
            Self::LnpBudget => "lnp-budget",
            Self::LatticeBkzBeta => "lattice-bkz-beta",
            Self::DualPerturb => "dual-perturb",
            Self::CertGraceSecs => "cert-grace-secs",
            Self::AnchorFirstRefusalMs => "anchor-first-refusal-ms",
            Self::RinsEvery => "rins-every",
            Self::RinsDrycap => "rins-drycap",
            Self::PumpShare => "pump-share",
            Self::SetpartShare => "setpart-share",
            Self::NoParity => "no-parity",
            Self::NoMarginReframe => "no-margin-reframe",
            Self::SymMode => "sym-mode",
            Self::HeurShare => "heur-share",
            Self::SbRel => "sb-rel",
            Self::SbCands => "sb-cands",
            Self::SbTotal => "sb-total",
            Self::NoPresolve => "no-presolve",
            Self::NoPresolveScout => "no-presolve-scout",
            Self::Vsids => "vsids",
            Self::RootProbeAll => "root-probe-all",
            Self::Sepstat => "sepstat",
            Self::LpStats => "lp-stats",
            Self::StepTraceN => "step-trace",
            Self::BumpDiag => "bump-diag",
            Self::BumpdiffLanes => "bumpdiff-lanes",
            Self::DiagPlainCold => "diag-plain-cold",
            Self::DumpVertex => "dump-vertex",
            Self::SmtLane => "smt-lane",
            Self::MaxNodes => "max-nodes",
            Self::StructElim => "struct-elim",
            Self::NoBoundCover => "no-bound-cover",
            Self::PumpIterMult => "pump-iter-mult",
            Self::NoPumpIterCap => "no-pump-iter-cap",
            Self::NgUp => "ng-up",
            Self::CutShadow => "cut-shadow",
            Self::ChainAgg => "chain-agg",
            Self::AutoMargin => "auto-margin",
            Self::ImplLane => "impl-lane",
            Self::ImplArm => "impl-arm",
            Self::DroughtDive => "drought-dive",
            Self::PropConflict => "prop-conflict",
            Self::LbConflict => "lb-conflict",
            Self::LbArm => "lb-arm",
            Self::LbStrict => "lb-strict",
            Self::SingletonSub => "singleton-sub",
            Self::AffineAgg => "affine-agg",
            Self::NodeCutSlots => "node-cut-slots",
            Self::NodeCutEvery => "node-cut-every",
            Self::NodeCutEager => "node-cut-eager",
            Self::AmoMultiway => "amo-multiway",
            Self::NodeGmi => "node-gmi",
            Self::NodeGmiEvery => "node-gmi-every",
            Self::NodeGmiMargin => "node-gmi-margin",
            Self::NodeRc => "node-rc",
            Self::NoRcCapGuard => "no-rc-cap-guard",
            Self::RootClosurePresolve => "root-closure-presolve",
            Self::TriCrashAll => "tri-crash-all",
            Self::SymBranch => "sym-branch",
            Self::StabOrbit => "stab-orbit",
            Self::Scale => "scale",
            Self::OrbitopeDyn => "orbitope-dyn",
            Self::NoTreeFloor => "no-tree-floor",
            Self::NoTreeBoundOutcome => "no-tree-bound-outcome",
            Self::NoRootFloor => "no-root-floor",
            Self::CoverMinimal => "cover-minimal",
            Self::GubClique => "gub-clique",
            Self::GmiCutTrace => "gmi-cut-trace",
            Self::CondTighten => "cond-tighten",
            Self::ModK => "mod-k",
            Self::KnapDbg => "knap-dbg",
            Self::MirAggRoot => "mir-agg-root",
            Self::ColdDualAll => "cold-dual-all",
            Self::CutWarm => "cut-warm",
            Self::Rlt => "rlt",
            Self::TableauMir => "tableau-mir",
            Self::DiveCommitStopped => "dive-commit-stopped",
            Self::NoRootWarm => "no-root-warm",
            Self::OrbitopeBranch => "orbitope-branch",
            Self::OrbitopeIlv => "orbitope-ilv",
            Self::OrbitopeBranchDyn => "orbitope-branch-dyn",
            Self::NodeCutLocal => "node-cut-local",
            Self::NoCondScout => "no-cond-scout",
            Self::NoFloat => "no-float",
            Self::HybridPbLp => "hybrid-pb-lp",
            Self::Attrib => "attrib",
            Self::Acensus => "acensus",
            Self::CutTopk => "cut-topk",
            Self::HybridTerm => "hybrid-term",
            Self::DiveProbeSecs => "dive-probe-secs",
            Self::SbProbeIters => "sb-probe-iters",
            Self::RensWindow => "rens-window",
            Self::RootProbeCap => "root-probe-cap",
            Self::RootProbeCliqueCap => "root-probe-clique-cap",
            Self::RootProbeNoLpRank => "root-probe-no-lp-rank",
            Self::RootProbeShare => "root-probe-share",
            Self::NodeCutBatch => "node-cut-batch",
            Self::NodeCutAge => "node-cut-age",
            Self::DualCutoff => "dual-cutoff",
            Self::MsDive => "ms-dive",
            Self::Mas74Plunge => "mas74-plunge",
            Self::MsDiveSteps => "ms-dive-steps",
            Self::PropFirst => "prop-first",
            Self::GmiMaxRows => "gmi-max-rows",
            Self::ChainProbe => "chain-probe",
            Self::BumpLuMin => "bump-lu-min",
            Self::ColdLuEtaRebuilds => "cold-lu-eta-rebuilds",
            Self::AdoptFtMaxRows => "adopt-ft-max-rows",
            Self::RefactorEvery => "refactor-every",
            Self::EtaCapMult => "eta-cap-mult",
            Self::LuMaxFillNnz => "lu-max-fill-nnz",
            Self::RelaxLift => "relax-lift",
            Self::Devex => "devex",
            Self::BumpBtf => "bump-btf",
            Self::NoMirKnap => "no-mir-knap",
            Self::GmiRounds => "gmi-rounds",
            Self::RootCutsPerRound => "root-cuts-per-round",
            Self::RootProbe => "root-probe",
            Self::Dfs => "dfs",
            Self::NodeCuts => "node-cuts",
            Self::NoLattice => "no-lattice",
            Self::NoSatStop => "no-sat-stop",
            Self::SatStopSecs => "sat-stop-secs",
            Self::SatStopMult => "sat-stop-mult",
            Self::NoBloomRelax => "no-bloom-relax",
            Self::FlipCapSecs => "flip-cap-secs",
            Self::FlipShare => "flip-share",
            Self::WarmLu => "warm-lu",
            Self::PresolveShare => "presolve-share",
            Self::NoCuts => "no-cuts",
            Self::PumpRestarts => "pump-restarts",
            Self::DiveMaxPins => "dive-max-pins",
            Self::NoDualfix => "no-dualfix",
            Self::NoKernelReform => "no-kernel-reform",
            Self::NoFeasConflict => "no-feas-conflict",
            Self::NoColdLu => "no-cold-lu",
            Self::Plunge => "plunge",
            Self::BbGate => "bb-gate",
            Self::ChildOrderMode => "child-order",
            Self::CutsPerRound => "cuts-per-round",
            Self::CutEffFloor => "cut-eff-floor",
            Self::FtSpikeArm => "ft-spike",
            Self::GubSb => "gub-sb",
            Self::NgBox => "ng-box",
            Self::NgBranchPct => "ng-branch-pct",
            Self::NodeProp => "node-prop",
            Self::SbSustain => "sb-sustain",
        }
    }

    pub(super) const ALL: [Knob; 226] = [
        Self::GmiRounds,
        Self::RootCutsPerRound,
        Self::RootProbe,
        Self::Dfs,
        Self::NodeCuts,
        Self::Plunge,
        Self::NoLattice,
        Self::NoSatStop,
        Self::SatStopSecs,
        Self::SatStopMult,
        Self::NoBloomRelax,
        Self::FlipCapSecs,
        Self::FlipShare,
        Self::WarmLu,
        Self::PresolveShare,
        Self::NoCuts,
        Self::PumpRestarts,
        Self::DiveMaxPins,
        Self::NoDualfix,
        Self::NoKernelReform,
        Self::NoCertDecouple,
        Self::NoFeasConflict,
        Self::NoColdLu,
        Self::NoVub,
        Self::NoMirGenint,
        Self::NoSepScreen,
        Self::NoFtFast,
        Self::NoFtranFast,
        Self::NoFtranNzFast,
        Self::NoCountsort,
        Self::NoCoefTighten,
        Self::NoOrbitope,
        Self::FtGrowthTol,
        Self::DualAnatomy,
        Self::VerifyAfter,
        Self::NoFusedRt,
        Self::NoRtKind,
        Self::IterProfile,
        Self::NoRtBitsKey,
        Self::NoWideBloom,
        Self::NoEtaReuse,
        Self::NoDevex,
        Self::NoColdDual,
        Self::NoTriCrash,
        Self::ChainDevex,
        Self::NoCutoff,
        Self::NoNodeLu,
        Self::NoTallLu,
        Self::NoTallColdDual,
        Self::NoDualChurnBand,
        Self::DualBloomCap,
        Self::NoFlowcoverAgg,
        Self::NoGiExt,
        Self::NoBottleneckExt,
        Self::NoClique,
        Self::NoOddCycle,
        Self::NoCoverExt,
        Self::NoFlowcover,
        Self::NoSnap,
        Self::NoSplns,
        Self::NoMsWalk,
        Self::NoSweepProve,
        Self::NoRinsRescue,
        Self::NoSym,
        Self::SubmipBb,
        Self::ZeroHalf,
        Self::OddCycle,
        Self::FlipReach,
        Self::PropSweeps,
        Self::PropQueue,
        Self::SplnsExposed,
        Self::SplnsBudget,
        Self::SplnsStall,
        Self::MsWalkMoves,
        Self::GubMeasEvery,
        Self::DiagCostPerturb,
        Self::FcMode,
        Self::FlipSolve,
        Self::NoGubBranch,
        Self::NoDedupCols,
        Self::NoBinaryComplementSub,
        Self::NoLbAct,
        Self::NoGiDfs,
        Self::NoImplCut,
        Self::NoImplTab,
        Self::NoKnapRedirect,
        Self::NoDiveSkip,
        Self::NoCutFma,
        Self::NoOddLift,
        Self::NoStrongcg,
        Self::DenseGmiLu,
        Self::NoChainShape,
        Self::NoChainPreorder,
        Self::NoBumpLu,
        Self::DualBypassMode,
        Self::EagerPerturbMode,
        Self::HarrisRt,
        Self::NoMirKnap,
        Self::BbGate,
        Self::ChildOrderMode,
        Self::CutsPerRound,
        Self::CutEffFloor,
        Self::FtSpikeArm,
        Self::GubSb,
        Self::NgBox,
        Self::NgBranchPct,
        Self::NodeProp,
        Self::SbSustain,
        Self::SymBranchBand,
        Self::Rins,
        Self::DualfixAll,
        Self::ImpliedBound,
        Self::LiftedCover,
        Self::LnpBudget,
        Self::LatticeBkzBeta,
        Self::DualPerturb,
        Self::CertGraceSecs,
        Self::AnchorFirstRefusalMs,
        Self::RinsEvery,
        Self::RinsDrycap,
        Self::PumpShare,
        Self::SetpartShare,
        Self::NoParity,
        Self::NoMarginReframe,
        Self::SymMode,
        Self::HeurShare,
        Self::SbRel,
        Self::SbCands,
        Self::SbTotal,
        Self::NoPresolve,
        Self::NoPresolveScout,
        Self::Vsids,
        Self::RootProbeAll,
        Self::Sepstat,
        Self::LpStats,
        Self::StepTraceN,
        Self::BumpDiag,
        Self::BumpdiffLanes,
        Self::DiagPlainCold,
        Self::DumpVertex,
        Self::SmtLane,
        Self::MaxNodes,
        Self::StructElim,
        Self::NoBoundCover,
        Self::PumpIterMult,
        Self::NoPumpIterCap,
        Self::NgUp,
        Self::CutShadow,
        Self::ChainAgg,
        Self::AutoMargin,
        Self::ImplLane,
        Self::ImplArm,
        Self::DroughtDive,
        Self::PropConflict,
        Self::LbConflict,
        Self::LbArm,
        Self::LbStrict,
        Self::SingletonSub,
        Self::AffineAgg,
        Self::NodeCutSlots,
        Self::NodeCutEvery,
        Self::NodeCutEager,
        Self::AmoMultiway,
        Self::NodeGmi,
        Self::NodeGmiEvery,
        Self::NodeGmiMargin,
        Self::NodeRc,
        Self::NoRcCapGuard,
        Self::RootClosurePresolve,
        Self::TriCrashAll,
        Self::SymBranch,
        Self::StabOrbit,
        Self::Scale,
        Self::OrbitopeDyn,
        Self::NoTreeFloor,
        Self::NoTreeBoundOutcome,
        Self::NoRootFloor,
        Self::CoverMinimal,
        Self::GubClique,
        Self::GmiCutTrace,
        Self::CondTighten,
        Self::ModK,
        Self::KnapDbg,
        Self::MirAggRoot,
        Self::ColdDualAll,
        Self::CutWarm,
        Self::Rlt,
        Self::TableauMir,
        Self::DiveCommitStopped,
        Self::NoRootWarm,
        Self::OrbitopeBranch,
        Self::OrbitopeIlv,
        Self::OrbitopeBranchDyn,
        Self::NodeCutLocal,
        Self::NoCondScout,
        Self::NoFloat,
        Self::HybridPbLp,
        Self::Attrib,
        Self::Acensus,
        Self::CutTopk,
        Self::HybridTerm,
        Self::DiveProbeSecs,
        Self::SbProbeIters,
        Self::RensWindow,
        Self::RootProbeCap,
        Self::RootProbeCliqueCap,
        Self::RootProbeNoLpRank,
        Self::RootProbeShare,
        Self::NodeCutBatch,
        Self::NodeCutAge,
        Self::DualCutoff,
        Self::MsDive,
        Self::Mas74Plunge,
        Self::MsDiveSteps,
        Self::PropFirst,
        Self::GmiMaxRows,
        Self::ChainProbe,
        Self::BumpLuMin,
        Self::ColdLuEtaRebuilds,
        Self::AdoptFtMaxRows,
        Self::RefactorEvery,
        Self::EtaCapMult,
        Self::LuMaxFillNnz,
        Self::RelaxLift,
        Self::Devex,
        Self::BumpBtf,
    ];

    pub(super) const fn slot(self) -> usize {
        // `ALL` is declaration-ordered and its round-trip test pins that
        // invariant, so duplicating the same 225-entry index table is needless.
        self as usize
    }
}
