// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

//! Clause provenance tracking for UNSAT debugging (#8321).
//!
//! Tags every clause in the SAT solver with its origin. Opt-in via
//! `AY_CLAUSE_PROVENANCE=1` environment variable. When disabled (default),
//! all operations are no-ops with zero allocation overhead.

use std::collections::BTreeMap;

/// Classification of a clause's origin within the solver pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[non_exhaustive]
pub enum ClauseProvenance {
    /// Clause from the original problem encoding (user input).
    ProblemEncoding,
    /// Clause generated from a theory conflict (DPLL(T)).
    TheoryConflict,
    /// Clause generated from a theory propagation reason.
    TheoryPropagation,
    /// Bound axiom clause (e.g., from LIA/LRA bound encoding).
    BoundAxiom,
    /// Learned clause from CDCL conflict analysis.
    Learned,
    /// Clause generated by inprocessing (BVE, vivification, etc.).
    Inprocessing,
    /// Theory lemma added during solving.
    TheoryLemma,
    /// Clause from split encoding (Boolean abstraction of theory atoms).
    SplitEncoding,
}

impl std::fmt::Display for ClauseProvenance {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ProblemEncoding => write!(f, "Problem encoding"),
            Self::TheoryConflict => write!(f, "Theory conflict"),
            Self::TheoryPropagation => write!(f, "Theory propagation"),
            Self::BoundAxiom => write!(f, "Bound axiom"),
            Self::Learned => write!(f, "Learned"),
            Self::Inprocessing => write!(f, "Inprocessing"),
            Self::TheoryLemma => write!(f, "Theory lemma"),
            Self::SplitEncoding => write!(f, "Split encoding"),
        }
    }
}

/// Tracks the provenance of each clause by arena index.
///
/// Zero-overhead when disabled: `tag()` early-returns on `!self.enabled`
/// (branch predicted not-taken). The `tags` vector is empty when disabled,
/// so no memory is allocated.
#[derive(Clone)]
pub(crate) struct ProvenanceTracker {
    /// Whether provenance tracking is active (checked once at init from env var).
    enabled: bool,
    /// Provenance tag per clause arena index. Only populated when `enabled`.
    tags: Vec<Option<ClauseProvenance>>,
}

/// Check whether provenance tracking is enabled.
///
/// Delegates to ay-core's centralized SatDebugEnvFlags OnceLock cache (#8506).
fn is_provenance_enabled() -> bool {
    ay_core::sat_debug_env_flags().clause_provenance
}

impl ProvenanceTracker {
    /// Create a new tracker. Checks `AY_CLAUSE_PROVENANCE` env var once.
    pub(crate) fn new() -> Self {
        let enabled = is_provenance_enabled();
        Self {
            enabled,
            tags: Vec::new(),
        }
    }

    /// Whether provenance tracking is active.
    #[inline]
    pub(crate) fn is_enabled(&self) -> bool {
        self.enabled
    }

    /// Tag a clause at the given arena index with its provenance.
    ///
    /// No-op when tracking is disabled (one branch, predicted not-taken).
    #[inline]
    pub(crate) fn tag(&mut self, clause_idx: usize, provenance: ClauseProvenance) {
        if !self.enabled {
            return;
        }
        if clause_idx >= self.tags.len() {
            self.tags.resize(clause_idx + 1, None);
        }
        self.tags[clause_idx] = Some(provenance);
    }

    /// Get the provenance of a clause at the given arena index.
    #[inline]
    pub(crate) fn get(&self, clause_idx: usize) -> Option<ClauseProvenance> {
        if !self.enabled || clause_idx >= self.tags.len() {
            return None;
        }
        self.tags[clause_idx]
    }

    /// Return a count of clauses by provenance category.
    pub(crate) fn summary(&self) -> BTreeMap<ClauseProvenance, usize> {
        let mut counts = BTreeMap::new();
        if !self.enabled {
            return counts;
        }
        for prov in self.tags.iter().flatten() {
            *counts.entry(*prov).or_insert(0) += 1;
        }
        counts
    }

    /// Total number of tracked clauses.
    pub(crate) fn tracked_count(&self) -> usize {
        if !self.enabled {
            return 0;
        }
        self.tags.iter().filter(|t| t.is_some()).count()
    }

    /// Compute a provenance breakdown for a subset of clauses identified by
    /// arena index.
    ///
    /// Used to generate [`TrackedClauseProvenanceSummary`]: the caller provides
    /// arena indices from a diagnostic support set, and this method tallies the
    /// provenance of each.
    pub(crate) fn breakdown_for_indices(
        &self,
        indices: &[usize],
    ) -> BTreeMap<ClauseProvenance, usize> {
        let mut counts = BTreeMap::new();
        if !self.enabled {
            return counts;
        }
        for &idx in indices {
            if let Some(prov) = self.get(idx) {
                *counts.entry(prov).or_insert(0) += 1;
            }
        }
        counts
    }
}

/// Provenance summary for tracked original-clause support (#8322).
///
/// Produced by
/// [`crate::solver::Solver::tracked_clause_provenance_summary()`]. The tracked
/// set is diagnostic reconstruction metadata and may over-approximate a
/// terminal refutation; this summary does not certify an UNSAT core.
#[derive(Debug, Clone)]
pub struct TrackedClauseProvenanceSummary {
    /// Total clauses in the problem (with provenance tracking).
    pub total_clauses: usize,
    /// Number of tracked support clauses found in the arena.
    pub tracked_clauses: usize,
    /// Breakdown of tracked support clauses by provenance category.
    pub breakdown: BTreeMap<ClauseProvenance, usize>,
}

impl std::fmt::Display for TrackedClauseProvenanceSummary {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "Tracked Clause Provenance Summary:")?;
        writeln!(f, "  total clauses:  {}", self.total_clauses)?;
        writeln!(f, "  tracked clauses: {}", self.tracked_clauses)?;
        if !self.breakdown.is_empty() {
            writeln!(f, "  breakdown:")?;
            let mut entries: Vec<_> = self.breakdown.iter().collect();
            entries.sort_by(|a, b| {
                b.1.cmp(a.1)
                    .then_with(|| format!("{}", a.0).cmp(&format!("{}", b.0)))
            });
            for (prov, count) in entries {
                let pct = if self.tracked_clauses > 0 {
                    (*count as f64 / self.tracked_clauses as f64) * 100.0
                } else {
                    0.0
                };
                writeln!(f, "    {prov}: {count} ({pct:.1}%)")?;
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_clause_provenance_tracker_disabled() {
        // When not enabled, all operations are no-ops.
        let mut tracker = ProvenanceTracker {
            enabled: false,
            tags: Vec::new(),
        };
        tracker.tag(0, ClauseProvenance::ProblemEncoding);
        assert_eq!(tracker.get(0), None);
        assert_eq!(tracker.tracked_count(), 0);
        assert!(tracker.summary().is_empty());
    }

    #[test]
    fn test_clause_provenance_tracker_enabled() {
        let mut tracker = ProvenanceTracker {
            enabled: true,
            tags: Vec::new(),
        };
        tracker.tag(0, ClauseProvenance::ProblemEncoding);
        tracker.tag(1, ClauseProvenance::ProblemEncoding);
        tracker.tag(5, ClauseProvenance::Learned);
        tracker.tag(10, ClauseProvenance::TheoryLemma);
        tracker.tag(12, ClauseProvenance::Inprocessing);

        assert_eq!(tracker.get(0), Some(ClauseProvenance::ProblemEncoding));
        assert_eq!(tracker.get(5), Some(ClauseProvenance::Learned));
        assert_eq!(tracker.get(10), Some(ClauseProvenance::TheoryLemma));
        assert_eq!(tracker.get(3), None); // untagged slot
        assert_eq!(tracker.get(100), None); // out of range

        assert_eq!(tracker.tracked_count(), 5);

        let summary = tracker.summary();
        assert_eq!(summary[&ClauseProvenance::ProblemEncoding], 2);
        assert_eq!(summary[&ClauseProvenance::Learned], 1);
        assert_eq!(summary[&ClauseProvenance::TheoryLemma], 1);
        assert_eq!(summary[&ClauseProvenance::Inprocessing], 1);
    }

    #[test]
    fn test_clause_provenance_display() {
        assert_eq!(
            format!("{}", ClauseProvenance::ProblemEncoding),
            "Problem encoding"
        );
        assert_eq!(format!("{}", ClauseProvenance::Learned), "Learned");
        assert_eq!(
            format!("{}", ClauseProvenance::TheoryConflict),
            "Theory conflict"
        );
        assert_eq!(
            format!("{}", ClauseProvenance::TheoryPropagation),
            "Theory propagation"
        );
        assert_eq!(format!("{}", ClauseProvenance::BoundAxiom), "Bound axiom");
        assert_eq!(
            format!("{}", ClauseProvenance::Inprocessing),
            "Inprocessing"
        );
        assert_eq!(format!("{}", ClauseProvenance::TheoryLemma), "Theory lemma");
        assert_eq!(
            format!("{}", ClauseProvenance::SplitEncoding),
            "Split encoding"
        );
    }

    #[test]
    fn test_clause_provenance_overwrite() {
        let mut tracker = ProvenanceTracker {
            enabled: true,
            tags: Vec::new(),
        };
        tracker.tag(0, ClauseProvenance::ProblemEncoding);
        assert_eq!(tracker.get(0), Some(ClauseProvenance::ProblemEncoding));

        // Overwrite with a different provenance
        tracker.tag(0, ClauseProvenance::Learned);
        assert_eq!(tracker.get(0), Some(ClauseProvenance::Learned));
    }

    #[test]
    fn test_clause_provenance_sparse_tagging() {
        let mut tracker = ProvenanceTracker {
            enabled: true,
            tags: Vec::new(),
        };
        // Tag at a high index — should grow the vec without panic.
        tracker.tag(1000, ClauseProvenance::Inprocessing);
        assert_eq!(tracker.get(1000), Some(ClauseProvenance::Inprocessing));
        assert_eq!(tracker.tracked_count(), 1);
    }

    // -- TrackedClauseProvenanceSummary tests (#8322) --

    #[test]
    fn test_breakdown_for_indices_enabled() {
        let mut tracker = ProvenanceTracker {
            enabled: true,
            tags: Vec::new(),
        };
        tracker.tag(0, ClauseProvenance::ProblemEncoding);
        tracker.tag(1, ClauseProvenance::ProblemEncoding);
        tracker.tag(2, ClauseProvenance::TheoryConflict);
        tracker.tag(3, ClauseProvenance::Learned);
        tracker.tag(4, ClauseProvenance::ProblemEncoding);

        // Only indices 0, 2, 4 are in the tracked support set.
        let breakdown = tracker.breakdown_for_indices(&[0, 2, 4]);
        assert_eq!(breakdown[&ClauseProvenance::ProblemEncoding], 2);
        assert_eq!(breakdown[&ClauseProvenance::TheoryConflict], 1);
        assert!(!breakdown.contains_key(&ClauseProvenance::Learned));
    }

    #[test]
    fn test_breakdown_for_indices_disabled() {
        let tracker = ProvenanceTracker {
            enabled: false,
            tags: Vec::new(),
        };
        let breakdown = tracker.breakdown_for_indices(&[0, 1, 2]);
        assert!(breakdown.is_empty());
    }

    #[test]
    fn test_breakdown_for_indices_with_untagged() {
        let mut tracker = ProvenanceTracker {
            enabled: true,
            tags: Vec::new(),
        };
        tracker.tag(0, ClauseProvenance::ProblemEncoding);
        // Index 1 is never tagged.
        tracker.tag(2, ClauseProvenance::Learned);

        let breakdown = tracker.breakdown_for_indices(&[0, 1, 2]);
        assert_eq!(breakdown[&ClauseProvenance::ProblemEncoding], 1);
        assert_eq!(breakdown[&ClauseProvenance::Learned], 1);
        // Untagged index 1 is silently skipped.
        assert_eq!(breakdown.len(), 2);
    }

    #[test]
    fn test_tracked_clause_provenance_summary_display() {
        let mut breakdown = BTreeMap::new();
        breakdown.insert(ClauseProvenance::ProblemEncoding, 5);
        breakdown.insert(ClauseProvenance::TheoryConflict, 3);
        breakdown.insert(ClauseProvenance::Learned, 2);

        let summary = TrackedClauseProvenanceSummary {
            total_clauses: 100,
            tracked_clauses: 10,
            breakdown,
        };

        let output = format!("{summary}");
        assert!(output.contains("total clauses:  100"));
        assert!(output.contains("tracked clauses: 10"));
        assert!(output.contains("Problem encoding: 5 (50.0%)"));
        assert!(output.contains("Theory conflict: 3 (30.0%)"));
        assert!(output.contains("Learned: 2 (20.0%)"));
    }

    #[test]
    fn test_tracked_clause_provenance_summary_empty_breakdown() {
        let summary = TrackedClauseProvenanceSummary {
            total_clauses: 0,
            tracked_clauses: 0,
            breakdown: BTreeMap::new(),
        };

        let output = format!("{summary}");
        assert!(output.contains("total clauses:  0"));
        assert!(output.contains("tracked clauses: 0"));
        // No breakdown section when empty.
        assert!(!output.contains("breakdown:"));
    }
}
