// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

//! Checker for Lean-backed Hall+Sinz and guard-cover-packing SAT sidecars.
//!
//! The checker is intentionally syntactic and fail-closed: it accepts only the
//! stable theorem names generated by the SAT-COMP structural research lane, it
//! pins every sidecar to the exact DIMACS bytes with SHA-256, and it turns a
//! guard-cover packing witness into metadata only after all dependent
//! Hall+Sinz sidecars have been accepted for the same formula.

use crate::dimacs_core::{self, DimacsCoreError, DimacsEvent, DimacsRecordRef};
use serde_json::{Map, Value};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

/// Stable Lean theorem required by accepted Hall+Sinz escape sidecars.
pub const STABLE_HALL_SINZ_ESCAPE_THEOREM: &str =
    "SatCompStructural.checked_syntactic_sparse_selected_capacity_hall_sinz_deficit_one_clause_sound";

/// Stable Lean theorem required by accepted guard-cover-packing sidecars.
pub const STABLE_GUARD_COVER_PACKING_THEOREM: &str =
    "SatCompStructural.checked_remapped_sparse_hall_guard_cover_packing_unsat";

/// Stable Lean theorem required by accepted separator-cover sidecars.
pub const STABLE_SEPARATOR_COVER_THEOREM: &str =
    "SatCompStructural.checked_dimacs_separator_cover_unsat";

/// Accepted Hall+Sinz escape evidence.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HallSinzEscapeEvidence {
    /// Stable theorem name accepted for this sidecar.
    pub theorem: &'static str,
    /// Derived escape clause, in DIMACS literal order.
    pub escape_clause: Vec<i32>,
    /// Sum of selected resource capacities.
    pub capacity_sum: u64,
}

/// Accepted guard-cover-packing evidence.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GuardCoverPackingEvidence {
    /// Stable theorem name accepted for this sidecar.
    pub theorem: &'static str,
    /// Number of dependent Hall cuts packed.
    pub cuts: usize,
    /// Number of guard literals in the sidecar.
    pub guards: usize,
    /// Right-hand side of the accepted guard budget.
    pub budget_rhs: u64,
    /// Packed deficit that exceeds the budget.
    pub packed_deficit: u64,
}

/// Accepted separator-cover evidence.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SeparatorCoverEvidence {
    /// Stable theorem name accepted for this sidecar.
    pub theorem: &'static str,
    /// Number of separator variables covered by the sidecar.
    pub separator_vars: usize,
    /// Number of cubes in the complete separator cover.
    pub cubes: usize,
    /// Number of Boolean assignments covered by the cube set.
    pub covered_assignments: u64,
}

/// Rejection from the guard-cover sidecar checker.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("{0}")]
pub struct GuardCoverSidecarError(String);

impl GuardCoverSidecarError {
    /// Human-readable rejection detail.
    pub fn detail(&self) -> &str {
        &self.0
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Cnf {
    num_vars: usize,
    clauses: Vec<Vec<i32>>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Guard {
    lit: i32,
    beta: u64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Cut {
    deficit: u64,
    scale: u64,
    coeff: BTreeMap<String, u64>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct SeparatorCube {
    id: String,
    lits: Vec<i32>,
}

fn reject<T>(detail: impl Into<String>) -> Result<T, GuardCoverSidecarError> {
    Err(GuardCoverSidecarError(detail.into()))
}

const MAX_CLAUSE_PREALLOC: usize = 1 << 20;

fn initial_clause_capacity(declared_clauses: usize, input_len: usize) -> usize {
    // Header counts are untrusted. There cannot be more nonempty clause
    // records than input bytes, and real inputs may still grow the vector as
    // records arrive. The fixed ceiling also avoids a large speculative
    // allocation for comment-heavy or otherwise padded files.
    declared_clauses.min(input_len).min(MAX_CLAUSE_PREALLOC)
}

fn parse_cnf(cnf_bytes: &[u8]) -> Result<Cnf, GuardCoverSidecarError> {
    let mut clauses = Vec::new();
    let header = dimacs_core::parse_dimacs_events(cnf_bytes, |event| {
        match event {
            DimacsEvent::Header(parsed) => {
                clauses.reserve(initial_clause_capacity(parsed.num_clauses, cnf_bytes.len()));
            }
            DimacsEvent::Record(DimacsRecordRef::Clause(raw)) => {
                clauses.push(raw.to_vec());
            }
            DimacsEvent::Record(DimacsRecordRef::Tagged { tag, .. }) => {
                return Err(DimacsCoreError::InvalidLiteral {
                    token: format!("unexpected tagged line '{tag}' in CNF input"),
                    line_number: 0,
                });
            }
        }
        Ok(())
    })
    .map_err(|error| GuardCoverSidecarError(format!("DIMACS parse error: {error}")))?;

    if clauses.len() != header.num_clauses {
        return reject(format!(
            "DIMACS header clause count {} != parsed {}",
            header.num_clauses,
            clauses.len()
        ));
    }

    Ok(Cnf {
        num_vars: header.num_vars,
        clauses,
    })
}

fn clause_set(cnf: &Cnf) -> BTreeSet<Vec<i32>> {
    cnf.clauses.iter().cloned().collect()
}

fn sha256_hex(bytes: &[u8]) -> String {
    let digest = Sha256::digest(bytes);
    let mut out = String::with_capacity(64);
    for byte in digest {
        let _ = write!(&mut out, "{byte:02x}");
    }
    out
}

fn json_object<'a>(
    value: &'a Value,
    field: &str,
) -> Result<&'a Map<String, Value>, GuardCoverSidecarError> {
    value
        .as_object()
        .ok_or_else(|| GuardCoverSidecarError(format!("{field} must be an object")))
}

fn json_list<'a>(value: &'a Value, field: &str) -> Result<&'a [Value], GuardCoverSidecarError> {
    value
        .as_array()
        .map(Vec::as_slice)
        .ok_or_else(|| GuardCoverSidecarError(format!("{field} must be a list")))
}

fn field<'a>(
    object: &'a Map<String, Value>,
    key: &str,
    parent: &str,
) -> Result<&'a Value, GuardCoverSidecarError> {
    object
        .get(key)
        .ok_or_else(|| GuardCoverSidecarError(format!("{parent}.{key} is missing")))
}

fn string_value<'a>(value: &'a Value, field: &str) -> Result<&'a str, GuardCoverSidecarError> {
    match value.as_str() {
        Some(value) if !value.is_empty() => Ok(value),
        _ => reject(format!("{field} must be a non-empty string")),
    }
}

fn string_list(value: &Value, field_name: &str) -> Result<Vec<String>, GuardCoverSidecarError> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for (index, item) in json_list(value, field_name)?.iter().enumerate() {
        let item = string_value(item, &format!("{field_name}[{index}]"))?;
        if !seen.insert(item.to_string()) {
            return reject(format!("{field_name} contains duplicate id {item}"));
        }
        out.push(item.to_string());
    }
    Ok(out)
}

fn nat(value: &Value, field_name: &str) -> Result<u64, GuardCoverSidecarError> {
    value.as_u64().ok_or_else(|| {
        GuardCoverSidecarError(format!("{field_name} must be a non-negative integer"))
    })
}

fn positive(value: &Value, field_name: &str) -> Result<u64, GuardCoverSidecarError> {
    let value = nat(value, field_name)?;
    if value == 0 {
        reject(format!("{field_name} must be a positive integer"))
    } else {
        Ok(value)
    }
}

fn dimacs_lit(
    value: &Value,
    field_name: &str,
    num_vars: usize,
) -> Result<i32, GuardCoverSidecarError> {
    let Some(raw) = value.as_i64() else {
        return reject(format!("{field_name} must be a nonzero DIMACS integer"));
    };
    if raw == 0 {
        return reject(format!("{field_name} must be a nonzero DIMACS integer"));
    }
    if raw == i64::from(i32::MIN) {
        return reject(format!(
            "{field_name} is outside the supported negatable DIMACS literal range"
        ));
    }
    if raw < i64::from(i32::MIN) || raw > i64::from(i32::MAX) {
        return reject(format!(
            "{field_name} is outside the i32 DIMACS literal range"
        ));
    }
    let abs = raw.unsigned_abs() as usize;
    if abs > num_vars {
        return reject(format!(
            "{field_name} references variable {abs} > num_vars {num_vars}"
        ));
    }
    Ok(raw as i32)
}

fn lit_list(
    value: &Value,
    field_name: &str,
    num_vars: usize,
) -> Result<Vec<i32>, GuardCoverSidecarError> {
    json_list(value, field_name)?
        .iter()
        .enumerate()
        .map(|(index, item)| dimacs_lit(item, &format!("{field_name}[{index}]"), num_vars))
        .collect()
}

fn object_keys(object: &Map<String, Value>) -> BTreeSet<String> {
    object.keys().cloned().collect()
}

fn slice_to_set(items: &[String]) -> BTreeSet<String> {
    items.iter().cloned().collect()
}

fn check_clause_shape(clause: &[i32], label: &str) -> Result<(), GuardCoverSidecarError> {
    let mut seen = BTreeSet::new();
    for &lit in clause {
        if !seen.insert(lit) {
            return reject(format!("{label} contains duplicate literal {lit}"));
        }
        if seen.contains(&-lit) {
            return reject(format!("{label} is tautological"));
        }
    }
    Ok(())
}

fn require_clause(
    clause_set: &BTreeSet<Vec<i32>>,
    clause: &[i32],
    label: &str,
) -> Result<(), GuardCoverSidecarError> {
    check_clause_shape(clause, label)?;
    if clause_set.contains(&clause.to_vec()) {
        Ok(())
    } else {
        reject(format!("missing {label}: {clause:?}"))
    }
}

fn read_separator_vars(
    value: &Value,
    num_vars: usize,
) -> Result<Vec<usize>, GuardCoverSidecarError> {
    let mut seen = BTreeSet::new();
    let mut vars = Vec::new();
    for (index, item) in json_list(value, "separator_vars")?.iter().enumerate() {
        let raw = positive(item, &format!("separator_vars[{index}]"))?;
        if raw > num_vars as u64 {
            return reject(format!(
                "separator_vars[{index}] references variable {raw} > num_vars {num_vars}"
            ));
        }
        let var = raw as usize;
        if !seen.insert(var) {
            return reject(format!("separator_vars contains duplicate variable {var}"));
        }
        vars.push(var);
    }
    if vars.is_empty() {
        return reject("separator_vars must not be empty");
    }
    if vars.len() >= u64::BITS as usize {
        return reject("separator cover is too large to enumerate in this checker");
    }
    Ok(vars)
}

fn check_cube_refuted_by_clause(
    cube_lits: &[i32],
    refuted_by: &[i32],
    clauses: &BTreeSet<Vec<i32>>,
) -> Result<(), GuardCoverSidecarError> {
    if refuted_by.is_empty() {
        return reject("separator cube refuted_by clause must not be empty");
    }
    require_clause(clauses, refuted_by, "separator cube refuted_by clause")?;
    let cube_lit_set = cube_lits.iter().copied().collect::<BTreeSet<_>>();
    for &lit in refuted_by {
        if !cube_lit_set.contains(&-lit) {
            return reject(format!(
                "separator cube does not falsify refuted_by literal {lit}"
            ));
        }
    }
    Ok(())
}

fn read_separator_cubes(
    value: &Value,
    clauses: &BTreeSet<Vec<i32>>,
    num_vars: usize,
) -> Result<Vec<SeparatorCube>, GuardCoverSidecarError> {
    let mut seen_ids = BTreeSet::new();
    let mut cubes = Vec::new();
    for (index, raw_cube) in json_list(value, "cubes")?.iter().enumerate() {
        let cube = json_object(raw_cube, &format!("cubes[{index}]"))?;
        let id = string_value(
            field(cube, "id", &format!("cubes[{index}]"))?,
            &format!("cubes[{index}].id"),
        )?;
        if !seen_ids.insert(id.to_string()) {
            return reject(format!("duplicate separator cube id {id}"));
        }
        let lits = lit_list(
            field(cube, "lits", &format!("cubes[{index}]"))?,
            &format!("cubes[{index}].lits"),
            num_vars,
        )?;
        if lits.is_empty() {
            return reject(format!("cubes[{index}].lits must not be empty"));
        }
        check_clause_shape(&lits, &format!("cubes[{index}].lits"))?;
        let refuted_by = lit_list(
            field(cube, "refuted_by", &format!("cubes[{index}]"))?,
            &format!("cubes[{index}].refuted_by"),
            num_vars,
        )?;
        check_cube_refuted_by_clause(&lits, &refuted_by, clauses)?;
        cubes.push(SeparatorCube {
            id: id.to_string(),
            lits,
        });
    }
    if cubes.is_empty() {
        return reject("cubes must not be empty");
    }
    Ok(cubes)
}

fn check_separator_cover_complete(
    separator_vars: &[usize],
    cubes: &[SeparatorCube],
) -> Result<u64, GuardCoverSidecarError> {
    let var_index: BTreeMap<usize, usize> = separator_vars
        .iter()
        .copied()
        .enumerate()
        .map(|(index, var)| (var, index))
        .collect();
    let expected_lits = separator_vars.len();
    let full_count = 1u64 << expected_lits;
    let mut masks = BTreeSet::new();

    for cube in cubes {
        if cube.lits.len() != expected_lits {
            return reject(format!(
                "separator cube {} assigns {} vars, expected {expected_lits}",
                cube.id,
                cube.lits.len()
            ));
        }
        let mut assigned = BTreeSet::new();
        let mut mask = 0u64;
        for &lit in &cube.lits {
            let var = lit.unsigned_abs() as usize;
            let Some(&index) = var_index.get(&var) else {
                return reject(format!(
                    "separator cube {} uses non-separator variable {var}",
                    cube.id
                ));
            };
            if !assigned.insert(var) {
                return reject(format!(
                    "separator cube {} assigns variable {var} more than once",
                    cube.id
                ));
            }
            if lit > 0 {
                mask |= 1u64 << index;
            }
        }
        if !masks.insert(mask) {
            return reject(format!(
                "duplicate separator assignment mask {mask} in cube {}",
                cube.id
            ));
        }
    }

    if masks.len() as u64 != full_count {
        return reject(format!(
            "incomplete separator cover: covered {} assignments, expected {full_count}",
            masks.len()
        ));
    }
    Ok(full_count)
}

fn parse_json_object(text: &str, label: &str) -> Result<Value, GuardCoverSidecarError> {
    let value: Value = serde_json::from_str(text)
        .map_err(|error| GuardCoverSidecarError(format!("{label} is invalid JSON: {error}")))?;
    if value.is_object() {
        Ok(value)
    } else {
        reject(format!("{label} root must be an object"))
    }
}

fn check_hash(
    cnf_bytes: &[u8],
    payload: &Map<String, Value>,
    field_name: &str,
    required: bool,
) -> Result<(), GuardCoverSidecarError> {
    let Some(value) = payload.get(field_name) else {
        if required {
            return reject(format!("{field_name} must be a string"));
        }
        return Ok(());
    };
    let claimed = string_value(value, field_name)?;
    let claimed = claimed.strip_prefix("sha256:").unwrap_or(claimed);
    let actual = sha256_hex(cnf_bytes);
    if claimed == actual {
        Ok(())
    } else {
        reject(format!("{field_name} mismatch"))
    }
}

fn check_hall_dependency_hash(
    cnf_bytes: &[u8],
    sidecar_text: &str,
    witness: &str,
) -> Result<(), GuardCoverSidecarError> {
    let value = parse_json_object(sidecar_text, &format!("Hall sidecar witness={witness}"))?;
    let payload = json_object(&value, &format!("Hall sidecar witness={witness}"))?;
    check_hash(cnf_bytes, payload, "formula_sha256", true).map_err(|error| {
        GuardCoverSidecarError(format!("Hall sidecar witness={witness} {}", error.detail()))
    })
}

/// Check a Hall+Sinz escape sidecar against exact DIMACS bytes.
pub fn check_hall_sinz_escape_sidecar(
    cnf_bytes: &[u8],
    sidecar_text: &str,
) -> Result<HallSinzEscapeEvidence, GuardCoverSidecarError> {
    let cnf = parse_cnf(cnf_bytes)?;
    let clauses = clause_set(&cnf);
    let value = parse_json_object(sidecar_text, "Hall sidecar")?;
    let payload = json_object(&value, "Hall sidecar")?;

    if nat(field(payload, "version", "Hall sidecar")?, "version")? != 1 {
        return reject("version must be 1");
    }
    let lane = string_value(field(payload, "lane", "Hall sidecar")?, "lane")?;
    if lane != "hall-sinz-escape" && lane != "hall-core" {
        return reject("lane must be hall-sinz-escape or hall-core");
    }

    let theorems = json_list(field(payload, "theorems", "Hall sidecar")?, "theorems")?;
    let has_stable_theorem = theorems.iter().any(|item| {
        item.as_str()
            .is_some_and(|theorem| theorem == STABLE_HALL_SINZ_ESCAPE_THEOREM)
    });
    if !has_stable_theorem {
        return reject(format!("missing theorem {STABLE_HALL_SINZ_ESCAPE_THEOREM}"));
    }

    if payload.contains_key("formula_sha256") {
        check_hash(cnf_bytes, payload, "formula_sha256", false)?;
    } else {
        check_hash(cnf_bytes, payload, "formula_hash", false)?;
    }

    let witness = json_object(field(payload, "witness", "Hall sidecar")?, "witness")?;
    let objects = string_list(field(witness, "objects", "witness")?, "witness.objects")?;
    let resources = string_list(field(witness, "resources", "witness")?, "witness.resources")?;
    let object_set = slice_to_set(&objects);
    let resource_set = slice_to_set(&resources);

    let capacity_raw = json_object(field(witness, "capacity", "witness")?, "witness.capacity")?;
    if object_keys(capacity_raw) != resource_set {
        return reject("witness.capacity keys must match witness.resources");
    }
    let mut capacity = BTreeMap::new();
    for resource in &resources {
        let cap = nat(
            field(capacity_raw, resource, "witness.capacity")?,
            &format!("witness.capacity[{resource}]"),
        )?;
        if cap < 1 {
            return reject(format!(
                "witness.capacity[{resource}] must be >= 1 for Sinz rows"
            ));
        }
        capacity.insert(resource.clone(), cap);
    }

    let allowed_raw = json_object(field(witness, "allowed", "witness")?, "witness.allowed")?;
    let edge_raw = json_object(field(witness, "edge_lits", "witness")?, "witness.edge_lits")?;
    let forbid_raw = json_object(
        field(witness, "forbid_lits", "witness")?,
        "witness.forbid_lits",
    )?;
    if object_keys(allowed_raw) != object_set
        || object_keys(edge_raw) != object_set
        || object_keys(forbid_raw) != object_set
    {
        return reject("object-keyed witness maps must match witness.objects");
    }

    let mut allowed: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    let mut edge_lits: BTreeMap<(String, String), i32> = BTreeMap::new();
    let mut forbid_lits: BTreeMap<String, Vec<i32>> = BTreeMap::new();

    for object in &objects {
        let object_allowed = string_list(
            field(allowed_raw, object, "witness.allowed")?,
            &format!("witness.allowed[{object}]"),
        )?;
        let allowed_set = slice_to_set(&object_allowed);
        if !allowed_set.is_subset(&resource_set) {
            return reject(format!(
                "witness.allowed[{object}] references unknown resources"
            ));
        }
        allowed.insert(object.clone(), allowed_set.clone());

        let edge_row = json_object(
            field(edge_raw, object, "witness.edge_lits")?,
            &format!("witness.edge_lits[{object}]"),
        )?;
        for resource in &allowed_set {
            let lit = dimacs_lit(
                field(edge_row, resource, &format!("witness.edge_lits[{object}]"))?,
                &format!("witness.edge_lits[{object}][{resource}]"),
                cnf.num_vars,
            )?;
            edge_lits.insert((object.clone(), resource.clone()), lit);
        }

        forbid_lits.insert(
            object.clone(),
            lit_list(
                field(forbid_raw, object, "witness.forbid_lits")?,
                &format!("witness.forbid_lits[{object}]"),
                cnf.num_vars,
            )?,
        );
    }

    for object in &objects {
        let mut demand = Vec::new();
        for resource in &resources {
            if allowed
                .get(object)
                .is_some_and(|allowed_set| allowed_set.contains(resource))
            {
                let lit = edge_lits
                    .get(&(object.clone(), resource.clone()))
                    .copied()
                    .ok_or_else(|| {
                        GuardCoverSidecarError(format!(
                            "missing witness.edge_lits[{object}][{resource}]"
                        ))
                    })?;
                demand.push(lit);
            }
        }
        demand.extend(forbid_lits.get(object).into_iter().flatten().copied());
        require_clause(&clauses, &demand, &format!("demand clause object={object}"))?;
    }

    let capacity_sum = capacity.values().sum::<u64>();
    if capacity_sum + 1 > objects.len() as u64 {
        return reject(format!(
            "deficit condition failed: sum(capacity)+1={} > objects={}",
            capacity_sum + 1,
            objects.len()
        ));
    }

    let sinz_raw = json_object(field(witness, "sinz_rows", "witness")?, "witness.sinz_rows")?;
    if object_keys(sinz_raw) != resource_set {
        return reject("witness.sinz_rows keys must match witness.resources");
    }

    for resource in &resources {
        let row = json_object(
            field(sinz_raw, resource, "witness.sinz_rows")?,
            &format!("witness.sinz_rows[{resource}]"),
        )?;
        let width = nat(
            field(row, "width", &format!("witness.sinz_rows[{resource}]"))?,
            &format!("witness.sinz_rows[{resource}].width"),
        )? as usize;
        let cap = *capacity
            .get(resource)
            .expect("capacity map was populated from resources") as usize;
        if cap > width {
            return reject(format!(
                "capacity width condition failed resource={resource}: capacity={cap} width={width}"
            ));
        }
        let mut prev = lit_list(
            field(row, "zero", &format!("witness.sinz_rows[{resource}]"))?,
            &format!("witness.sinz_rows[{resource}].zero"),
            cnf.num_vars,
        )?;
        if prev.len() != width {
            return reject(format!(
                "witness.sinz_rows[{resource}].zero length {} != width {width}",
                prev.len()
            ));
        }

        let expected_inputs: Vec<i32> = objects
            .iter()
            .filter(|object| {
                allowed
                    .get(*object)
                    .is_some_and(|allowed_set| allowed_set.contains(resource))
            })
            .map(|object| {
                edge_lits
                    .get(&(object.clone(), resource.clone()))
                    .copied()
                    .expect("edge literal was loaded for allowed resource")
            })
            .collect();
        let steps = json_list(
            field(row, "steps", &format!("witness.sinz_rows[{resource}]"))?,
            &format!("witness.sinz_rows[{resource}].steps"),
        )?;
        if steps.len() != expected_inputs.len() {
            return reject(format!(
                "sinz step count mismatch resource={resource}: got {}, expected {}",
                steps.len(),
                expected_inputs.len()
            ));
        }

        for (index, (step_raw, expected_input)) in
            steps.iter().zip(expected_inputs.iter()).enumerate()
        {
            let step = json_object(
                step_raw,
                &format!("witness.sinz_rows[{resource}].steps[{index}]"),
            )?;
            let step_input = dimacs_lit(
                field(
                    step,
                    "input",
                    &format!("witness.sinz_rows[{resource}].steps[{index}]"),
                )?,
                &format!("witness.sinz_rows[{resource}].steps[{index}].input"),
                cnf.num_vars,
            )?;
            if step_input != *expected_input {
                return reject(format!(
                    "sinz input mismatch resource={resource} step={index}: got {step_input}, expected {expected_input}"
                ));
            }
            let curr = lit_list(
                field(
                    step,
                    "row",
                    &format!("witness.sinz_rows[{resource}].steps[{index}]"),
                )?,
                &format!("witness.sinz_rows[{resource}].steps[{index}].row"),
                cnf.num_vars,
            )?;
            if curr.len() != width {
                return reject(format!(
                    "sinz row length mismatch resource={resource} step={index}: got {}, expected {width}",
                    curr.len()
                ));
            }

            require_clause(
                &clauses,
                &[-step_input, curr[0]],
                &format!("sinz inputCol0 clause resource={resource} step={index}"),
            )?;
            for col in 0..width {
                require_clause(
                    &clauses,
                    &[-prev[col], curr[col]],
                    &format!("sinz carry clause resource={resource} step={index} col={col}"),
                )?;
            }
            for col in 0..width.saturating_sub(1) {
                require_clause(
                    &clauses,
                    &[-step_input, -prev[col], curr[col + 1]],
                    &format!("sinz bump clause resource={resource} step={index} col={col}"),
                )?;
            }
            require_clause(
                &clauses,
                &[-step_input, -prev[cap - 1]],
                &format!("sinz overflow clause resource={resource} step={index}"),
            )?;
            prev = curr;
        }
    }

    let escape_clause: Vec<i32> = objects
        .iter()
        .flat_map(|object| forbid_lits.get(object).into_iter().flatten().copied())
        .collect();
    check_clause_shape(&escape_clause, "derived escape clause")?;
    if escape_clause.is_empty() {
        return reject("derived escape clause is empty");
    }

    Ok(HallSinzEscapeEvidence {
        theorem: STABLE_HALL_SINZ_ESCAPE_THEOREM,
        escape_clause,
        capacity_sum,
    })
}

fn read_guards(
    raw_guards: &Value,
    num_vars: usize,
) -> Result<BTreeMap<String, Guard>, GuardCoverSidecarError> {
    let mut guards = BTreeMap::new();
    let mut lit_owner = BTreeMap::new();
    for (index, raw_guard) in json_list(raw_guards, "guards")?.iter().enumerate() {
        let guard = json_object(raw_guard, &format!("guards[{index}]"))?;
        let guard_id = string_value(
            field(guard, "id", &format!("guards[{index}]"))?,
            &format!("guards[{index}].id"),
        )?;
        if guards.contains_key(guard_id) {
            return reject(format!("duplicate guard id {guard_id}"));
        }
        let lit = dimacs_lit(
            field(guard, "lit", &format!("guards[{index}]"))?,
            &format!("guards[{index}].lit"),
            num_vars,
        )?;
        if lit_owner.contains_key(&lit) {
            return reject(format!(
                "guard literal {lit} is assigned to multiple guards"
            ));
        }
        let beta = positive(
            field(guard, "beta", &format!("guards[{index}]"))?,
            &format!("guards[{index}].beta"),
        )?;
        guards.insert(guard_id.to_string(), Guard { lit, beta });
        lit_owner.insert(lit, guard_id.to_string());
    }
    if guards.is_empty() {
        return reject("guards must not be empty");
    }
    Ok(guards)
}

fn read_budget_terms(
    budget: &Map<String, Value>,
    guards: &BTreeMap<String, Guard>,
    num_vars: usize,
) -> Result<Vec<(String, i32, u64)>, GuardCoverSidecarError> {
    let mut terms = Vec::new();
    let mut seen = BTreeSet::new();
    for (index, raw_term) in json_list(field(budget, "terms", "budget")?, "budget.terms")?
        .iter()
        .enumerate()
    {
        let term = json_object(raw_term, &format!("budget.terms[{index}]"))?;
        let guard_id = string_value(
            field(term, "guard", &format!("budget.terms[{index}]"))?,
            &format!("budget.terms[{index}].guard"),
        )?;
        let Some(guard) = guards.get(guard_id) else {
            return reject(format!(
                "budget.terms[{index}].guard references unknown guard {guard_id}"
            ));
        };
        if !seen.insert(guard_id.to_string()) {
            return reject(format!("duplicate budget term for guard {guard_id}"));
        }
        let lit = dimacs_lit(
            field(term, "lit", &format!("budget.terms[{index}]"))?,
            &format!("budget.terms[{index}].lit"),
            num_vars,
        )?;
        let weight = positive(
            field(term, "weight", &format!("budget.terms[{index}]"))?,
            &format!("budget.terms[{index}].weight"),
        )?;
        if lit != guard.lit {
            return reject(format!(
                "budget term literal mismatch guard={guard_id}: got {lit}, expected {}",
                guard.lit
            ));
        }
        if weight != guard.beta {
            return reject(format!(
                "budget term weight mismatch guard={guard_id}: got {weight}, expected {}",
                guard.beta
            ));
        }
        terms.push((guard_id.to_string(), lit, weight));
    }
    if seen != guards.keys().cloned().collect::<BTreeSet<_>>() {
        return reject("budget.terms guard ids must match guards");
    }
    Ok(terms)
}

fn check_budget_evidence(
    budget: &Map<String, Value>,
    budget_terms: &[(String, i32, u64)],
    clauses: &BTreeSet<Vec<i32>>,
    num_vars: usize,
) -> Result<(), GuardCoverSidecarError> {
    let rhs = nat(field(budget, "rhs", "budget")?, "budget.rhs")?;
    let evidence = json_object(field(budget, "evidence", "budget")?, "budget.evidence")?;
    let kind = string_value(
        field(evidence, "kind", "budget.evidence")?,
        "budget.evidence.kind",
    )?;
    let evidence_rhs = nat(
        field(evidence, "rhs", "budget.evidence")?,
        "budget.evidence.rhs",
    )?;
    if evidence_rhs != rhs {
        return reject(format!(
            "budget evidence rhs mismatch: got {evidence_rhs}, expected {rhs}"
        ));
    }

    if kind == "negative-units" {
        if rhs != 0 {
            return reject("negative-units budget evidence requires budget.rhs = 0");
        }
        for (index, (_, lit, _)) in budget_terms.iter().enumerate() {
            require_clause(
                clauses,
                &[-*lit],
                &format!("budget negative-unit clause term={index}"),
            )?;
        }
        return Ok(());
    }

    if kind != "sinz_bounded_forward_v1" {
        return reject(format!("unsupported budget evidence kind {kind}"));
    }
    if rhs < 1 {
        return reject("sinz_bounded_forward_v1 budget evidence requires budget.rhs >= 1");
    }
    for (index, (_, _, weight)) in budget_terms.iter().enumerate() {
        if *weight != 1 {
            return reject(format!(
                "sinz budget evidence only supports unit weights: budget.terms[{index}].weight={weight}"
            ));
        }
    }

    let width = nat(
        field(evidence, "width", "budget.evidence")?,
        "budget.evidence.width",
    )? as usize;
    if rhs as usize > width {
        return reject(format!(
            "budget evidence width condition failed: rhs={rhs} width={width}"
        ));
    }
    let mut prev = lit_list(
        field(evidence, "zero", "budget.evidence")?,
        "budget.evidence.zero",
        num_vars,
    )?;
    if prev.len() != width {
        return reject(format!(
            "budget.evidence.zero length {} != width {width}",
            prev.len()
        ));
    }

    let steps = json_list(
        field(evidence, "steps", "budget.evidence")?,
        "budget.evidence.steps",
    )?;
    if steps.len() != budget_terms.len() {
        return reject(format!(
            "budget sinz step count mismatch: got {}, expected {}",
            steps.len(),
            budget_terms.len()
        ));
    }
    for (index, (raw_step, (_, expected_input, _))) in
        steps.iter().zip(budget_terms.iter()).enumerate()
    {
        let step = json_object(raw_step, &format!("budget.evidence.steps[{index}]"))?;
        let step_input = dimacs_lit(
            field(step, "input", &format!("budget.evidence.steps[{index}]"))?,
            &format!("budget.evidence.steps[{index}].input"),
            num_vars,
        )?;
        if step_input != *expected_input {
            return reject(format!(
                "budget sinz input mismatch step={index}: got {step_input}, expected {expected_input}"
            ));
        }

        let curr = lit_list(
            field(step, "row", &format!("budget.evidence.steps[{index}]"))?,
            &format!("budget.evidence.steps[{index}].row"),
            num_vars,
        )?;
        if curr.len() != width {
            return reject(format!(
                "budget sinz row length mismatch step={index}: got {}, expected {width}",
                curr.len()
            ));
        }
        require_clause(
            clauses,
            &[-step_input, curr[0]],
            &format!("budget sinz inputCol0 clause step={index}"),
        )?;
        for col in 0..width {
            require_clause(
                clauses,
                &[-prev[col], curr[col]],
                &format!("budget sinz carry clause step={index} col={col}"),
            )?;
        }
        for col in 0..width.saturating_sub(1) {
            require_clause(
                clauses,
                &[-step_input, -prev[col], curr[col + 1]],
                &format!("budget sinz bump clause step={index} col={col}"),
            )?;
        }
        require_clause(
            clauses,
            &[-step_input, -prev[rhs as usize - 1]],
            &format!("budget sinz overflow clause step={index}"),
        )?;
        prev = curr;
    }
    Ok(())
}

fn check_dependencies<R>(
    cnf_bytes: &[u8],
    depends_on_raw: &Value,
    mut resolver: R,
) -> Result<BTreeMap<String, Vec<i32>>, GuardCoverSidecarError>
where
    R: FnMut(&str) -> Result<String, String>,
{
    let mut hall_escape_by_cut = BTreeMap::new();
    for (index, raw_dep) in json_list(depends_on_raw, "depends_on")?.iter().enumerate() {
        let dep = json_object(raw_dep, &format!("depends_on[{index}]"))?;
        let cut_id = string_value(
            field(dep, "cut_id", &format!("depends_on[{index}]"))?,
            &format!("depends_on[{index}].cut_id"),
        )?;
        if hall_escape_by_cut.contains_key(cut_id) {
            return reject(format!("duplicate depends_on cut_id {cut_id}"));
        }
        let witness = string_value(
            field(dep, "witness", &format!("depends_on[{index}]"))?,
            &format!("depends_on[{index}].witness"),
        )?;
        let accepted_theorem = string_value(
            field(dep, "accepted_theorem", &format!("depends_on[{index}]"))?,
            &format!("depends_on[{index}].accepted_theorem"),
        )?;
        if accepted_theorem != STABLE_HALL_SINZ_ESCAPE_THEOREM {
            return reject(format!(
                "depends_on[{index}].accepted_theorem must be {STABLE_HALL_SINZ_ESCAPE_THEOREM}"
            ));
        }

        let hall_text = resolver(witness).map_err(|error| {
            GuardCoverSidecarError(format!(
                "failed to load Hall sidecar witness={witness}: {error}"
            ))
        })?;
        check_hall_dependency_hash(cnf_bytes, &hall_text, witness)?;
        let hall_result =
            check_hall_sinz_escape_sidecar(cnf_bytes, &hall_text).map_err(|error| {
                GuardCoverSidecarError(format!(
                    "Hall sidecar rejected cut_id={cut_id} witness={witness}: {}",
                    error.detail()
                ))
            })?;
        if hall_result.theorem != accepted_theorem {
            return reject(format!(
                "Hall theorem mismatch cut_id={cut_id}: got {}, expected {accepted_theorem}",
                hall_result.theorem
            ));
        }
        hall_escape_by_cut.insert(cut_id.to_string(), hall_result.escape_clause);
    }
    if hall_escape_by_cut.is_empty() {
        return reject("depends_on must not be empty");
    }
    Ok(hall_escape_by_cut)
}

fn read_cuts(
    cuts_raw: &Value,
    hall_escape_by_cut: &BTreeMap<String, Vec<i32>>,
    guards: &BTreeMap<String, Guard>,
    num_vars: usize,
) -> Result<BTreeMap<String, Cut>, GuardCoverSidecarError> {
    let lit_to_guard: BTreeMap<i32, String> = guards
        .iter()
        .map(|(guard_id, guard)| (guard.lit, guard_id.clone()))
        .collect();
    let mut cuts = BTreeMap::new();
    for (index, raw_cut) in json_list(cuts_raw, "cuts")?.iter().enumerate() {
        let cut = json_object(raw_cut, &format!("cuts[{index}]"))?;
        let cut_id = string_value(
            field(cut, "id", &format!("cuts[{index}]"))?,
            &format!("cuts[{index}].id"),
        )?;
        if cuts.contains_key(cut_id) {
            return reject(format!("duplicate cut id {cut_id}"));
        }
        let Some(expected_escape) = hall_escape_by_cut.get(cut_id) else {
            return reject(format!("cuts[{index}].id has no matching depends_on entry"));
        };
        let source = string_value(
            field(cut, "source", &format!("cuts[{index}]"))?,
            &format!("cuts[{index}].source"),
        )?;
        if source != "hall-sinz-sidecar" {
            return reject(format!("cuts[{index}].source must be hall-sinz-sidecar"));
        }
        let deficit = positive(
            field(cut, "deficit", &format!("cuts[{index}]"))?,
            &format!("cuts[{index}].deficit"),
        )?;
        if deficit != 1 {
            return reject(format!(
                "cuts[{index}].deficit must be 1 for Hall escape clauses"
            ));
        }
        let scale = positive(
            field(cut, "scale", &format!("cuts[{index}]"))?,
            &format!("cuts[{index}].scale"),
        )?;
        let escape_clause = lit_list(
            field(cut, "escape_clause", &format!("cuts[{index}]"))?,
            &format!("cuts[{index}].escape_clause"),
            num_vars,
        )?;
        if escape_clause.is_empty() {
            return reject(format!("cuts[{index}].escape_clause must not be empty"));
        }
        if &escape_clause != expected_escape {
            return reject(format!("escape_clause mismatch cut_id={cut_id}"));
        }

        let mut occurrence_coeff: BTreeMap<String, u64> = BTreeMap::new();
        for lit in &escape_clause {
            let Some(guard_id) = lit_to_guard.get(lit) else {
                return reject(format!(
                    "cuts[{index}].escape_clause literal {lit} has no guard"
                ));
            };
            *occurrence_coeff.entry(guard_id.clone()).or_insert(0) += 1;
        }

        let coeff_raw = json_object(
            field(cut, "coeff", &format!("cuts[{index}]"))?,
            &format!("cuts[{index}].coeff"),
        )?;
        let mut coeff = BTreeMap::new();
        for (guard_id, value) in coeff_raw {
            if !guards.contains_key(guard_id) {
                return reject(format!(
                    "cuts[{index}].coeff references unknown guard {guard_id}"
                ));
            }
            coeff.insert(
                guard_id.clone(),
                positive(value, &format!("cuts[{index}].coeff[{guard_id}]"))?,
            );
        }
        if coeff != occurrence_coeff {
            return reject(format!("coeff occurrence mismatch cut_id={cut_id}"));
        }
        cuts.insert(
            cut_id.to_string(),
            Cut {
                deficit,
                scale,
                coeff,
            },
        );
    }

    if cuts.keys().cloned().collect::<BTreeSet<_>>()
        != hall_escape_by_cut.keys().cloned().collect::<BTreeSet<_>>()
    {
        return reject("cuts ids must match depends_on cut_ids");
    }
    Ok(cuts)
}

fn read_packed_coeff(
    raw_packed_coeff: &Value,
) -> Result<BTreeMap<String, u64>, GuardCoverSidecarError> {
    let packed_coeff_raw = json_object(raw_packed_coeff, "packing.packed_coeff")?;
    let mut packed_coeff = BTreeMap::new();
    for (guard_id, value) in packed_coeff_raw {
        packed_coeff.insert(
            guard_id.clone(),
            positive(value, &format!("packing.packed_coeff[{guard_id}]"))?,
        );
    }
    Ok(packed_coeff)
}

fn check_packing(
    packing: &Map<String, Value>,
    budget_rhs: u64,
    guards: &BTreeMap<String, Guard>,
    cuts: &BTreeMap<String, Cut>,
) -> Result<u64, GuardCoverSidecarError> {
    let packed_deficit = positive(
        field(packing, "packed_deficit", "packing")?,
        "packing.packed_deficit",
    )?;
    let expected_deficit = cuts
        .values()
        .try_fold(0u64, |acc, cut| {
            cut.scale
                .checked_mul(cut.deficit)
                .and_then(|v| acc.checked_add(v))
        })
        .ok_or_else(|| GuardCoverSidecarError("packed_deficit overflow".to_string()))?;
    if packed_deficit != expected_deficit {
        return reject(format!(
            "packed_deficit mismatch: got {packed_deficit}, expected {expected_deficit}"
        ));
    }

    let packed_coeff = read_packed_coeff(field(packing, "packed_coeff", "packing")?)?;
    let mut expected_coeff: BTreeMap<String, u64> = BTreeMap::new();
    for cut in cuts.values() {
        for (guard_id, coeff) in &cut.coeff {
            let scaled = cut
                .scale
                .checked_mul(*coeff)
                .ok_or_else(|| GuardCoverSidecarError("packed_coeff overflow".to_string()))?;
            let entry = expected_coeff.entry(guard_id.clone()).or_insert(0);
            *entry = entry
                .checked_add(scaled)
                .ok_or_else(|| GuardCoverSidecarError("packed_coeff overflow".to_string()))?;
        }
    }
    if packed_coeff != expected_coeff {
        return reject("packed_coeff mismatch");
    }

    for (guard_id, coeff) in &packed_coeff {
        let Some(guard) = guards.get(guard_id) else {
            return reject(format!(
                "packing.packed_coeff references unknown guard {guard_id}"
            ));
        };
        if coeff > &guard.beta {
            return reject(format!(
                "coefficient domination failed guard={guard_id}: coeff={coeff} beta={}",
                guard.beta
            ));
        }
    }

    if field(packing, "coeff_dominated_by_beta", "packing")?.as_bool() != Some(true) {
        return reject("packing.coeff_dominated_by_beta must be true");
    }
    let contradiction = string_value(
        field(packing, "contradiction", "packing")?,
        "packing.contradiction",
    )?;
    if contradiction != "budget.rhs < packed_deficit" {
        return reject("packing.contradiction must be budget.rhs < packed_deficit");
    }
    if budget_rhs >= packed_deficit {
        return reject(format!(
            "contradiction failed: budget.rhs={budget_rhs} packed_deficit={packed_deficit}"
        ));
    }
    Ok(packed_deficit)
}

/// Check a guard-cover-packing sidecar and its Hall dependencies.
///
/// `hall_resolver` is called with each relative `depends_on[].witness` value
/// and must return the corresponding Hall+Sinz sidecar text. The checker does
/// not perform filesystem access on its own.
pub fn check_guard_cover_packing_sidecar<R>(
    cnf_bytes: &[u8],
    sidecar_text: &str,
    hall_resolver: R,
) -> Result<GuardCoverPackingEvidence, GuardCoverSidecarError>
where
    R: FnMut(&str) -> Result<String, String>,
{
    let cnf = parse_cnf(cnf_bytes)?;
    let clauses = clause_set(&cnf);
    let value = parse_json_object(sidecar_text, "guard-cover sidecar")?;
    let payload = json_object(&value, "guard-cover sidecar")?;

    if nat(field(payload, "version", "guard-cover sidecar")?, "version")? != 1 {
        return reject("version must be 1");
    }
    if string_value(field(payload, "lane", "guard-cover sidecar")?, "lane")?
        != "guard-cover-packing"
    {
        return reject("lane must be guard-cover-packing");
    }
    if string_value(field(payload, "theorem", "guard-cover sidecar")?, "theorem")?
        != STABLE_GUARD_COVER_PACKING_THEOREM
    {
        return reject(format!(
            "theorem must be {STABLE_GUARD_COVER_PACKING_THEOREM}"
        ));
    }
    check_hash(cnf_bytes, payload, "formula_sha256", true)?;

    let hall_escape_by_cut = check_dependencies(
        cnf_bytes,
        field(payload, "depends_on", "guard-cover sidecar")?,
        hall_resolver,
    )?;
    let guards = read_guards(
        field(payload, "guards", "guard-cover sidecar")?,
        cnf.num_vars,
    )?;
    let budget = json_object(field(payload, "budget", "guard-cover sidecar")?, "budget")?;
    let budget_rhs = nat(field(budget, "rhs", "budget")?, "budget.rhs")?;
    let budget_terms = read_budget_terms(budget, &guards, cnf.num_vars)?;
    check_budget_evidence(budget, &budget_terms, &clauses, cnf.num_vars)?;

    let cuts = read_cuts(
        field(payload, "cuts", "guard-cover sidecar")?,
        &hall_escape_by_cut,
        &guards,
        cnf.num_vars,
    )?;
    let packing = json_object(field(payload, "packing", "guard-cover sidecar")?, "packing")?;
    let packed_deficit = check_packing(packing, budget_rhs, &guards, &cuts)?;

    Ok(GuardCoverPackingEvidence {
        theorem: STABLE_GUARD_COVER_PACKING_THEOREM,
        cuts: cuts.len(),
        guards: guards.len(),
        budget_rhs,
        packed_deficit,
    })
}

/// Check a separator-cover sidecar against exact DIMACS bytes.
pub fn check_separator_cover_sidecar(
    cnf_bytes: &[u8],
    sidecar_text: &str,
) -> Result<SeparatorCoverEvidence, GuardCoverSidecarError> {
    let cnf = parse_cnf(cnf_bytes)?;
    let clauses = clause_set(&cnf);
    let value = parse_json_object(sidecar_text, "separator-cover sidecar")?;
    let payload = json_object(&value, "separator-cover sidecar")?;

    if nat(
        field(payload, "version", "separator-cover sidecar")?,
        "version",
    )? != 1
    {
        return reject("version must be 1");
    }
    if string_value(field(payload, "lane", "separator-cover sidecar")?, "lane")?
        != "separator-cover"
    {
        return reject("lane must be separator-cover");
    }
    if string_value(
        field(payload, "theorem", "separator-cover sidecar")?,
        "theorem",
    )? != STABLE_SEPARATOR_COVER_THEOREM
    {
        return reject(format!("theorem must be {STABLE_SEPARATOR_COVER_THEOREM}"));
    }
    check_hash(cnf_bytes, payload, "formula_sha256", true)?;

    let separator_vars = read_separator_vars(
        field(payload, "separator_vars", "separator-cover sidecar")?,
        cnf.num_vars,
    )?;
    let cubes = read_separator_cubes(
        field(payload, "cubes", "separator-cover sidecar")?,
        &clauses,
        cnf.num_vars,
    )?;
    let covered_assignments = check_separator_cover_complete(&separator_vars, &cubes)?;

    Ok(SeparatorCoverEvidence {
        theorem: STABLE_SEPARATOR_COVER_THEOREM,
        separator_vars: separator_vars.len(),
        cubes: cubes.len(),
        covered_assignments,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn fixture_cnf() -> Vec<u8> {
        b"p cnf 7 10\n\
1 3 0\n\
2 4 0\n\
-1 6 0\n\
-5 6 0\n\
-1 -5 0\n\
-2 7 0\n\
-6 7 0\n\
-2 -6 0\n\
-3 0\n\
-4 0\n"
            .to_vec()
    }

    fn fixture_hall(cnf: &[u8]) -> String {
        let formula_sha256 = sha256_hex(cnf);
        json!({
            "version": 1,
            "lane": "hall-sinz-escape",
            "formula_sha256": formula_sha256,
            "theorems": [STABLE_HALL_SINZ_ESCAPE_THEOREM],
            "witness": {
                "objects": ["p0", "p1"],
                "resources": ["h0"],
                "capacity": {"h0": 1},
                "allowed": {"p0": ["h0"], "p1": ["h0"]},
                "edge_lits": {"p0": {"h0": 1}, "p1": {"h0": 2}},
                "forbid_lits": {"p0": [3], "p1": [4]},
                "sinz_rows": {
                    "h0": {
                        "width": 1,
                        "zero": [5],
                        "steps": [
                            {"input": 1, "row": [6]},
                            {"input": 2, "row": [7]}
                        ]
                    }
                }
            }
        })
        .to_string()
    }

    fn fixture_guard(cnf: &[u8]) -> String {
        let formula_sha256 = sha256_hex(cnf);
        json!({
            "version": 1,
            "lane": "guard-cover-packing",
            "formula_sha256": formula_sha256,
            "theorem": STABLE_GUARD_COVER_PACKING_THEOREM,
            "depends_on": [{
                "cut_id": "core-000",
                "witness": "case.core-000.hall.json",
                "accepted_theorem": STABLE_HALL_SINZ_ESCAPE_THEOREM
            }],
            "guards": [
                {"id": "core-000:p0", "lit": 3, "beta": 1},
                {"id": "core-000:p1", "lit": 4, "beta": 1}
            ],
            "cuts": [{
                "id": "core-000",
                "deficit": 1,
                "scale": 1,
                "coeff": {"core-000:p0": 1, "core-000:p1": 1},
                "escape_clause": [3, 4],
                "source": "hall-sinz-sidecar"
            }],
            "budget": {
                "rhs": 0,
                "terms": [
                    {"guard": "core-000:p0", "lit": 3, "weight": 1},
                    {"guard": "core-000:p1", "lit": 4, "weight": 1}
                ],
                "evidence": {"kind": "negative-units", "rhs": 0}
            },
            "packing": {
                "packed_deficit": 1,
                "packed_coeff": {"core-000:p0": 1, "core-000:p1": 1},
                "coeff_dominated_by_beta": true,
                "contradiction": "budget.rhs < packed_deficit"
            }
        })
        .to_string()
    }

    fn fixture_separator_cnf() -> Vec<u8> {
        b"p cnf 1 2\n1 0\n-1 0\n".to_vec()
    }

    fn fixture_separator_cover(cnf: &[u8]) -> String {
        let formula_sha256 = sha256_hex(cnf);
        json!({
            "version": 1,
            "lane": "separator-cover",
            "formula_sha256": formula_sha256,
            "theorem": STABLE_SEPARATOR_COVER_THEOREM,
            "separator_vars": [1],
            "cubes": [
                {"id": "x=true", "lits": [1], "refuted_by": [-1]},
                {"id": "x=false", "lits": [-1], "refuted_by": [1]}
            ]
        })
        .to_string()
    }

    #[test]
    fn huge_declared_clause_count_does_not_drive_preallocation() {
        assert_eq!(initial_clause_capacity(usize::MAX, 17), 17);

        let cnf = format!("p cnf 1 {}\n1 0\n", usize::MAX);
        let error = parse_cnf(cnf.as_bytes()).expect_err("clause-count mismatch must reject");
        assert!(
            error.detail().contains("header clause count"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn accepts_guard_cover_sidecar_with_hall_dependency() {
        let cnf = fixture_cnf();
        let hall = fixture_hall(&cnf);
        let guard = fixture_guard(&cnf);

        let accepted = check_guard_cover_packing_sidecar(&cnf, &guard, |witness| {
            if witness == "case.core-000.hall.json" {
                Ok(hall.clone())
            } else {
                Err(format!("unexpected witness {witness}"))
            }
        })
        .expect("sidecar should be accepted");

        assert_eq!(accepted.cuts, 1);
        assert_eq!(accepted.guards, 2);
        assert_eq!(accepted.budget_rhs, 0);
        assert_eq!(accepted.packed_deficit, 1);
    }

    #[test]
    fn rejects_formula_hash_mismatch() {
        let cnf = fixture_cnf();
        let hall = fixture_hall(&cnf);
        let mut guard: Value = serde_json::from_str(&fixture_guard(&cnf)).expect("guard JSON");
        guard["formula_sha256"] = Value::String("sha256:0000".to_string());

        let error =
            check_guard_cover_packing_sidecar(&cnf, &guard.to_string(), |_| Ok(hall.clone()))
                .expect_err("hash mismatch must reject");

        assert!(
            error.detail().contains("formula_sha256 mismatch"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn rejects_coefficients_that_do_not_match_escape_occurrences() {
        let cnf = fixture_cnf();
        let hall = fixture_hall(&cnf);
        let mut guard: Value = serde_json::from_str(&fixture_guard(&cnf)).expect("guard JSON");
        guard["cuts"][0]["coeff"]["core-000:p1"] = Value::Number(2u64.into());

        let error =
            check_guard_cover_packing_sidecar(&cnf, &guard.to_string(), |_| Ok(hall.clone()))
                .expect_err("bad occurrence coefficients must reject");

        assert!(
            error.detail().contains("coeff occurrence mismatch"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn accepts_minimal_separator_cover_sidecar() {
        let cnf = fixture_separator_cnf();
        let sidecar = fixture_separator_cover(&cnf);

        let accepted = check_separator_cover_sidecar(&cnf, &sidecar)
            .expect("separator-cover sidecar should be accepted");

        assert_eq!(accepted.theorem, STABLE_SEPARATOR_COVER_THEOREM);
        assert_eq!(accepted.separator_vars, 1);
        assert_eq!(accepted.cubes, 2);
        assert_eq!(accepted.covered_assignments, 2);
    }

    #[test]
    fn rejects_incomplete_separator_cover_sidecar() {
        let cnf = fixture_separator_cnf();
        let mut sidecar: Value =
            serde_json::from_str(&fixture_separator_cover(&cnf)).expect("sidecar JSON");
        sidecar["cubes"].as_array_mut().unwrap().pop();

        let error = check_separator_cover_sidecar(&cnf, &sidecar.to_string())
            .expect_err("incomplete cover must reject");

        assert!(
            error.detail().contains("incomplete separator cover"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn rejects_separator_cube_not_refuting_clause() {
        let cnf = fixture_separator_cnf();
        let mut sidecar: Value =
            serde_json::from_str(&fixture_separator_cover(&cnf)).expect("sidecar JSON");
        sidecar["cubes"][0]["refuted_by"] = json!([1]);

        let error = check_separator_cover_sidecar(&cnf, &sidecar.to_string())
            .expect_err("non-refuting cube must reject");

        assert!(
            error
                .detail()
                .contains("does not falsify refuted_by literal"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn rejects_min_i32_separator_literal() {
        let cnf = fixture_separator_cnf();
        let mut sidecar: Value =
            serde_json::from_str(&fixture_separator_cover(&cnf)).expect("sidecar JSON");
        sidecar["cubes"][0]["lits"] = json!([i32::MIN]);

        let error = check_separator_cover_sidecar(&cnf, &sidecar.to_string())
            .expect_err("minimum i32 literal must reject");

        assert!(
            error
                .detail()
                .contains("supported negatable DIMACS literal range"),
            "unexpected error: {error}"
        );
    }
}
