// Copyright 2026 Andrew Yates
// SPDX-License-Identifier: Apache-2.0

#![allow(clippy::panic)]

//! Soundness regression: non-string sequence spurious-UNSAT (sequences fuzzer
//! seed 69).
//!
//! The no-proof search enables optimizations (eager LIA routing, guarded-eq
//! mining, second variable substitution) that are disabled under proof
//! production and carry latent soundness holes. Combined with the heuristic
//! non-string-sequence axiom battery in `solve_seq_lia`, they closed the
//! following `(Seq Bool)` formula as a SPURIOUS `unsat` while z3 decides it
//! `sat`:
//!
//! ```text
//! (or (xor (distinct (seq.extract sqb0 0 (seq.len sqb0)) sqb0)
//!          <replace-to-empty / extract-of-empty concat equality>)
//!     (and (seq.nth (seq.++ sqb2 (seq.unit false)) i0)
//!          (seq.contains sqb3 sqb3) (seq.contains sqb3 sqb2)))
//! ```
//!
//! This wrong `unsat` was invisible to BOTH soundness checks: the SAT-side
//! model-validation gate never inspects an `unsat`, and proof-checking never
//! ran because in proof mode the spurious conflict is not even derived (proof
//! mode returns `unknown` for this shape). The fix (`check_sat_guarded`
//! #nonstring-seq-unsat-corroboration) corroborates any non-string-seq `unsat`
//! reached without proofs by re-solving once with proofs forced on; an
//! uncorroborated `unsat` fails closed to `unknown` (always sound).
//!
//! `run_executor_smt_with_timeout` builds a bare `Executor::new()` (proofs off),
//! i.e. the exact no-proof path that produced the wrong verdict — and the same
//! path the ayz3 / FFI binding takes. The only sound outcomes are `unknown` or
//! `sat`; `unsat` is a WRONG answer and MUST NOT regress.

mod common;

use common::SolverOutcome;
use ntest::timeout;

/// The full seed-69 reproducer (nested `let`, as generated by the fuzzer).
const SEED69: &str = r#"
(set-logic ALL)
(declare-fun sqb0 () (Seq Bool))
(declare-fun sqb1 () (Seq Bool))
(declare-fun sqb2 () (Seq Bool))
(declare-fun sqb3 () (Seq Bool))
(declare-fun i0 () Int)
(assert (let ((a!1 (= (seq.++ (seq.replace sqb0 (seq.unit true) (as seq.empty (Seq Bool))) (as seq.empty (Seq Bool)))
                      (seq.++ sqb1 (seq.extract (as seq.empty (Seq Bool)) 0 (seq.len (as seq.empty (Seq Bool)))))))
      (a!3 (and (seq.nth (seq.++ sqb2 (seq.unit false)) i0) (seq.contains sqb3 sqb3) (seq.contains sqb3 sqb2))))
(let ((a!2 (xor (distinct (seq.extract sqb0 0 (seq.len sqb0)) sqb0) a!1)))
  (or a!2 a!3))))
(check-sat)
"#;

/// The flattened minimization (single `assert`, no `let`).
const MIN: &str = r#"
(set-logic ALL)
(declare-fun sqb0 () (Seq Bool))
(declare-fun sqb1 () (Seq Bool))
(declare-fun sqb2 () (Seq Bool))
(declare-fun sqb3 () (Seq Bool))
(declare-fun i0 () Int)
(assert (or (xor (distinct (seq.extract sqb0 0 (seq.len sqb0)) sqb0)
                 (= (seq.++ (seq.replace sqb0 (seq.unit true) (as seq.empty (Seq Bool))) (as seq.empty (Seq Bool)))
                    (seq.++ sqb1 (seq.extract (as seq.empty (Seq Bool)) 0 (seq.len (as seq.empty (Seq Bool)))))))
            (and (seq.nth (seq.++ sqb2 (seq.unit false)) i0) (seq.contains sqb3 sqb3) (seq.contains sqb3 sqb2))))
(check-sat)
"#;

fn assert_never_unsat(label: &str, smt: &str) {
    let outcome = common::run_executor_smt_with_timeout(smt, 30)
        .unwrap_or_else(|err| panic!("solver error on {label}: {err}"));
    assert_ne!(
        outcome,
        SolverOutcome::Unsat,
        "{label}: no-proof path reported a SPURIOUS unsat (z3 decides this sat); \
         only `sat` or `unknown` are sound here"
    );
}

#[test]
#[timeout(60_000)]
fn seed69_nonstring_seq_is_never_unsat() {
    assert_never_unsat("seed69", SEED69);
    assert_never_unsat("min", MIN);
}

/// Guard the discriminator: GENUINE non-string sequence unsats must still be
/// decided `unsat` — the corroboration gate is demote-only and must not
/// blanket-fail-close every seq unsat. `(seq.extract s 0 (seq.len s)) = s`
/// always holds, so `distinct` of the two is genuinely unsatisfiable, and z3
/// agrees. These reconfirm under proof mode and must survive the gate.
#[test]
#[timeout(60_000)]
fn genuine_nonstring_seq_unsats_survive() {
    let cases = [
        (
            "distinct-extract-whole",
            r#"
(set-logic ALL)
(declare-fun s () (Seq Bool))
(assert (distinct (seq.extract s 0 (seq.len s)) s))
(check-sat)
"#,
        ),
        (
            "len-conflict",
            r#"
(set-logic ALL)
(declare-fun s () (Seq Int))
(assert (= (seq.len s) 3))
(assert (= (seq.len s) 4))
(check-sat)
"#,
        ),
        (
            "unit-len",
            r#"
(set-logic ALL)
(declare-fun s () (Seq Int))
(assert (= s (seq.unit 5)))
(assert (not (= (seq.len s) 1)))
(check-sat)
"#,
        ),
        (
            "empty-contains",
            r#"
(set-logic ALL)
(declare-fun s () (Seq Bool))
(assert (seq.contains s (seq.unit true)))
(assert (= (seq.len s) 0))
(check-sat)
"#,
        ),
        (
            "concat-empty-len",
            r#"
(set-logic ALL)
(declare-fun a () (Seq Int))
(declare-fun b () (Seq Int))
(assert (= (seq.++ a b) (as seq.empty (Seq Int))))
(assert (not (= (seq.len a) 0)))
(check-sat)
"#,
        ),
    ];
    for (label, smt) in cases {
        let outcome = common::run_executor_smt_with_timeout(smt, 30)
            .unwrap_or_else(|err| panic!("solver error on {label}: {err}"));
        assert_eq!(
            outcome,
            SolverOutcome::Unsat,
            "{label}: genuine seq unsat must stay `unsat` (corroboration gate \
             must not blanket-demote non-string-seq unsats)"
        );
    }
}
