#!/bin/bash
#SBATCH --job-name=ay-chccomp-worker
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=24:00:00
#SBATCH --array=0-10
#SBATCH --output=logs/ay-worker-%A_%a.out
#SBATCH --error=logs/ay-worker-%A_%a.err
# ay-script: chccomp-slurm-worker

# Copyright 2026 Andrew Yates
# Licensed under the Apache License, Version 2.0

set -euo pipefail

# This SLURM script runs the `ay` distributed worker pipeline.
# It uses SLURM_ARRAY_TASK_ID to automatically pick a sharded lane of the CHC-COMP benchmarks.

# 1. Ensure the Rust environment and binary are ready
cargo build --release --bin ay --features="cli bench"

# 2. Get the specific lane assigned to this array task
# (e.g. tracks, or partitions generated by `ay submission worker chc-comp shard-plan`)
LANE_NAME="lane_${SLURM_ARRAY_TASK_ID}"

echo "Starting AY CHC-COMP Worker on $(hostname) for lane: $LANE_NAME"

# 3. Run the harvest/gate worker job
target/release/ay submission worker chc-comp run \
    --issue 1 \
    --lane "$LANE_NAME" \
    --benchmarks-root benchmarks/chc/chc-comp26-benchmarks \
    --tracks "LIA,BV,LIA-Arrays,ADT-LIA,LRA-Lin" \
    --benchmark-timeout-ms 300000 \
    --report-dir the development design notes

echo "Worker task completed."
