#!/usr/bin/env python3
# Copyright 2026 Andrew Yates
# Author: Andrew Yates <andrewyates.name@gmail.com>
# Licensed under the Apache License, Version 2.0
"""Close the two known dense-binary AY/Gurobi comparison gaps.

The corpus is generated by ``crates/ay-milp/examples/milp_speed.rs``.  This
harness freezes that already-built generator and the production ``ay-milp``
binary, asks the generator to dump deterministic MPS, then feeds those identical
bytes to both production AY and Gurobi under one serial `_oom_guard` lease.  It
does not build: benchmark/build overlap is a hard refusal.

Default cases are exactly the known open evidence:

* the twelve <=75x56 ladder members at matched 8T, covering the historical gap;
* the same twelve members at matched 1T, preventing a routed 8T win from hiding
  a new serial regression;
* 80x60 seed 2026, where Gurobi 1T proved in 102.02s and AY did not at 180s.

A case closes only when both solvers return the published optimum, both emitted
points pass production AY's exact rational checker against the shared MPS, and
AY's end-to-end process wall is no greater.  Timeouts, invalid optima, missing
output, memory-envelope breaches, and truncation all fail closed.

Exit status is zero only when every repetition of every case closes.  Any
measured Gurobi advantage or invalid/incomplete solver evidence returns one;
argument/preflight failures remain non-zero through ``argparse`` or an exception.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import pathlib
import platform
import shutil
import stat
import subprocess
import sys
import time
from fractions import Fraction
from typing import List, Optional

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
sys.path.insert(0, str(SCRIPT_DIR))

from _oom_guard import (  # noqa: E402
    plan_solver_resources,
    run_captured,
    warn_concurrent_build,
)
import ay_gurobi_closure as evidence  # noqa: E402


LADDER_8T = tuple(
    (n, m, seed, optimum)
    for n, m, optima in (
        (60, 45, {7: 228, 42: 204, 99: 223, 2026: 256}),
        (70, 52, {7: 302, 42: 310, 99: 194, 2026: 270}),
        (75, 56, {7: 241, 42: 339, 99: 242, 2026: 278}),
    )
    for seed, optimum in sorted(optima.items())
)
LADDER_1T = LADDER_8T
SERIAL_1T = ((80, 60, 2026, 273),)

GUROBI_DRIVER = r"""
import json
import sys
import time
import gurobipy as gp

path, threads, timeout, solution_path = (
    sys.argv[1], int(sys.argv[2]), float(sys.argv[3]), sys.argv[4]
)
started = time.monotonic()
solver_env = gp.Env(empty=True)
solver_env.setParam("OutputFlag", 0)
solver_env.start()
model = gp.read(path, env=solver_env)
model.Params.OutputFlag = 0
model.Params.Threads = threads
model.Params.TimeLimit = timeout
model.Params.Seed = 0
model.Params.MIPGap = 0.0
model.Params.MIPGapAbs = 0.0
model.optimize()
solution_error = None
if model.SolCount:
    try:
        model.write(solution_path)
    except Exception as error:
        solution_error = "%s: %s" % (type(error).__name__, error)
status_names = {
    gp.GRB.OPTIMAL: "optimal",
    gp.GRB.INFEASIBLE: "infeasible",
    gp.GRB.UNBOUNDED: "unbounded",
    gp.GRB.INF_OR_UNBD: "inf_or_unbd",
    gp.GRB.TIME_LIMIT: "time_limit",
}
print(json.dumps({
    "status": status_names.get(model.Status, "status_%d" % model.Status),
    "objective": model.ObjVal if model.SolCount else None,
    "best_bound": model.ObjBound if model.IsMIP else None,
    "node_count": model.NodeCount if model.IsMIP else 0,
    "solution_count": model.SolCount,
    "solution_error": solution_error,
    "worker_budget": model.Params.Threads,
    "seed": model.Params.Seed,
    "mip_gap": model.Params.MIPGap,
    "mip_gap_abs": model.Params.MIPGapAbs,
    "solver_runtime_sec": model.Runtime,
    "driver_wall_sec": time.monotonic() - started,
    "version": list(gp.gurobi.version()),
}, sort_keys=True, allow_nan=False))
"""


def sha256_file(path: pathlib.Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def file_identity(path: pathlib.Path) -> dict[str, object]:
    info = path.stat()
    return {
        "path": str(path),
        "sha256": sha256_file(path),
        "bytes": info.st_size,
        "mtime_ns": info.st_mtime_ns,
    }


def git_provenance() -> dict[str, object]:
    def git(*args: str) -> str:
        return subprocess.run(
            ["git", *args],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()

    status = git("status", "--short")
    return {
        "head": git("rev-parse", "HEAD"),
        "branch": git("branch", "--show-current"),
        "dirty": bool(status),
        "status_sha256": hashlib.sha256(status.encode()).hexdigest(),
    }


def controlled_env(plan, threads: int, timeout: float) -> dict[str, str]:
    env = {
        key: value
        for key, value in os.environ.items()
        if not key.startswith(("AY_", "NY_"))
        and key not in {
            "MEMLIMIT", "NBCORE", "TIME_LIMIT", "LP_DUMP", "MPS_DUMP", "DUMP_ONLY"
        }
    }
    env.update(
        {
            "OMP_NUM_THREADS": str(threads),
            "OPENBLAS_NUM_THREADS": str(threads),
            "MKL_NUM_THREADS": str(threads),
            "VECLIB_MAXIMUM_THREADS": str(threads),
            "NUMEXPR_NUM_THREADS": str(threads),
            "RAYON_NUM_THREADS": str(threads),
        }
    )
    return env


def environment_posture(env: dict[str, str], threads: int) -> dict[str, object]:
    fingerprint = hashlib.sha256()
    for key in sorted(env):
        fingerprint.update(key.encode("utf-8"))
        fingerprint.update(b"=")
        fingerprint.update(env[key].encode("utf-8"))
        fingerprint.update(b"\0")
    return {
        "sha256": fingerprint.hexdigest(),
        "thread_limits": {
            key: env[key]
            for key in (
                "OMP_NUM_THREADS",
                "OPENBLAS_NUM_THREADS",
                "MKL_NUM_THREADS",
                "VECLIB_MAXIMUM_THREADS",
                "NUMEXPR_NUM_THREADS",
                "RAYON_NUM_THREADS",
            )
        },
        "requested_threads": threads,
        "gurobi_license_environment_names_present": [
            key for key in evidence.LICENSE_ENV_NAMES if key in env
        ],
        "license_environment_values_recorded": False,
    }


def command_identity(
    command: list[str], embedded_source: str | None = None
) -> dict[str, object]:
    display = list(command)
    if embedded_source is not None:
        display = [
            f"<embedded Python sha256={hashlib.sha256(embedded_source.encode()).hexdigest()}>"
            if field == embedded_source
            else field
            for field in display
        ]
    raw = b"\0".join(os.fsencode(field) for field in command)
    return {"argv": display, "argv_sha256": hashlib.sha256(raw).hexdigest()}


def optional_file_identity(path: pathlib.Path) -> dict[str, object]:
    if not path.is_file():
        return {"path": str(path), "exists": False}
    identity = file_identity(path)
    identity["exists"] = True
    return identity


def captured_fields(run) -> dict[str, object]:
    return {
        "process_wall_sec": run.wall_sec,
        "returncode": run.returncode,
        "timed_out": run.timed_out,
        "memout": run.memout,
        "cancelled": run.cancelled,
        "stdout_truncated": run.stdout_truncated,
        "stderr_truncated": run.stderr_truncated,
        "output_truncated": run.output_truncated,
        "stdout": run.stdout,
        "stderr": run.stderr,
    }


def build_ay_command(
    binary: pathlib.Path,
    mps_path: pathlib.Path,
    threads: int,
    timeout: float,
    certificate: pathlib.Path,
    witness: pathlib.Path,
) -> list[str]:
    return [
        str(binary),
        "solve",
        str(mps_path),
        "--time-limit",
        format(timeout, ".17g"),
        "--threads",
        str(threads),
        "--seed",
        "0",
        "--deterministic" if threads == 1 else "--no-deterministic",
        "--require",
        "witness",
        "--emit-cert",
        str(certificate),
        "--emit-witness",
        str(witness),
        "--witness-format",
        "rational",
        "--format",
        "json",
    ]


def run_point_checker(
    binary: pathlib.Path,
    mps_path: pathlib.Path,
    point_path: pathlib.Path,
    checker_timeout: float,
    plan,
    env: dict[str, str],
    label: str,
) -> dict[str, object]:
    if not point_path.is_file():
        return {"not_run": True, "reason": "point was not emitted"}
    run = run_captured(
        [
            str(binary),
            "check-point",
            "--model",
            str(mps_path),
            "--point",
            str(point_path),
        ],
        plan.memlimit_mb,
        checker_timeout,
        label=label,
        env=env,
        cwd=REPO_ROOT,
    )
    return {**captured_fields(run), "parsed": evidence.parse_point_output(run.stdout)}


def run_certificate_checker(
    binary: pathlib.Path,
    mps_path: pathlib.Path,
    certificate_path: pathlib.Path,
    checker_timeout: float,
    plan,
    env: dict[str, str],
    label: str,
) -> dict[str, object]:
    if not certificate_path.is_file():
        return {"not_run": True, "reason": "certificate was not emitted"}
    run = run_captured(
        [
            str(binary),
            "verify",
            "--model",
            str(mps_path),
            "--cert",
            str(certificate_path),
        ],
        plan.memlimit_mb,
        checker_timeout,
        label=label,
        env=env,
        cwd=REPO_ROOT,
    )
    return {**captured_fields(run), "parsed": evidence.parse_verify_output(run.stdout)}


def run_ay(
    binary: pathlib.Path,
    mps_path: pathlib.Path,
    threads: int,
    timeout: float,
    plan,
    artifact_dir: pathlib.Path,
) -> dict[str, object]:
    artifact_dir.mkdir(parents=True, exist_ok=True)
    env = controlled_env(plan, threads, timeout)
    certificate = artifact_dir / "result.ayc"
    witness = artifact_dir / "result.sol"
    command = build_ay_command(
        binary, mps_path, threads, timeout, certificate, witness
    )
    run = run_captured(
        command,
        plan.memlimit_mb,
        timeout + 10.0,
        label=f"dense-ay-{mps_path.stem}-{threads}t",
        env=env,
        cwd=REPO_ROOT,
    )
    payload = None
    parse_error = None
    try:
        payload = evidence.parse_last_json_object(run.stdout)
    except ValueError as error:
        parse_error = f"{type(error).__name__}: {error}"
    verdict = payload or {}
    return {
        "status": str(verdict.get("status", "unknown")).lower(),
        "objective": verdict.get("value"),
        "solver_runtime_sec": verdict.get("time"),
        "nodes": verdict.get("nodes"),
        "worker_budget": threads,
        "deterministic": threads == 1,
        "posture_source": "production CLI argv",
        "command": command_identity(command),
        "environment": environment_posture(env, threads),
        "parse_error": parse_error,
        "certificate": optional_file_identity(certificate),
        "witness": optional_file_identity(witness),
        **captured_fields(run),
    }


def run_gurobi(
    python: str,
    lp_path: pathlib.Path,
    threads: int,
    timeout: float,
    plan,
    artifact_dir: pathlib.Path,
) -> dict[str, object]:
    artifact_dir.mkdir(parents=True, exist_ok=True)
    env = controlled_env(plan, threads, timeout)
    solution = artifact_dir / "result.sol"
    command = [
        python,
        "-c",
        GUROBI_DRIVER,
        str(lp_path),
        str(threads),
        format(timeout, ".17g"),
        str(solution),
    ]
    run = run_captured(
        command,
        plan.memlimit_mb,
        timeout + 10.0,
        label=f"dense-gurobi-{lp_path.stem}-{threads}t",
        env=env,
        cwd=REPO_ROOT,
    )
    payload = None
    parse_error = None
    try:
        lines = [line for line in run.stdout.splitlines() if line.strip()]
        payload = json.loads(lines[-1]) if lines else None
        if not isinstance(payload, dict):
            raise ValueError("Gurobi driver emitted no JSON object")
    except (ValueError, json.JSONDecodeError) as error:
        parse_error = str(error)
    result = payload or {"status": "unknown", "objective": None}
    result.update(
        {
            "command": command_identity(command, GUROBI_DRIVER),
            "environment": environment_posture(env, threads),
            "parse_error": parse_error,
            "solution": optional_file_identity(solution),
            **captured_fields(run),
        }
    )
    return result


def valid_optimum(
    result: dict[str, object], expected: int, solver: str, expected_threads: int
) -> list[str]:
    failures = []
    if result.get("status") != "optimal":
        failures.append(f"{solver} did not prove optimal")
    raw = result.get("objective")
    value = None
    try:
        value = Fraction(str(raw))
        if value != expected:
            failures.append(f"{solver} objective {raw!r} != expected {expected}")
    except (TypeError, ValueError, ZeroDivisionError):
        failures.append(f"{solver} objective is unparseable: {raw!r}")
    for field in ("timed_out", "memout", "cancelled", "output_truncated"):
        if result.get(field):
            failures.append(f"{solver} {field}")
    if result.get("returncode") != 0:
        failures.append(f"{solver} returncode={result.get('returncode')}")
    if result.get("parse_error"):
        failures.append(f"{solver} parse error: {result['parse_error']}")
    if solver == "gurobi" and result.get("solution_error"):
        failures.append(f"Gurobi solution export failed: {result['solution_error']}")
    process_wall = result.get("process_wall_sec")
    if (
        isinstance(process_wall, bool)
        or not isinstance(process_wall, (int, float))
        or not math.isfinite(process_wall)
        or process_wall < 0
    ):
        failures.append(f"{solver} process wall is invalid: {process_wall!r}")
    runtime = result.get("solver_runtime_sec")
    if (
        isinstance(runtime, bool)
        or not isinstance(runtime, (int, float))
        or not math.isfinite(runtime)
        or runtime < 0
    ):
        failures.append(f"{solver} solver runtime is invalid: {runtime!r}")
    worker_budget = result.get("worker_budget")
    if type(worker_budget) is not int or worker_budget != expected_threads:
        failures.append(
            f"{solver} worker budget {worker_budget!r} != requested {expected_threads}"
        )
    if solver == "ay" and result.get("deterministic") is not (expected_threads == 1):
        failures.append(
            f"AY deterministic posture {result.get('deterministic')!r} != "
            f"requested {expected_threads == 1}"
        )
    if solver == "gurobi":
        if result.get("seed") != 0:
            failures.append(f"Gurobi seed {result.get('seed')!r} != requested 0")
        for field in ("mip_gap", "mip_gap_abs"):
            gap_value = result.get(field)
            if (
                isinstance(gap_value, bool)
                or not isinstance(gap_value, (int, float))
                or not math.isfinite(gap_value)
                or gap_value != 0.0
            ):
                failures.append(f"Gurobi {field} {gap_value!r} != requested 0")

    point_check = result.get("point_check")
    if not isinstance(point_check, dict) or point_check.get("not_run"):
        failures.append(f"{solver} point checker did not run")
    else:
        for field in (
            "timed_out",
            "memout",
            "cancelled",
            "stdout_truncated",
            "stderr_truncated",
        ):
            if point_check.get(field):
                failures.append(f"{solver} point checker {field}")
        if point_check.get("returncode") != 0:
            failures.append(
                f"{solver} point checker returncode={point_check.get('returncode')}"
            )
        parsed = point_check.get("parsed")
        if not isinstance(parsed, dict) or parsed.get("status") != "FEASIBLE":
            failures.append(f"{solver} point did not pass exact feasibility checking")
        else:
            columns = parsed.get("columns")
            if (
                not isinstance(columns, dict)
                or not isinstance(columns.get("named"), int)
                or not isinstance(columns.get("total"), int)
                or columns["total"] <= 0
                or columns["named"] != columns["total"]
            ):
                failures.append(
                    f"{solver} point checker did not name every model column: "
                    f"{columns!r}"
                )
            checked_raw = parsed.get("objective")
            try:
                checked = Fraction(str(checked_raw))
                if checked != expected:
                    failures.append(
                        f"{solver} checked point objective {checked_raw!r} != "
                        f"expected {expected}"
                    )
                elif value is None or value != checked:
                    failures.append(
                        f"{solver} reported objective {raw!r} != checked point "
                        f"objective {checked_raw!r}"
                    )
            except (TypeError, ValueError, ZeroDivisionError):
                failures.append(
                    f"{solver} checked point objective is unparseable: {checked_raw!r}"
                )
    if solver == "ay":
        certificate = result.get("certificate")
        if not isinstance(certificate, dict) or certificate.get("exists") is not True:
            failures.append("AY did not emit its requested certificate artifact")
        certificate_check = result.get("certificate_check")
        if not isinstance(certificate_check, dict) or certificate_check.get("not_run"):
            failures.append("AY certificate checker did not run")
        else:
            for field in (
                "timed_out",
                "memout",
                "cancelled",
                "stdout_truncated",
                "stderr_truncated",
            ):
                if certificate_check.get(field):
                    failures.append(f"AY certificate checker {field}")
            certificate_parsed = certificate_check.get("parsed")
            certificate_status = (
                certificate_parsed.get("status")
                if isinstance(certificate_parsed, dict)
                else None
            )
            expected_exit = {"VERIFIED": 0, "PARTIAL": 11}.get(certificate_status)
            if expected_exit is None or certificate_check.get("returncode") != expected_exit:
                failures.append(
                    "AY certificate checker did not return VERIFIED or consistent PARTIAL"
                )
            claims = (
                certificate_parsed.get("claims", {})
                if isinstance(certificate_parsed, dict)
                else {}
            )
            verified_claims = set(str(claims.get("verified", "-")).split(",")) - {
                "",
                "-",
            }
            refuted_claims = set(str(claims.get("refuted", "-")).split(",")) - {
                "",
                "-",
            }
            if "primal" not in verified_claims:
                failures.append("AY certificate lacks an independently verified primal claim")
            if refuted_claims:
                failures.append(
                    f"AY certificate contains refuted claims: {sorted(refuted_claims)}"
                )
    return failures


def freeze_binary(source: pathlib.Path, destination: pathlib.Path) -> dict[str, object]:
    source_identity = file_identity(source)
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
    destination.chmod(stat.S_IRUSR | stat.S_IXUSR)
    frozen_identity = file_identity(destination)
    if source_identity["sha256"] != frozen_identity["sha256"]:
        raise RuntimeError("AY dense-ladder binary changed while it was being frozen")
    return {"source": source_identity, "frozen": frozen_identity}


def generate_mps(binary: pathlib.Path, path: pathlib.Path, case, plan) -> dict[str, object]:
    n, m, seed, _ = case
    env = controlled_env(plan, 1, 1.0)
    env.update({"MPS_DUMP": str(path), "DUMP_ONLY": "1"})
    run = run_captured(
        [str(binary), str(n), str(m), str(seed)],
        plan.memlimit_mb,
        10.0,
        label=f"dense-generate-{n}x{m}-s{seed}",
        env=env,
        cwd=REPO_ROOT,
    )
    if (
        run.returncode != 0
        or run.timed_out
        or run.memout
        or run.cancelled
        or run.output_truncated
        or not path.is_file()
    ):
        raise RuntimeError(
            f"generator failed for {n}x{m} seed {seed}: "
            f"rc={run.returncode} timeout={run.timed_out} memout={run.memout} "
            f"cancelled={run.cancelled} truncated={run.output_truncated}\n{run.stderr}"
        )
    return file_identity(path)


def solver_order(case_index: int, repetition: int) -> tuple[str, str]:
    """Balance cold/warm launch ownership across cases and repetitions."""

    return ("ay", "gurobi") if (case_index + repetition) % 2 == 0 else ("gurobi", "ay")


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--ay-bin",
        type=pathlib.Path,
        default=REPO_ROOT / "target/release/ay-milp",
    )
    parser.add_argument(
        "--generator-bin",
        type=pathlib.Path,
        default=REPO_ROOT / "target/release/examples/milp_speed",
    )
    parser.add_argument("--gurobi-python", default=sys.executable)
    parser.add_argument("--timeout-8t", type=float, default=60.0)
    parser.add_argument("--timeout-1t", type=float, default=200.0)
    parser.add_argument("--checker-timeout", type=float, default=120.0)
    parser.add_argument("--repetitions", type=int, default=1)
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=REPO_ROOT / "evals/results/ay-gurobi-dense-ladder/closure.json",
    )
    args = parser.parse_args(argv)
    if args.repetitions < 1:
        parser.error("--repetitions must be positive")
    for label, value in (
        ("--timeout-8t", args.timeout_8t),
        ("--timeout-1t", args.timeout_1t),
        ("--checker-timeout", args.checker_timeout),
    ):
        if not math.isfinite(value) or value <= 0:
            parser.error(f"{label} must be finite and positive")

    source_binary = args.ay_bin.expanduser().resolve(strict=True)
    source_generator = args.generator_bin.expanduser().resolve(strict=True)
    python = shutil.which(args.gurobi_python)
    if python is None:
        parser.error(f"Gurobi Python executable not found: {args.gurobi_python}")
    output = args.out.expanduser().resolve()
    artifacts = output.with_name(f"{output.stem}.artifacts")
    if output.exists() or artifacts.exists():
        parser.error(f"refusing to overwrite {output} or {artifacts}")

    warn_concurrent_build()
    plan = plan_solver_resources(1, label="milp_dense_ladder_closure.py")
    if plan.jobs != 1:
        raise RuntimeError(f"closure harness requires a serial process plan: {plan}")
    if plan.nbcore < 8:
        raise RuntimeError(
            f"matched 8T closure needs at least 8 planned physical cores, got {plan.nbcore}"
        )

    provenance = git_provenance()
    artifacts.mkdir(parents=True)
    frozen_binary = artifacts / "bin/ay-milp"
    binary_identity = freeze_binary(source_binary, frozen_binary)
    frozen_generator = artifacts / "bin/milp_speed"
    generator_binary_identity = freeze_binary(source_generator, frozen_generator)
    generator_source = REPO_ROOT / "crates/ay-milp/examples/milp_speed.rs"

    cases = [(case, 8, args.timeout_8t) for case in LADDER_8T]
    cases.extend((case, 1, args.timeout_1t) for case in LADDER_1T)
    cases.extend((case, 1, args.timeout_1t) for case in SERIAL_1T)
    records = []
    lp_dir = artifacts / "instances"
    lp_dir.mkdir()
    generated = {}
    for case, _threads, _timeout in cases:
        n, m, seed, _expected = case
        key = f"{n}x{m}-s{seed}"
        if key not in generated:
            lp_path = lp_dir / f"{key}.mps"
            generated[key] = {
                "path": lp_path,
                "identity": generate_mps(frozen_generator, lp_path, case, plan),
            }

    for case_index, (case, threads, timeout) in enumerate(cases):
        n, m, seed, expected = case
        key = f"{n}x{m}-s{seed}"
        posture_key = f"{key}-{threads}t"
        if (
            file_identity(generated[key]["path"])["sha256"]
            != generated[key]["identity"]["sha256"]
        ):
            raise RuntimeError(
                f"generated benchmark input changed during campaign: "
                f"{generated[key]['path']}"
            )
        repetitions = []
        for repetition in range(args.repetitions):
            trial_dir = artifacts / "runs" / posture_key / f"r{repetition}"
            # Alternate launch order across both cases and repetitions so the
            # default one-repetition campaign is balanced too.  Evidence
            # checking happens only after both timed children have exited.
            order = solver_order(case_index, repetition)
            if order[0] == "ay":
                ay = run_ay(
                    frozen_binary,
                    generated[key]["path"],
                    threads,
                    timeout,
                    plan,
                    trial_dir / "ay",
                )
                gurobi = run_gurobi(
                    python,
                    generated[key]["path"],
                    threads,
                    timeout,
                    plan,
                    trial_dir / "gurobi",
                )
            else:
                gurobi = run_gurobi(
                    python,
                    generated[key]["path"],
                    threads,
                    timeout,
                    plan,
                    trial_dir / "gurobi",
                )
                ay = run_ay(
                    frozen_binary,
                    generated[key]["path"],
                    threads,
                    timeout,
                    plan,
                    trial_dir / "ay",
                )
            checker_env = controlled_env(plan, threads, timeout)
            ay["point_check"] = run_point_checker(
                frozen_binary,
                generated[key]["path"],
                pathlib.Path(ay["witness"]["path"]),
                args.checker_timeout,
                plan,
                checker_env,
                f"dense-ay-point-{posture_key}-r{repetition}",
            )
            ay["certificate_check"] = run_certificate_checker(
                frozen_binary,
                generated[key]["path"],
                pathlib.Path(ay["certificate"]["path"]),
                args.checker_timeout,
                plan,
                checker_env,
                f"dense-ay-cert-{posture_key}-r{repetition}",
            )
            gurobi["point_check"] = run_point_checker(
                frozen_binary,
                generated[key]["path"],
                pathlib.Path(gurobi["solution"]["path"]),
                args.checker_timeout,
                plan,
                checker_env,
                f"dense-gurobi-point-{posture_key}-r{repetition}",
            )
            failures = valid_optimum(ay, expected, "ay", threads)
            failures.extend(valid_optimum(gurobi, expected, "gurobi", threads))
            ay_wall = float(ay["process_wall_sec"])
            gurobi_wall = float(gurobi["process_wall_sec"])
            if not failures and ay_wall > gurobi_wall:
                failures.append(
                    f"Gurobi faster: AY {ay_wall:.6f}s > Gurobi {gurobi_wall:.6f}s"
                )
            ay_runtime = ay.get("solver_runtime_sec")
            gurobi_runtime = gurobi.get("solver_runtime_sec")
            if (
                not failures
                and isinstance(ay_runtime, (int, float))
                and isinstance(gurobi_runtime, (int, float))
                and ay_runtime > gurobi_runtime
            ):
                failures.append(
                    f"Gurobi solver faster: AY {ay_runtime:.6f}s > "
                    f"Gurobi {gurobi_runtime:.6f}s"
                )
            repetitions.append(
                {
                    "repetition": repetition,
                    "solver_order": list(order),
                    "ay": ay,
                    "gurobi": gurobi,
                    "gurobi_over_ay": gurobi_wall / ay_wall if ay_wall > 0 else None,
                    "gurobi_over_ay_solver_runtime": (
                        gurobi_runtime / ay_runtime
                        if isinstance(ay_runtime, (int, float))
                        and isinstance(gurobi_runtime, (int, float))
                        and ay_runtime > 0
                        else None
                    ),
                    "closed": not failures,
                    "failures": failures,
                }
            )
            print(
                f"{posture_key} r{repetition}: "
                f"AY={ay['status']} {ay_wall:.3f}s "
                f"GRB={gurobi.get('status')} {gurobi_wall:.3f}s "
                f"{'CLOSED' if not failures else 'OPEN'}",
                flush=True,
            )
        records.append(
            {
                "name": posture_key,
                "n": n,
                "m": m,
                "seed": seed,
                "expected_optimum": expected,
                "threads": threads,
                "timeout_sec": timeout,
                "instance": generated[key]["identity"],
                "closed": all(rep["closed"] for rep in repetitions),
                "repetitions": repetitions,
            }
        )

    payload = {
        "schema": "ay-gurobi-dense-ladder-closure-v1",
        "created_unix": time.time(),
        "closed": all(record["closed"] for record in records),
        "summary": {
            "expected_cases": len(cases),
            "expected_repetitions_per_case": args.repetitions,
            "cases": len(records),
            "closed": sum(record["closed"] for record in records),
            "open": sum(not record["closed"] for record in records),
        },
        "resource_envelope": {
            "requested_jobs": 1,
            "jobs": plan.jobs,
            "memlimit_mb_per_child": plan.memlimit_mb,
            "nbcore_planned": plan.nbcore,
            "headroom_mb": plan.headroom_mb,
            "enforcement": "process-group RSS watchdog on every AY/Gurobi/generator child",
            "rss_grace_mb": 0,
        },
        "evidence_posture": {
            "shared_input": "identical deterministic MPS bytes, SHA-256 recorded",
            "ay_binary": "frozen production ay-milp",
            "point_check": (
                "both emitted points re-parsed and checked in exact rational arithmetic "
                "with full column coverage"
            ),
            "ay_certificate": (
                "artifact required; independent verifier must return VERIFIED or PARTIAL "
                "with primal verified and no refuted claims"
            ),
            "optimality_truth": "frozen published optimum table in this harness",
            "known_limit": (
                "PARTIAL certificates may leave the optimal dual claim as replay evidence; "
                "that standing is preserved per trial and is not described as fully verified"
            ),
            "gurobi_mip_gap": 0.0,
            "gurobi_mip_gap_abs": 0.0,
            "solver_order": "alternating by case index and repetition",
        },
        "provenance": {
            "git": provenance,
            "binary": binary_identity,
            "generator_binary": generator_binary_identity,
            "generator_source": file_identity(generator_source),
            "python": sys.version,
            "platform": platform.platform(),
            "gurobi_python": file_identity(pathlib.Path(python)),
            "gurobi_driver_sha256": hashlib.sha256(GUROBI_DRIVER.encode()).hexdigest(),
        },
        "records": records,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(payload["summary"], sort_keys=True), flush=True)
    return campaign_exit_code(payload)


def campaign_exit_code(payload: dict[str, object]) -> int:
    """Return success only for a literally closed, complete campaign payload."""

    records = payload.get("records")
    if not isinstance(records, list) or not records:
        return 1
    if payload.get("closed") is not True:
        return 1
    summary = payload.get("summary")
    if not isinstance(summary, dict):
        return 1
    expected_cases = summary.get("expected_cases")
    expected_repetitions = summary.get("expected_repetitions_per_case")
    if (
        type(expected_cases) is not int
        or expected_cases <= 0
        or len(records) != expected_cases
        or type(expected_repetitions) is not int
        or expected_repetitions <= 0
    ):
        return 1
    for record in records:
        if not isinstance(record, dict) or record.get("closed") is not True:
            return 1
        repetitions = record.get("repetitions")
        if (
            not isinstance(repetitions, list)
            or len(repetitions) != expected_repetitions
        ):
            return 1
        repetition_ids = [
            repetition.get("repetition")
            for repetition in repetitions
            if isinstance(repetition, dict)
        ]
        if repetition_ids != list(range(expected_repetitions)):
            return 1
        if any(
            not isinstance(repetition, dict) or repetition.get("closed") is not True
            for repetition in repetitions
        ):
            return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
