#!/bin/sh
# PB-COMP run script for the AY pseudo-Boolean solver — GENERATED by
# competition/pb/package.sh from competition/pb/entries.toml (entry: AY).
# Edit entries.toml, not this file.
#
# The Pseudo-Boolean Competition substitutes its placeholders into the
# submitter-provided command line (see competitionRequirements.pdf, sec. 4.3):
#
#   NOCERT tracks:  DIR/run.sh BENCHNAME
#   CERT tracks:    DIR/run.sh BENCHNAME PROOFFILE
#
# BENCHNAME is the .opb/.wbo instance; PROOFFILE the VeriPB proof output path.
# CPU limit comes from TIMELIMIT (or TIMEOUT), seconds. Output is the standard
# PB competition format: `c` comments, `o <obj>` improvements (flushed), exactly
# one `s` line, and `v` lines assigning every variable on SAT/OPTIMUM. AY traps
# SIGTERM and force-flushes the best incumbent within 0.85s (watchdog), well
# before the harness SIGKILL.
set -eu

# ---- Trident entry preset (from entries.toml) ------------------------------
export AY_PB_PARALLEL=auto
# ----------------------------------------------------------------------------

# Use ALL competition cores when the parallel preset is active. NBCORE falls
# back to the machine core count when the competition does not export it. The
# solver applies parallel search ONLY where it is a measured win (decision);
# optimization keeps the sequential full-budget path unless configured.
if [ -z "${NBCORE:-}" ]; then NBCORE=$( (nproc 2>/dev/null) || sysctl -n hw.ncpu 2>/dev/null || echo 1 ); fi
export NBCORE

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
BENCH=${1:?usage: run.sh BENCHNAME [PROOFFILE]}
PROOF=${2:-}
TL=${TIMELIMIT:-${TIMEOUT:-}}

set -- pb solve
# AY's --timeout is milliseconds of WALL time; PB-COMP TIMELIMIT is CPU
# seconds enforced by runsolver across ALL threads. SEQUENTIAL entries
# (AY_PB_PARALLEL=off preset) additionally watch their own process-CPU clock
# (AY_PB_CPU_BUDGET_MS) so that when an auxiliary thread is busy (proof-tap
# serializer, sleepy watchdogs) they stand down — fail-closed, proofs
# committed-or-removed — BEFORE runsolver's SIGTERM. The 2s margin covers the
# final flush; floor of 1s keeps tiny limits sane. The PARALLEL entry must
# NOT self-limit on CPU: its track is wall-clock limited with N busy workers,
# so a TL-derived CPU budget would stop it at ~1/N of its real budget.
if [ -n "${TL}" ]; then
    set -- "$@" --timeout "$(( TL * 1000 ))"
    if [ "${AY_PB_PARALLEL:-off}" = "off" ]; then
        CPU_BUDGET_MS=$(( TL * 1000 - 2000 ))
        if [ "${CPU_BUDGET_MS}" -lt 1000 ]; then CPU_BUDGET_MS=1000; fi
        export AY_PB_CPU_BUDGET_MS="${CPU_BUDGET_MS}"
    fi
fi
if [ -n "${PROOF}" ]; then
    set -- "$@" --proof "${PROOF}"
fi

exec "${DIR}/ay-pb" "$@" "${BENCH}"
