// Copyright 2026 Andrew Yates
// Author: Andrew Yates
// Licensed under the Apache License, Version 2.0

//! `ay scripts` — discover, run, and gate the repo's indexed scripts.
//!
//! The registry is `scripts/index.toml` (public half) plus
//! `scripts/index-internal.toml` (internal half, `!`-excluded from
//! publish/manifest.txt and therefore present only in dev checkouts). Both
//! files share one schema (schema_version, `[[script]]` arrays); names are
//! unique across the pair and every entry validates on load, corpora.toml
//! style. The index is the source of truth; the CLI is a thin validated
//! reader/runner.
//!
//! 0.1.0 verbs: `list`, `show`, `run`, `check`, `readme`. The `check` verb
//! also carries the `sync-manifest` gate mode (diff-check of the generated
//! exclusion block in publish/manifest.txt); a `sync-manifest --write` verb
//! lands post-0.1.0 — the manifest is never auto-written.

use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command as ProcCommand;

use anyhow::{anyhow, bail, Context, Result};
use clap::{Args, Subcommand, ValueEnum};
use serde::{Deserialize, Serialize};

/// Repo-relative path of the public index (ships).
const PUBLIC_INDEX: &str = "scripts/index.toml";
/// Repo-relative path of the internal index (never ships).
const INTERNAL_INDEX: &str = "scripts/index-internal.toml";
/// Repo-relative path of the generated public catalog.
const README_PATH: &str = "scripts/README.md";
/// Repo-relative path of the publication allowlist manifest.
const MANIFEST_PATH: &str = "publish/manifest.txt";
/// Marker opening the generated exclusion block in the manifest.
const GENERATED_BEGIN: &str = "# BEGIN generated by ay scripts sync-manifest";
/// Marker closing the generated exclusion block in the manifest.
const GENERATED_END: &str = "# END generated";

/// Closed set of first segments for the dotted `group` taxonomy.
const GROUP_ROOTS: &[&str] = &[
    "bench",
    "compare",
    "corpus",
    "gate",
    "fuzz",
    "audit",
    "build",
    "competition",
    "report",
    "oracle",
    "lib",
    "test",
    "hook",
    "dev",
    "smoke",
    "portal",
    "campaign",
    "archive",
    "evidence",
    "compat",
];

/// Group-level long help, attached to the `Scripts` variant in main.rs.
pub(crate) const GROUP_LONG_ABOUT: &str = "Discover, run, and gate the repo's indexed scripts\n\n\
Scripts wrap external tools and competition harnesses; when logic is core\n\
it lives in Rust instead (see `ay bench sat-delta`). The index —\n\
scripts/index.toml, plus scripts/index-internal.toml in dev checkouts — is\n\
the source of truth for what exists, what it wraps, what fronts it, and\n\
what ships. When an entry names a fronting subcommand, prefer the\n\
subcommand.\n\n\
`sync-manifest --write` (regenerating the manifest exclusion block) lands\n\
post-0.1.0; `check` performs its diff-check gate mode today and the\n\
manifest is only ever rewritten by a human.";

#[derive(Subcommand)]
pub(crate) enum ScriptsCommand {
    /// List indexed scripts
    List(ListArgs),
    /// Print one script's full index entry
    Show(ShowArgs),
    /// Run an indexed script with the standard environment
    Run(RunArgs),
    /// Verify index / tree / publication consistency
    Check(CheckArgs),
    /// Render scripts/README.md from the public index
    Readme(ReadmeArgs),
}

#[derive(Args)]
#[command(long_about = "List indexed scripts\n\n\
Columns: NAME, GROUP, LANG, PUBLISH, STATUS, CLI, SUMMARY. The CLI column\n\
names the subcommand that fronts the script; prefer it over direct\n\
invocation. Reads scripts/index.toml and, when present,\n\
scripts/index-internal.toml.")]
pub(crate) struct ListArgs {
    /// Only entries whose dotted group matches the prefix (e.g. bench.sat)
    #[arg(long, value_name = "PREFIX")]
    group: Option<String>,
    /// Only public or internal entries
    #[arg(long, value_name = "WHICH")]
    publish: Option<Publish>,
    /// Only this status
    #[arg(long, value_name = "WHICH")]
    status: Option<Status>,
    /// Only scripts that declare this tool in `tools`
    #[arg(long, value_name = "NAME")]
    tool: Option<String>,
    /// Emit the filtered entries as JSON
    #[arg(long)]
    json: bool,
}

#[derive(Args)]
#[command(long_about = "Print one script's full index entry\n\n\
The entry, the resolved interpreter, declared tools with their resolved\n\
paths, required sibling scripts, docs pointer, and fronting subcommand.")]
pub(crate) struct ShowArgs {
    /// Script index name (e.g. chccomp-harness)
    name: String,
    /// Emit the entry as JSON
    #[arg(long)]
    json: bool,
}

#[derive(Args)]
#[command(long_about = "Run an indexed script with the standard environment\n\n\
Resolves the interpreter from the entry's lang, runs from the repo root,\n\
and exports AY_CLI (this binary's path), AY_REPO_ROOT, and AY_TOOL_<NAME>\n\
for every tool the entry declares (resolved first; missing tools fail fast\n\
with the matching `ay tool install` line). Entries with entrypoint library,\n\
template, or test are refused; status=broken entries are refused;\n\
deprecated and archival entries warn. Scripts remain directly runnable\n\
without this wrapper — `run` only adds resolution and environment.")]
pub(crate) struct RunArgs {
    /// Script index name
    name: String,
    /// Print the exact command line and env, do not execute
    #[arg(long)]
    dry_run: bool,
    /// Skip tool preflight resolution
    #[arg(long)]
    no_tools: bool,
    /// Arguments passed through to the script after `--`
    #[arg(last = true, value_name = "ARGS")]
    args: Vec<String>,
}

#[derive(Args)]
#[command(long_about = "Verify index / tree / publication consistency\n\n\
Checks, fail-closed:\n  \
1. every entry's path exists and is git-tracked; every tracked script\n     \
under scripts/ has an index entry (public or internal) or matches a\n     \
[policy].exempt glob; names are unique across both files\n  \
2. publish agrees with reality: the generated exclusion block in\n     \
publish/manifest.txt (between the BEGIN/END markers) matches the block\n     \
derived from the internal index, including the\n     \
!scripts/index-internal.toml line — diff printed on mismatch, the\n     \
manifest is never written\n  \
3. every internal entry's path is covered by a manifest exclusion or\n     \
lives under a non-allowlisted dir; public entries survive the manifest\n\n\
Header, tool-recipe, and shipped-reference checks (design items 2/4/5)\n\
land with a later wave. Exit code 1 when any finding is reported.")]
pub(crate) struct CheckArgs {
    /// Emit findings as JSON
    #[arg(long)]
    json: bool,
}

#[derive(Args)]
#[command(long_about = "Render scripts/README.md from the public index\n\n\
Grouped tables of public entries, marked as generated. Default prints and\n\
exits 1 if the checked-in file is stale (gate mode); --write rewrites it.")]
pub(crate) struct ReadmeArgs {
    /// Rewrite scripts/README.md in place
    #[arg(long)]
    write: bool,
}

// ---------------------------------------------------------------------------
// Registry schema
// ---------------------------------------------------------------------------

#[derive(Debug, Serialize, Deserialize)]
struct Index {
    schema_version: u32,
    #[serde(default)]
    policy: Policy,
    #[serde(default, rename = "script")]
    scripts: Vec<ScriptEntry>,
}

#[derive(Debug, Default, Serialize, Deserialize)]
struct Policy {
    #[serde(default)]
    exempt: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ScriptEntry {
    name: String,
    path: String,
    lang: Lang,
    group: String,
    summary: String,
    publish: Publish,
    #[serde(default)]
    status: Status,
    #[serde(default)]
    entrypoint: Entrypoint,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    tools: Vec<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    requires: Vec<String>,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    cli: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    cli_note: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    docs: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    replaced_by: String,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    waiver: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ValueEnum)]
#[serde(rename_all = "lowercase")]
enum Lang {
    Python,
    Sh,
    Bash,
    Zsh,
}

impl Lang {
    fn label(&self) -> &'static str {
        match self {
            Lang::Python => "python",
            Lang::Sh => "sh",
            Lang::Bash => "bash",
            Lang::Zsh => "zsh",
        }
    }

    /// Interpreter program `scripts run` execs.
    fn interpreter(&self) -> &'static str {
        match self {
            Lang::Python => "python3",
            Lang::Sh => "sh",
            Lang::Bash => "bash",
            Lang::Zsh => "zsh",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ValueEnum)]
#[serde(rename_all = "lowercase")]
enum Publish {
    Public,
    Internal,
}

impl Publish {
    fn label(&self) -> &'static str {
        match self {
            Publish::Public => "public",
            Publish::Internal => "internal",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, ValueEnum, Default)]
#[serde(rename_all = "lowercase")]
enum Status {
    #[default]
    Active,
    Deprecated,
    Archival,
    Broken,
    Placeholder,
}

impl Status {
    fn label(&self) -> &'static str {
        match self {
            Status::Active => "active",
            Status::Deprecated => "deprecated",
            Status::Archival => "archival",
            Status::Broken => "broken",
            Status::Placeholder => "placeholder",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
enum Entrypoint {
    #[default]
    Cli,
    Library,
    Hook,
    Convention,
    Template,
    Test,
}

impl Entrypoint {
    fn label(&self) -> &'static str {
        match self {
            Entrypoint::Cli => "cli",
            Entrypoint::Library => "library",
            Entrypoint::Hook => "hook",
            Entrypoint::Convention => "convention",
            Entrypoint::Template => "template",
            Entrypoint::Test => "test",
        }
    }
}

fn is_kebab(s: &str) -> bool {
    !s.is_empty()
        && !s.starts_with('-')
        && !s.ends_with('-')
        && !s.contains("--")
        && s.chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

impl ScriptEntry {
    fn validate(&self) -> Result<()> {
        if !is_kebab(&self.name) {
            bail!("name `{}` is not kebab-case", self.name);
        }
        if self.path.is_empty() || self.path.starts_with('/') || self.path.contains("..") {
            bail!("path `{}` must be repo-relative", self.path);
        }
        let mut segments = self.group.split('.');
        let root = segments.next().unwrap_or("");
        if !GROUP_ROOTS.contains(&root) {
            bail!(
                "group `{}`: first segment `{}` is not in the closed taxonomy ({})",
                self.group,
                root,
                GROUP_ROOTS.join("|")
            );
        }
        for seg in self.group.split('.') {
            if !is_kebab(seg) {
                bail!("group `{}`: bad segment `{}`", self.group, seg);
            }
        }
        if self.summary.is_empty() {
            bail!("summary must not be empty");
        }
        if self.entrypoint == Entrypoint::Cli && self.cli.is_empty() && self.cli_note.is_empty() {
            bail!("entrypoint=cli with cli=\"\" requires a cli_note explaining why no subcommand fronts it");
        }
        if !self.replaced_by.is_empty() && self.status != Status::Deprecated {
            bail!("replaced_by is set but status is not deprecated");
        }
        Ok(())
    }
}

impl Index {
    fn load(path: &Path, expected: Publish) -> Result<Self> {
        let body =
            fs::read_to_string(path).with_context(|| format!("read index {}", path.display()))?;
        let index: Index =
            toml::from_str(&body).with_context(|| format!("parse index {}", path.display()))?;
        if index.schema_version != 1 {
            bail!(
                "index {}: unsupported schema_version {} (expected 1)",
                path.display(),
                index.schema_version
            );
        }
        for entry in &index.scripts {
            entry
                .validate()
                .with_context(|| format!("script {} in {}", entry.name, path.display()))?;
            if entry.publish != expected {
                bail!(
                    "index {}: script {} has publish={} but this is the {} index",
                    path.display(),
                    entry.name,
                    entry.publish.label(),
                    expected.label()
                );
            }
        }
        Ok(index)
    }
}

/// Both index halves, loaded and cross-validated.
struct Loaded {
    public: Index,
    /// `None` in public snapshots, where the internal index never ships.
    internal: Option<Index>,
}

impl Loaded {
    fn load(root: &Path) -> Result<Self> {
        let public = Index::load(&root.join(PUBLIC_INDEX), Publish::Public)?;
        let internal_path = root.join(INTERNAL_INDEX);
        let internal = if internal_path.is_file() {
            Some(Index::load(&internal_path, Publish::Internal)?)
        } else {
            None
        };
        let loaded = Loaded { public, internal };
        validate_cross(&loaded.public, loaded.internal.as_ref())?;
        Ok(loaded)
    }

    fn entries(&self) -> impl Iterator<Item = &ScriptEntry> {
        self.public
            .scripts
            .iter()
            .chain(self.internal.iter().flat_map(|i| i.scripts.iter()))
    }

    fn find(&self, name: &str) -> Result<&ScriptEntry> {
        self.entries().find(|e| e.name == name).ok_or_else(|| {
            anyhow!("script `{name}` not found in the index (see `ay scripts list`)")
        })
    }
}

/// Cross-file invariants: names unique across both halves, `requires`
/// targets resolve.
fn validate_cross(public: &Index, internal: Option<&Index>) -> Result<()> {
    let mut names = BTreeSet::new();
    let mut paths = BTreeSet::new();
    let all: Vec<&ScriptEntry> = public
        .scripts
        .iter()
        .chain(internal.iter().flat_map(|i| i.scripts.iter()))
        .collect();
    for entry in &all {
        if !names.insert(entry.name.as_str()) {
            bail!(
                "duplicate script name `{}` across the index files",
                entry.name
            );
        }
        if !paths.insert(entry.path.as_str()) {
            bail!(
                "duplicate script path `{}` across the index files",
                entry.path
            );
        }
    }
    for entry in &all {
        for req in &entry.requires {
            if !names.contains(req.as_str()) {
                bail!(
                    "script {}: requires `{}` which has no index entry",
                    entry.name,
                    req
                );
            }
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Repo helpers
// ---------------------------------------------------------------------------

/// Walk up from the current directory to the checkout containing the index.
fn repo_root() -> Result<PathBuf> {
    let mut dir = env::current_dir().context("determine current directory")?;
    loop {
        if dir.join(PUBLIC_INDEX).is_file() {
            return Ok(dir);
        }
        if !dir.pop() {
            bail!("could not locate {PUBLIC_INDEX} above the current directory; run inside the ay repo");
        }
    }
}

/// Map of tracked path -> git mode string (e.g. "100755"), from
/// `git ls-files -s`.
fn git_tracked(root: &Path) -> Result<BTreeMap<String, String>> {
    let out = ProcCommand::new("git")
        .args(["ls-files", "-s", "-z"])
        .current_dir(root)
        .output()
        .context("run `git ls-files -s` (is git installed?)")?;
    if !out.status.success() {
        bail!(
            "`git ls-files` failed in {}: {}",
            root.display(),
            String::from_utf8_lossy(&out.stderr).trim()
        );
    }
    let mut tracked = BTreeMap::new();
    for record in out.stdout.split(|&b| b == 0) {
        if record.is_empty() {
            continue;
        }
        let record = String::from_utf8_lossy(record);
        // Format: "<mode> <sha> <stage>\t<path>"
        let Some((meta, path)) = record.split_once('\t') else {
            continue;
        };
        let mode = meta.split(' ').next().unwrap_or("").to_string();
        tracked.insert(path.to_string(), mode);
    }
    Ok(tracked)
}

/// Env var name for a declared tool: uppercased, non-alphanumeric -> `_`.
fn tool_env_var(name: &str) -> String {
    let mangled: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    format!("AY_TOOL_{mangled}")
}

/// Resolve a declared tool: `$AY_TOOL_<NAME>` override first, then `$PATH`.
fn resolve_tool(name: &str) -> Option<PathBuf> {
    if let Some(over) = env::var_os(tool_env_var(name)) {
        let p = PathBuf::from(over);
        if p.is_file() {
            return Some(p);
        }
    }
    let path_var = env::var_os("PATH")?;
    for dir in env::split_paths(&path_var) {
        let candidate = dir.join(name);
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

/// Simple glob: `*` matches any run of characters except `/`; patterns are
/// matched segment-wise and cover a path when they match a leading prefix of
/// its segments (so `proofs/evidence` covers `proofs/evidence/x/y.sh`).
fn pattern_covers(pattern: &str, path: &str) -> bool {
    let pat_segs: Vec<&str> = pattern.split('/').collect();
    let path_segs: Vec<&str> = path.split('/').collect();
    let mut pi = 0usize;
    for (i, pseg) in pat_segs.iter().enumerate() {
        if *pseg == "**" {
            // `**` swallows the rest of the path.
            return true;
        }
        match path_segs.get(i) {
            Some(sseg) if segment_match(pseg, sseg) => pi = i + 1,
            _ => return false,
        }
    }
    // All pattern segments matched a prefix of the path.
    pi == pat_segs.len()
}

/// Match one path segment against a pattern segment with `*` wildcards.
fn segment_match(pattern: &str, segment: &str) -> bool {
    // Iterative greedy glob restricted to one segment.
    let (p, s): (Vec<char>, Vec<char>) = (pattern.chars().collect(), segment.chars().collect());
    let (mut pi, mut si) = (0usize, 0usize);
    let (mut star, mut mark) = (None::<usize>, 0usize);
    while si < s.len() {
        if pi < p.len() && (p[pi] == s[si]) {
            pi += 1;
            si += 1;
        } else if pi < p.len() && p[pi] == '*' {
            star = Some(pi);
            mark = si;
            pi += 1;
        } else if let Some(sp) = star {
            pi = sp + 1;
            mark += 1;
            si = mark;
        } else {
            return false;
        }
    }
    while pi < p.len() && p[pi] == '*' {
        pi += 1;
    }
    pi == p.len()
}

// ---------------------------------------------------------------------------
// publish/manifest.txt model
// ---------------------------------------------------------------------------

/// Parse of the publication manifest as far as `scripts check` needs it.
struct PublishManifest {
    /// Allowlisted top-level names (dirs or files), the non-`!` lines.
    allow: Vec<String>,
    /// `!` exclusions outside the generated block, without the leading `!`.
    hand_exclusions: Vec<String>,
    /// Raw lines between the BEGIN/END markers (markers excluded).
    /// `None` when the markers are absent.
    generated: Option<Vec<String>>,
}

impl PublishManifest {
    fn parse(path: &Path) -> Result<Self> {
        let body = fs::read_to_string(path)
            .with_context(|| format!("read manifest {}", path.display()))?;
        let mut allow = Vec::new();
        let mut hand_exclusions = Vec::new();
        let mut generated: Option<Vec<String>> = None;
        let mut in_generated = false;
        for line in body.lines() {
            let trimmed = line.trim();
            if trimmed == GENERATED_BEGIN {
                if generated.is_some() {
                    bail!("{}: duplicate `{}` marker", path.display(), GENERATED_BEGIN);
                }
                generated = Some(Vec::new());
                in_generated = true;
                continue;
            }
            if trimmed == GENERATED_END {
                if !in_generated {
                    bail!(
                        "{}: `{}` marker without a BEGIN",
                        path.display(),
                        GENERATED_END
                    );
                }
                in_generated = false;
                continue;
            }
            if in_generated {
                generated
                    .as_mut()
                    .expect("in generated block")
                    .push(line.to_string());
                continue;
            }
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }
            if let Some(excl) = trimmed.strip_prefix('!') {
                hand_exclusions.push(excl.to_string());
            } else {
                allow.push(trimmed.to_string());
            }
        }
        if in_generated {
            bail!(
                "{}: unterminated `{}` block",
                path.display(),
                GENERATED_BEGIN
            );
        }
        Ok(PublishManifest {
            allow,
            hand_exclusions,
            generated,
        })
    }

    /// Every exclusion pattern, generated block included.
    fn all_exclusions(&self) -> Vec<String> {
        let mut all = self.hand_exclusions.clone();
        if let Some(generated) = &self.generated {
            for line in generated {
                if let Some(excl) = line.trim().strip_prefix('!') {
                    all.push(excl.to_string());
                }
            }
        }
        all
    }

    /// Is `path` under an allowlisted top-level entry?
    fn allowlisted(&self, path: &str) -> bool {
        let top = path.split('/').next().unwrap_or(path);
        self.allow.iter().any(|a| a == top || a == path)
    }

    fn excluded(&self, path: &str) -> bool {
        self.all_exclusions()
            .iter()
            .any(|e| pattern_covers(e, path))
    }
}

/// The exclusion block `sync-manifest` derives from the internal index:
/// the internal index itself, then one `!` line per internal entry whose
/// path sits under an allowlisted directory and is not already covered by a
/// hand-maintained exclusion. Order follows the internal index file.
fn expected_generated_block(
    internal: &[ScriptEntry],
    hand_exclusions: &[String],
    manifest: &PublishManifest,
) -> Vec<String> {
    let mut lines = vec![format!("!{INTERNAL_INDEX}")];
    for entry in internal {
        if !manifest.allowlisted(&entry.path) {
            continue; // non-allowlisted dirs (docs/, reports/, tools/) never ship
        }
        if hand_exclusions
            .iter()
            .any(|e| pattern_covers(e, &entry.path))
        {
            continue; // already covered outside the generated block
        }
        lines.push(format!("!{}", entry.path));
    }
    lines
}

// ---------------------------------------------------------------------------
// Verbs
// ---------------------------------------------------------------------------

pub(crate) fn run(cmd: ScriptsCommand) -> Result<i32> {
    match cmd {
        ScriptsCommand::List(args) => run_list(args),
        ScriptsCommand::Show(args) => run_show(args),
        ScriptsCommand::Run(args) => run_run(args),
        ScriptsCommand::Check(args) => run_check(args),
        ScriptsCommand::Readme(args) => run_readme(args),
    }
}

fn run_list(args: ListArgs) -> Result<i32> {
    let loaded = Loaded::load(&repo_root()?)?;
    let group_matches = |group: &str| -> bool {
        match &args.group {
            None => true,
            Some(prefix) => group == prefix || group.starts_with(&format!("{prefix}.")),
        }
    };
    let entries: Vec<&ScriptEntry> = loaded
        .entries()
        .filter(|e| group_matches(&e.group))
        .filter(|e| args.publish.map_or(true, |p| e.publish == p))
        .filter(|e| args.status.map_or(true, |s| e.status == s))
        .filter(|e| {
            args.tool
                .as_ref()
                .map_or(true, |t| e.tools.iter().any(|x| x == t))
        })
        .collect();
    if args.json {
        println!("{}", serde_json::to_string_pretty(&entries)?);
        return Ok(0);
    }
    println!(
        "{:<28} {:<20} {:<7} {:<9} {:<11} {:<38} SUMMARY",
        "NAME", "GROUP", "LANG", "PUBLISH", "STATUS", "CLI"
    );
    for e in entries {
        let cli = if e.cli.is_empty() {
            "-"
        } else {
            e.cli.as_str()
        };
        println!(
            "{:<28} {:<20} {:<7} {:<9} {:<11} {:<38} {}",
            e.name,
            e.group,
            e.lang.label(),
            e.publish.label(),
            e.status.label(),
            cli,
            e.summary
        );
    }
    Ok(0)
}

fn run_show(args: ShowArgs) -> Result<i32> {
    let loaded = Loaded::load(&repo_root()?)?;
    let entry = loaded.find(&args.name)?;
    if args.json {
        println!("{}", serde_json::to_string_pretty(entry)?);
        return Ok(0);
    }
    let dash = |s: &str| {
        if s.is_empty() {
            "-".to_string()
        } else {
            s.to_string()
        }
    };
    println!("name:        {}", entry.name);
    println!("path:        {}", entry.path);
    println!(
        "lang:        {} (interpreter: {})",
        entry.lang.label(),
        entry.lang.interpreter()
    );
    println!("group:       {}", entry.group);
    println!("publish:     {}", entry.publish.label());
    println!("status:      {}", entry.status.label());
    println!("entrypoint:  {}", entry.entrypoint.label());
    println!("summary:     {}", entry.summary);
    println!("cli:         {}", dash(&entry.cli));
    println!("cli_note:    {}", dash(&entry.cli_note));
    println!("docs:        {}", dash(&entry.docs));
    println!("replaced_by: {}", dash(&entry.replaced_by));
    println!("waiver:      {}", dash(&entry.waiver));
    if entry.tools.is_empty() {
        println!("tools:       -");
    } else {
        let rendered: Vec<String> = entry
            .tools
            .iter()
            .map(|t| match resolve_tool(t) {
                Some(p) => format!("{t} -> {}", p.display()),
                None => format!("{t} (not found; ${} or $PATH)", tool_env_var(t)),
            })
            .collect();
        println!("tools:       {}", rendered.join(", "));
    }
    println!(
        "requires:    {}",
        if entry.requires.is_empty() {
            "-".to_string()
        } else {
            entry.requires.join(", ")
        }
    );
    Ok(0)
}

fn run_run(args: RunArgs) -> Result<i32> {
    let root = repo_root()?;
    let loaded = Loaded::load(&root)?;
    let entry = loaded.find(&args.name)?;
    match entry.entrypoint {
        Entrypoint::Library | Entrypoint::Template | Entrypoint::Test => bail!(
            "script `{}` has entrypoint={}; it is not directly runnable via `scripts run`",
            entry.name,
            entry.entrypoint.label()
        ),
        _ => {}
    }
    if entry.status == Status::Broken {
        bail!(
            "script `{}` is status=broken; refusing to run it ({})",
            entry.name,
            entry.summary
        );
    }
    if matches!(entry.status, Status::Deprecated | Status::Archival) {
        eprintln!(
            "warning: script `{}` is status={}{}",
            entry.name,
            entry.status.label(),
            if entry.replaced_by.is_empty() {
                String::new()
            } else {
                format!("; replaced by `{}`", entry.replaced_by)
            }
        );
    }

    let mut env_pairs: Vec<(String, String)> = Vec::new();
    let ay_cli = env::current_exe().context("resolve the running ay binary")?;
    env_pairs.push(("AY_CLI".to_string(), ay_cli.display().to_string()));
    env_pairs.push(("AY_REPO_ROOT".to_string(), root.display().to_string()));
    if !args.no_tools {
        for tool in &entry.tools {
            match resolve_tool(tool) {
                Some(path) => {
                    env_pairs.push((tool_env_var(tool), path.display().to_string()));
                }
                None => bail!(
                    "tool `{tool}` (declared by `{}`) not found via ${} or $PATH; \
                     install it (e.g. `ay tool install {tool}`) or rerun with --no-tools",
                    entry.name,
                    tool_env_var(tool)
                ),
            }
        }
    }

    let interpreter = entry.lang.interpreter();
    if args.dry_run {
        for (k, v) in &env_pairs {
            println!("{k}={v}");
        }
        let mut argv = vec![interpreter.to_string(), entry.path.clone()];
        argv.extend(args.args.iter().cloned());
        println!("cd {} && {}", root.display(), argv.join(" "));
        return Ok(0);
    }

    let mut cmd = ProcCommand::new(interpreter);
    cmd.arg(&entry.path).args(&args.args).current_dir(&root);
    for (k, v) in &env_pairs {
        cmd.env(k, v);
    }
    let status = cmd
        .status()
        .with_context(|| format!("exec {interpreter} {}", entry.path))?;
    Ok(status.code().unwrap_or(1))
}

/// One `scripts check` violation.
#[derive(Debug)]
struct Finding {
    check: &'static str,
    message: String,
}

fn run_check(args: CheckArgs) -> Result<i32> {
    let root = repo_root()?;
    let loaded = Loaded::load(&root)?;
    let tracked = git_tracked(&root)?;
    let mut findings: Vec<Finding> = Vec::new();

    // (a) every index path exists and is tracked.
    for entry in loaded.entries() {
        let dir_prefix = format!("{}/", entry.path);
        let is_tracked =
            tracked.contains_key(&entry.path) || tracked.keys().any(|k| k.starts_with(&dir_prefix));
        if !is_tracked {
            findings.push(Finding {
                check: "index-path",
                message: format!(
                    "entry `{}`: path {} is not git-tracked",
                    entry.name, entry.path
                ),
            });
        } else if !root.join(&entry.path).exists() {
            findings.push(Finding {
                check: "index-path",
                message: format!(
                    "entry `{}`: path {} is tracked but missing from the working tree",
                    entry.name, entry.path
                ),
            });
        }
    }

    // (b) every tracked script under scripts/ is indexed (public OR internal).
    let indexed_paths: BTreeSet<&str> = loaded.entries().map(|e| e.path.as_str()).collect();
    for path in unindexed_under_scripts(&tracked, &indexed_paths, &loaded.public.policy.exempt) {
        findings.push(Finding {
            check: "unindexed",
            message: format!("{path} is a tracked script with no index entry (public or internal)"),
        });
    }

    // (c) generated manifest block matches (diff-check only; never write).
    let manifest_path = root.join(MANIFEST_PATH);
    if manifest_path.is_file() {
        let manifest = PublishManifest::parse(&manifest_path)?;
        match (&manifest.generated, &loaded.internal) {
            (None, _) => findings.push(Finding {
                check: "manifest-block",
                message: format!(
                    "{MANIFEST_PATH}: `{GENERATED_BEGIN}` / `{GENERATED_END}` markers not found"
                ),
            }),
            (Some(actual), Some(internal)) => {
                let expected = expected_generated_block(
                    &internal.scripts,
                    &manifest.hand_exclusions,
                    &manifest,
                );
                if *actual != expected {
                    findings.push(Finding {
                        check: "manifest-block",
                        message: render_block_diff(actual, &expected),
                    });
                }
            }
            (Some(_), None) => findings.push(Finding {
                check: "manifest-block",
                message: format!(
                    "{INTERNAL_INDEX} is missing; cannot verify the generated manifest block"
                ),
            }),
        }

        // (d) publication coverage both directions.
        if let Some(internal) = &loaded.internal {
            for entry in &internal.scripts {
                if manifest.allowlisted(&entry.path) && !manifest.excluded(&entry.path) {
                    findings.push(Finding {
                        check: "internal-coverage",
                        message: format!(
                            "internal entry `{}`: path {} is under an allowlisted dir but matches no `!` exclusion — it would ship",
                            entry.name, entry.path
                        ),
                    });
                }
            }
        }
        for entry in &loaded.public.scripts {
            if manifest.excluded(&entry.path) {
                findings.push(Finding {
                    check: "public-coverage",
                    message: format!(
                        "public entry `{}`: path {} is excluded by the manifest — it would not ship",
                        entry.name, entry.path
                    ),
                });
            } else if !manifest.allowlisted(&entry.path) {
                findings.push(Finding {
                    check: "public-coverage",
                    message: format!(
                        "public entry `{}`: path {} is not under an allowlisted dir — it would not ship",
                        entry.name, entry.path
                    ),
                });
            }
        }
    } else {
        // Public snapshots carry no publish/ dir; nothing to verify there.
        if loaded.internal.is_some() {
            findings.push(Finding {
                check: "manifest-block",
                message: format!("{MANIFEST_PATH} not found but {INTERNAL_INDEX} is present"),
            });
        }
    }

    if args.json {
        let rendered: Vec<serde_json::Value> = findings
            .iter()
            .map(|f| serde_json::json!({ "check": f.check, "message": f.message }))
            .collect();
        println!(
            "{}",
            serde_json::to_string_pretty(&serde_json::json!({ "findings": rendered }))?
        );
    } else if findings.is_empty() {
        println!(
            "scripts check: OK ({} entries indexed)",
            loaded.entries().count()
        );
    } else {
        println!("scripts check: {} finding(s)", findings.len());
        for f in &findings {
            println!("  [{}] {}", f.check, f.message);
        }
    }
    Ok(if findings.is_empty() { 0 } else { 1 })
}

/// Human-readable diff between the checked-in generated block and the block
/// derived from the internal index.
fn render_block_diff(actual: &[String], expected: &[String]) -> String {
    let actual_set: BTreeSet<&String> = actual.iter().collect();
    let expected_set: BTreeSet<&String> = expected.iter().collect();
    let mut out = String::from(
        "generated exclusion block in publish/manifest.txt does not match the internal index\n  (run a human-reviewed update; `ay scripts check` never writes the manifest)",
    );
    for line in actual {
        if !expected_set.contains(line) {
            out.push_str(&format!("\n  - {line}"));
        }
    }
    for line in expected {
        if !actual_set.contains(line) {
            out.push_str(&format!("\n  + {line}"));
        }
    }
    if actual_set == expected_set {
        out.push_str("\n  (same lines, different order; expected order:)");
        for line in expected {
            out.push_str(&format!("\n    {line}"));
        }
    }
    out
}

/// File extensions that are never scripts even when executable.
const DATA_EXTS: &[&str] = &[
    "md", "json", "toml", "txt", "csv", "tsv", "yaml", "yml", "lock", "set",
];
/// File extensions that are always scripts.
const SCRIPT_EXTS: &[&str] = &["py", "sh", "bash", "zsh"];
/// Index-owned files under scripts/ that need no entry.
const INDEX_FILES: &[&str] = &[PUBLIC_INDEX, INTERNAL_INDEX, README_PATH];

/// Tracked scripts under scripts/ with no index entry: the fail-closed side
/// of the bijection. Pure so the logic is unit-testable.
fn unindexed_under_scripts(
    tracked: &BTreeMap<String, String>,
    indexed_paths: &BTreeSet<&str>,
    exempt: &[String],
) -> Vec<String> {
    let mut missing = Vec::new();
    for (path, mode) in tracked {
        if !path.starts_with("scripts/") {
            continue;
        }
        if INDEX_FILES.contains(&path.as_str()) {
            continue;
        }
        let ext = Path::new(path)
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("");
        let is_script = if SCRIPT_EXTS.contains(&ext) {
            true
        } else if DATA_EXTS.contains(&ext) {
            false
        } else {
            mode == "100755"
        };
        if !is_script {
            continue;
        }
        if exempt.iter().any(|g| pattern_covers(g, path)) {
            continue;
        }
        let covered = indexed_paths.contains(path.as_str())
            || indexed_paths
                .iter()
                .any(|p| path.starts_with(&format!("{p}/")));
        if !covered {
            missing.push(path.clone());
        }
    }
    missing
}

fn run_readme(args: ReadmeArgs) -> Result<i32> {
    let root = repo_root()?;
    let loaded = Loaded::load(&root)?;
    let rendered = render_readme(&loaded.public.scripts);
    let readme_path = root.join(README_PATH);
    if args.write {
        fs::write(&readme_path, &rendered)
            .with_context(|| format!("write {}", readme_path.display()))?;
        println!(
            "wrote {README_PATH} ({} public entries)",
            loaded.public.scripts.len()
        );
        return Ok(0);
    }
    print!("{rendered}");
    let current = fs::read_to_string(&readme_path).unwrap_or_default();
    if current != rendered {
        eprintln!("{README_PATH} is stale; run `ay scripts readme --write`");
        return Ok(1);
    }
    Ok(0)
}

/// Deterministic render of scripts/README.md from the public index: one
/// table per top-level group, groups and rows sorted.
fn render_readme(public: &[ScriptEntry]) -> String {
    let mut by_root: BTreeMap<&str, Vec<&ScriptEntry>> = BTreeMap::new();
    for entry in public {
        let root = entry.group.split('.').next().unwrap_or(&entry.group);
        by_root.entry(root).or_default().push(entry);
    }
    for entries in by_root.values_mut() {
        entries.sort_by(|a, b| (&a.group, &a.name).cmp(&(&b.group, &b.name)));
    }
    let escape = |s: &str| s.replace('|', "\\|");
    let mut out = String::new();
    out.push_str(
        "<!-- GENERATED by `ay scripts readme --write` from scripts/index.toml. Do not edit by hand. -->\n\n",
    );
    out.push_str("# Scripts\n\n");
    out.push_str(
        "Catalog of the repo's public indexed scripts, generated from\n\
         `scripts/index.toml` — the source of truth for what exists, what it\n\
         wraps, what fronts it, and what ships (`ay scripts --help`). When an\n\
         entry names a fronting subcommand (CLI column), prefer the subcommand\n\
         over direct invocation.\n\n\
         Adding functionality? Apply in order:\n\n\
         1. Rust in the binary when the logic is product semantics,\n\
            soundness-relevant, scoring, provenance, or anything shipped code\n\
            depends on for correctness.\n\
         2. An `ay tool` recipe (reference/tools.toml) when the need is a\n\
            pinned external binary at a known path.\n\
         3. An indexed script when wrapping an external tool's workflow,\n\
            gluing an evolving campaign, or preserving archival evidence. A\n\
            script does not exist until its index entry does\n\
            (`ay scripts check` enforces the bijection).\n",
    );
    for (root, entries) in &by_root {
        out.push_str(&format!("\n## {root}\n\n"));
        out.push_str("| Name | Group | Path | Lang | Status | CLI | Summary |\n");
        out.push_str("|---|---|---|---|---|---|---|\n");
        for e in entries {
            let cli = if e.cli.is_empty() {
                "-".to_string()
            } else {
                format!("`{}`", escape(&e.cli))
            };
            out.push_str(&format!(
                "| {} | {} | `{}` | {} | {} | {} | {} |\n",
                e.name,
                e.group,
                escape(&e.path),
                e.lang.label(),
                e.status.label(),
                cli,
                escape(&e.summary)
            ));
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root_for_tests() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../..")
            .canonicalize()
            .expect("canonicalize repo root")
    }

    fn parse_index(body: &str, expected: Publish) -> Result<Index> {
        let index: Index = toml::from_str(body)?;
        for entry in &index.scripts {
            entry.validate()?;
            if entry.publish != expected {
                bail!("publish mismatch");
            }
        }
        Ok(index)
    }

    const MINIMAL: &str = r#"
schema_version = 1

[[script]]
name    = "a-script"
path    = "scripts/a.py"
lang    = "python"
group   = "bench.sat"
summary = "x"
publish = "public"
cli     = "ay bench"
"#;

    #[test]
    fn repo_indexes_parse_and_validate() {
        let root = repo_root_for_tests();
        let loaded = Loaded::load(&root).expect("load repo indexes");
        assert!(!loaded.public.scripts.is_empty(), "public index is empty");
        let internal = loaded
            .internal
            .as_ref()
            .expect("internal index present in dev checkout");
        assert!(!internal.scripts.is_empty(), "internal index is empty");
        assert!(loaded
            .public
            .scripts
            .iter()
            .all(|e| e.publish == Publish::Public));
        assert!(internal
            .scripts
            .iter()
            .all(|e| e.publish == Publish::Internal));
    }

    #[test]
    fn duplicate_names_across_files_rejected() {
        let public = parse_index(MINIMAL, Publish::Public).unwrap();
        let internal_body = MINIMAL
            .replace("publish = \"public\"", "publish = \"internal\"")
            .replace("scripts/a.py", "scripts/b.py");
        let internal = parse_index(&internal_body, Publish::Internal).unwrap();
        let err = validate_cross(&public, Some(&internal)).unwrap_err();
        assert!(err.to_string().contains("duplicate script name"), "{err}");
    }

    #[test]
    fn taxonomy_root_is_a_closed_set() {
        let body = MINIMAL.replace("bench.sat", "bogus.sat");
        let err = parse_index(&body, Publish::Public).unwrap_err();
        assert!(err.to_string().contains("closed taxonomy"), "{err}");
        // Every root used by the checked-in indexes is in the closed set
        // (Index::load enforces it; loading is the assertion).
        let root = repo_root_for_tests();
        Loaded::load(&root).expect("checked-in groups within taxonomy");
    }

    #[test]
    fn cli_entrypoint_requires_cli_or_note() {
        let body = MINIMAL.replace("cli     = \"ay bench\"", "");
        let err = parse_index(&body, Publish::Public).unwrap_err();
        assert!(err.to_string().contains("cli_note"), "{err}");
    }

    #[test]
    fn check_detects_unindexed_scripts() {
        let mut tracked = BTreeMap::new();
        tracked.insert("scripts/rogue.py".to_string(), "100644".to_string());
        tracked.insert("scripts/hook".to_string(), "100755".to_string());
        tracked.insert("scripts/README.md".to_string(), "100644".to_string());
        tracked.insert("scripts/data.json".to_string(), "100755".to_string());
        tracked.insert("scripts/exempted.py".to_string(), "100644".to_string());
        tracked.insert("scripts/indexed.sh".to_string(), "100644".to_string());
        tracked.insert("elsewhere/x.py".to_string(), "100644".to_string());
        let mut indexed = BTreeSet::new();
        indexed.insert("scripts/indexed.sh");
        let exempt = vec!["scripts/exempted.py".to_string()];
        let missing = unindexed_under_scripts(&tracked, &indexed, &exempt);
        assert_eq!(
            missing,
            vec!["scripts/hook".to_string(), "scripts/rogue.py".to_string()]
        );
    }

    #[test]
    fn manifest_generated_block_matches_internal_index() {
        let root = repo_root_for_tests();
        let loaded = Loaded::load(&root).expect("load repo indexes");
        let internal = loaded.internal.as_ref().expect("internal index");
        let manifest = PublishManifest::parse(&root.join(MANIFEST_PATH)).expect("parse manifest");
        let actual = manifest
            .generated
            .as_ref()
            .expect("generated block markers present in publish/manifest.txt");
        let expected =
            expected_generated_block(&internal.scripts, &manifest.hand_exclusions, &manifest);
        assert_eq!(
            actual, &expected,
            "run-order or content drift between index-internal.toml and the manifest block"
        );
    }

    #[test]
    fn checked_in_readme_is_fresh() {
        let root = repo_root_for_tests();
        let loaded = Loaded::load(&root).expect("load repo indexes");
        let rendered = render_readme(&loaded.public.scripts);
        let checked_in =
            fs::read_to_string(root.join(README_PATH)).expect("read scripts/README.md");
        assert_eq!(
            checked_in, rendered,
            "scripts/README.md is stale; run `ay scripts readme --write`"
        );
    }

    #[test]
    fn pattern_covering() {
        assert!(pattern_covers(
            "proofs/evidence",
            "proofs/evidence/pbcomp/x/run_audit.sh"
        ));
        assert!(pattern_covers(
            "scripts/pb_submit.py",
            "scripts/pb_submit.py"
        ));
        assert!(!pattern_covers(
            "scripts/pb_submit.py",
            "scripts/pb_submit.py.bak"
        ));
        assert!(pattern_covers("third_party/**", "third_party/z3/build.sh"));
        assert!(pattern_covers("proofs/2026-*.md", "proofs/2026-01-01-x.md"));
        assert!(!pattern_covers(
            "proofs/2026-*.md",
            "proofs/2025-01-01-x.md"
        ));
    }
}
