[package]
name = "ay-qbf"
description = "Quantified Boolean Formula (QBF) solver for AY"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
ay-sat.workspace = true

[dev-dependencies]
criterion.workspace = true
ntest = "0.9"

[[bench]]
name = "qbf_bench"
harness = false

[lints]
workspace = true
