// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! Strict-mode schema validation for `TheoryLemmaKind::BvBitBlast` and
//! `TheoryLemmaKind::BvBitBlastGate` proof steps.
//!
//! Context (#8820): previously these lemmas were accepted structurally — any
//! non-empty clause passed, so an attacker-controlled proof could forge a
//! BV lemma and obtain UNSAT. This module replaces the non-empty check with
//! schema validation that catches the most common forgery patterns:
//!
//! - Every literal in a bit-blast clause must be Boolean-sorted. Non-Boolean
//!   terms cannot appear in a propositional clause generated by the bit
//!   blaster.
//! - The clause must mention at least one sub-term involving a bitvector
//!   constant, variable, or gate operation — a pure propositional clause
//!   with no BV content is not a bit-blast product.
//! - Annotated same-width gate lemmas must reference the declared operator at
//!   the declared bit-width.
//! - The clause must be fully evaluable by either the bounded Bool/BV checker
//!   or the proof-producing bit-blast checker. The former enumerates every
//!   small assignment; the latter bit-blasts a bounded-width symbolic clause,
//!   requires an LRAT-derived resolution refutation, and replays every emitted
//!   gate and resolution step.
//!
//! Unsupported operators, widths above the proof producer's bound, malformed
//! terms, SAT negations, and unsurfaceable refutations are all rejected.

use ay_core::{
    time::Instant, BvGateType, Constant, Proof, ProofId, ProofStep, Sort, Symbol, TermData, TermId,
    TermStore, TheoryLemmaKind,
};
use ay_sat::ResolutionProofLimits;
use num_traits::ToPrimitive;
use std::collections::{HashMap, HashSet};
use std::time::Duration;

use super::ProofCheckError;
use crate::{
    bv_blast_export::BvBlastValidateLimits,
    bv_blast_solver::{export_bv_blast_proof_expr_with_limits, BvExprProofLimits},
    BvExpr,
};

/// Recognize whether `clause` is a strict-checkable (ungated) bit-blast lemma —
/// i.e. whether [`validate_bv_bitblast`] with no gate annotation would accept it.
///
/// This is the exact inverse of the validator's semantic checks: the
/// proof classifier (`ay-dpll`) calls it to upgrade a `Generic`/trust lemma into
/// the strict-checkable `BvBitBlast` kind ONLY when strict mode will
/// independently re-validate it by exhaustive evaluation or a checked
/// bit-blast/LRAT refutation — so classifier and checker cannot drift. A
/// non-tautological, unsupported, or too-wide clause is rejected.
#[must_use]
pub fn recognize_bv_bitblast(terms: &TermStore, clause: &[TermId]) -> bool {
    validate_bv_bitblast(terms, ProofId(0), clause, None).is_ok()
}

/// Maximum number of lemmas in one proof that may invoke the proof-producing
/// bit-blast/LRAT fallback.  The fallback has a finite per-lemma deadline; this
/// whole-proof cap prevents an untrusted proof from multiplying that deadline
/// by an arbitrary number of individually bounded lemmas.
pub const MAX_PROOF_PRODUCING_BV_LEMMAS_PER_PROOF: usize = 8;

/// Whether validating `clause` can require the proof-producing fallback.
///
/// This is a cheap structural classification only: clauses covered by the
/// exhaustive <=8-assignment-bit evaluator return `false`; wider or otherwise
/// unsupported bounded-evaluator shapes with BV content return `true`.  It does
/// not claim the clause is valid.
#[must_use]
pub fn bv_bitblast_requires_proof_producer(terms: &TermStore, clause: &[TermId]) -> bool {
    if !clause_mentions_bv(terms, clause) {
        return false;
    }
    match collect_bounded_vars(terms, clause) {
        Some(vars) => vars.iter().map(|var| var.bits).sum::<u32>() > MAX_BOUNDED_ASSIGNMENT_BITS,
        None => true,
    }
}

/// Reject a strict proof whose tagged BV lemmas can multiply the bounded
/// proof-producing fallback beyond the whole-proof resource budget.
pub(crate) fn validate_proof_producing_bv_budget(
    proof: &Proof,
    terms: &TermStore,
) -> Result<(), ProofCheckError> {
    let mut count = 0_usize;
    for (index, step) in proof.steps.iter().enumerate() {
        let ProofStep::TheoryLemma { clause, kind, .. } = step else {
            continue;
        };
        if !matches!(
            kind,
            TheoryLemmaKind::BvBitBlast | TheoryLemmaKind::BvBitBlastGate { .. }
        ) || !bv_bitblast_requires_proof_producer(terms, clause)
        {
            continue;
        }
        count += 1;
        if count > MAX_PROOF_PRODUCING_BV_LEMMAS_PER_PROOF {
            return Err(ProofCheckError::InvalidTheoryLemma {
                step: ProofId(index as u32),
                reason: format!(
                    "proof contains more than {} lemmas requiring the bounded \
                     proof-producing BV checker",
                    MAX_PROOF_PRODUCING_BV_LEMMAS_PER_PROOF
                ),
            });
        }
    }
    Ok(())
}

/// Recognize the deliberately narrow `evaluate` fragment used to certify a
/// preprocessing-folded bitvector concat: one unit equality from a closed
/// concat tree to its exact BV constant, with total width at most 64 bits.
///
/// Keeping this separate from [`recognize_bv_bitblast`] avoids widening that
/// rule's bounded symbolic truth-table surface merely to check one closed
/// constant-folding fact.
#[must_use]
pub fn recognize_bv_ground_evaluate(terms: &TermStore, clause: &[TermId]) -> bool {
    validate_bv_ground_evaluate(terms, ProofId(0), clause, 0, &[]).is_ok()
}

/// Strictly validate the Carcara `evaluate` shape emitted for folded BV
/// concats. This is intentionally not a general evaluator: no variables,
/// non-concat operators, premises, arguments, or widths above 64 are admitted.
pub(crate) fn validate_bv_ground_evaluate(
    terms: &TermStore,
    step_id: ProofId,
    clause: &[TermId],
    premise_count: usize,
    args: &[TermId],
) -> Result<(), ProofCheckError> {
    let invalid = |reason: &str| ProofCheckError::InvalidTheoryLemma {
        step: step_id,
        reason: format!("evaluate: {reason}"),
    };
    if premise_count != 0 {
        return Err(invalid("ground BV evaluation must not have premises"));
    }
    if !args.is_empty() {
        return Err(invalid("ground BV evaluation must not have arguments"));
    }
    let [equality] = clause else {
        return Err(invalid(
            "ground BV evaluation must conclude one equality literal",
        ));
    };
    if terms.sort(*equality) != &Sort::Bool {
        return Err(invalid("conclusion equality must have Bool sort"));
    }
    let TermData::App(Symbol::Named(name), equality_args) = terms.get(*equality) else {
        return Err(invalid("conclusion must be an equality application"));
    };
    if name != "=" || equality_args.len() != 2 {
        return Err(invalid("conclusion must be a binary equality"));
    }

    let (actual, actual_width, contains_concat) = eval_ground_concat(terms, equality_args[0], 0)
        .ok_or_else(|| invalid("left side is not a well-sorted closed concat tree"))?;
    if !contains_concat {
        return Err(invalid("left side must contain a concat"));
    }
    let (expected, expected_width) = eval_ground_bv_constant(terms, equality_args[1])
        .ok_or_else(|| invalid("right side must be a well-sorted BV constant"))?;
    if actual_width != expected_width || actual != expected {
        return Err(invalid(
            "closed concat does not evaluate to the asserted BV constant",
        ));
    }
    Ok(())
}

fn eval_ground_concat(terms: &TermStore, term: TermId, depth: u32) -> Option<(u64, u32, bool)> {
    if depth > 512 {
        return None;
    }
    if let Some((value, width)) = eval_ground_bv_constant(terms, term) {
        return Some((value, width, false));
    }
    let TermData::App(Symbol::Named(name), concat_args) = terms.get(term) else {
        return None;
    };
    if name != "concat" || concat_args.len() != 2 {
        return None;
    }
    let (high, high_width, _) = eval_ground_concat(terms, concat_args[0], depth + 1)?;
    let (low, low_width, _) = eval_ground_concat(terms, concat_args[1], depth + 1)?;
    let width = high_width.checked_add(low_width)?;
    if high_width == 0 || low_width == 0 || width > u64::BITS || low_width >= u64::BITS {
        return None;
    }
    if terms.sort(term) != &Sort::bitvec(width) {
        return None;
    }
    Some(((high << low_width) | low, width, true))
}

fn eval_ground_bv_constant(terms: &TermStore, term: TermId) -> Option<(u64, u32)> {
    let TermData::Const(Constant::BitVec { value, width }) = terms.get(term) else {
        return None;
    };
    if *width == 0 || *width > u64::BITS || terms.sort(term) != &Sort::bitvec(*width) {
        return None;
    }
    let value = value.to_u64()?;
    if value > bv_mask(*width) {
        return None;
    }
    Some((value, *width))
}

/// Recognize whether `clause` is a strict-checkable Boolean tautology — every
/// literal is `Bool`-sorted and the clause is TRUE under every assignment of its
/// bounded (Bool / small-BV) variables. The exact inverse of
/// [`validate_bool_tautology`].
#[must_use]
pub fn recognize_bool_tautology(terms: &TermStore, clause: &[TermId]) -> bool {
    validate_bool_tautology(terms, ProofId(0), clause).is_ok()
}

/// Validate a `BoolTautology` lemma in strict mode: a propositional/Boolean
/// equality or formula that is TRUE under every assignment of its bounded
/// variables (e.g. `(= (not (not p)) p)`, `(= (and p p) p)`). Reuses the same
/// exhaustive bounded evaluator as the bit-blast path, but WITHOUT the
/// `clause_mentions_bv` content requirement — a pure-Boolean tautology has no
/// bitvector sub-term, and the exhaustive evaluation IS the soundness check
/// (every assignment satisfies the clause), so no BV content is needed. Every
/// literal must be `Bool`-sorted, and all variables must be bounded (else the
/// checker cannot exhaustively evaluate and fails closed).
pub(crate) fn validate_bool_tautology(
    terms: &TermStore,
    step_id: ProofId,
    clause: &[TermId],
) -> Result<(), ProofCheckError> {
    if clause.is_empty() {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: "bool tautology clause must be non-empty".to_string(),
        });
    }
    for &lit in clause {
        if !matches!(terms.sort(lit), Sort::Bool) {
            return Err(ProofCheckError::InvalidTheoryLemma {
                step: step_id,
                reason: format!(
                    "bool tautology literal has non-Bool sort {:?}; the clause must \
                     be purely propositional",
                    terms.sort(lit)
                ),
            });
        }
    }
    // Packed clausification units can contain theory atoms the bounded
    // Bool/BV evaluator intentionally cannot interpret. Their propositional
    // tautology is nevertheless decidable by exact structure:
    //
    //   (or p (not p))
    //   (or child (not (and ... child ...)))
    //   (or p q ... (not (or p q ...)))
    //
    // The conjunction form is packed Alethe `and_pos`; top-level assertion
    // flattening also generates the OR/self-complement unit. Recognize only a
    // literal and its exact complement, an exact child of the negated
    // conjunction, or every member of the negated disjunction. The atoms'
    // theory semantics are irrelevant, so this remains sound for RM, arrays,
    // datatypes, and every other Boolean-sorted atom.
    if let [unit] = clause {
        if is_packed_clausification_tautology(terms, *unit) {
            return Ok(());
        }
    }
    validate_bounded_clause_semantics(terms, step_id, clause)
}

fn is_packed_clausification_tautology(terms: &TermStore, term: TermId) -> bool {
    let TermData::App(symbol, disjuncts) = terms.get(term) else {
        return false;
    };
    if symbol.name() != "or" || disjuncts.len() < 2 {
        return false;
    }
    if disjuncts
        .iter()
        .any(|&disjunct| terms.sort(disjunct) != &Sort::Bool)
    {
        return false;
    }
    for &negated in disjuncts {
        let TermData::Not(inner) = terms.get(negated) else {
            continue;
        };
        if terms.sort(*inner) != &Sort::Bool {
            continue;
        }
        if disjuncts.contains(inner) {
            return true;
        }
        let TermData::App(join_symbol, members) = terms.get(*inner) else {
            continue;
        };
        if members
            .iter()
            .any(|&member| terms.sort(member) != &Sort::Bool)
        {
            continue;
        }
        match join_symbol.name() {
            "and"
                if disjuncts
                    .iter()
                    .any(|other| *other != negated && members.contains(other)) =>
            {
                return true;
            }
            "or" if !members.is_empty()
                && members.iter().all(|member| {
                    disjuncts
                        .iter()
                        .any(|other| *other != negated && other == member)
                }) =>
            {
                return true;
            }
            _ => {}
        }
    }
    // The two DUAL shapes, where the gate term occurs POSITIVELY in the packed
    // unit — Alethe `and_neg` and `or_neg`:
    //
    //   (or (and t1 .. tn) (not t1) .. (not tn))   -- and_neg
    //   (or (or  t1 .. tn) (not ti))               -- or_neg
    //
    // Tautology by the same one-line case split as the negated shapes above.
    // `and_neg`: either every `ti` holds, so the conjunction disjunct is true,
    // or some `ti` fails, and ITS negation is one of the disjuncts. `or_neg`:
    // either `ti` holds, so the disjunction disjunct is true, or it fails and
    // `(not ti)` is a disjunct. Both are exact — the members' theory semantics
    // are irrelevant, exactly as for `and_pos`/`or_pos`.
    //
    // Without `and_neg` the Tseitin definition clause of a top-level `(and ..)`
    // over non-Bool-bounded atoms (e.g. an EUF equality) reached the strict
    // checker as a bare `assume` and a correct QF_UF refutation under
    // `:produce-unsat-cores` was rejected as "assumes term outside the supplied
    // problem obligation", publishing `unknown` where z3 says `unsat`
    // (#uc-and-neg-packed-tautology).
    for &positive in disjuncts {
        let TermData::App(join_symbol, members) = terms.get(positive) else {
            continue;
        };
        if members.is_empty() || members.iter().any(|&m| terms.sort(m) != &Sort::Bool) {
            continue;
        }
        let negation_present = |member: TermId| {
            disjuncts.iter().any(|&other| {
                other != positive
                    && matches!(terms.get(other), TermData::Not(inner) if *inner == member)
            })
        };
        match join_symbol.name() {
            "and" if members.iter().all(|&m| negation_present(m)) => return true,
            "or" if members.iter().any(|&m| negation_present(m)) => return true,
            _ => {}
        }
    }
    false
}

/// Validate a `BvBitBlast` or `BvBitBlastGate` lemma in strict mode.
///
/// See module docs for the schema the clause must match.
pub(crate) fn validate_bv_bitblast(
    terms: &TermStore,
    step_id: ProofId,
    clause: &[TermId],
    gate: Option<(BvGateType, u32)>,
) -> Result<(), ProofCheckError> {
    if clause.is_empty() {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: "bv_bitblast clause must be non-empty".to_string(),
        });
    }

    for &lit in clause {
        // Every literal in a propositional bit-blast clause must be Boolean-
        // sorted. If we see a BV/Int/Real literal directly, the prover is
        // trying to sneak a non-propositional term through the SAT interface.
        let lit_sort = terms.sort(lit);
        if !matches!(lit_sort, Sort::Bool) {
            return Err(ProofCheckError::InvalidTheoryLemma {
                step: step_id,
                reason: format!(
                    "bv_bitblast literal has non-Bool sort {lit_sort:?}; \
                     bit-blast clauses must be purely propositional"
                ),
            });
        }
    }

    // The clause must mention at least one sub-term that is actually a
    // bitvector thing: a BV constant, BV variable, BV gate output, or an
    // equality/comparison between BV terms. A clause with no BV content at
    // all is not a bit-blast product, so we reject it as a forgery.
    if !clause_mentions_bv(terms, clause) {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: "bv_bitblast clause does not mention any bitvector \
                     sub-term; a forged lemma cannot hide behind this rule"
                .to_string(),
        });
    }

    // For the annotated gate form, require at least one sub-term that is an
    // application of an SMT-LIB operator consistent with the declared gate
    // type. This is a lightweight sanity check; it rejects lemmas whose
    // declared `gate_type = bvand` is incompatible with a clause that talks
    // only about `bvor`, etc.
    if let Some((gate_type, width)) = gate {
        let required_op = required_op_name(gate_type);
        // `None` means the gate type corresponds to a primitive shape
        // (const / variable / ite) rather than a concrete SMT-LIB operator.
        // For those we skip the operator check — the generic `clause_mentions_bv`
        // check above already rejects clauses without BV content.
        if let Some(op) = required_op {
            if !clause_mentions_matching_gate(terms, clause, op, gate_type, width) {
                return Err(ProofCheckError::InvalidTheoryLemma {
                    step: step_id,
                    reason: format!(
                        "bv_bitblast annotated gate {gate_type:?} requires \
                         the clause to reference operator `{op}` at width \
                         {width}, but no such sub-term was found"
                    ),
                });
            }
        }
    }

    match validate_bounded_clause_semantics(terms, step_id, clause) {
        Ok(()) => Ok(()),
        Err(bounded_error) => validate_proof_producing_clause_semantics(terms, step_id, clause)
            .map_err(|proof_error| ProofCheckError::InvalidTheoryLemma {
                step: step_id,
                reason: format!(
                    "bv_bitblast semantic checks failed: bounded checker: {bounded_error}; \
                     proof-producing checker: {proof_error}"
                ),
            }),
    }
}

/// Return the SMT-LIB operator name that must appear somewhere in the clause
/// for the given gate type. Returns `None` for gate types whose encoding
/// does not produce a named SMT-LIB operator (e.g., `Const`, `Variable`,
/// `Ite`).
fn required_op_name(gate_type: BvGateType) -> Option<&'static str> {
    match gate_type {
        BvGateType::And => Some("bvand"),
        BvGateType::Or => Some("bvor"),
        BvGateType::Xor => Some("bvxor"),
        BvGateType::Not => Some("bvnot"),
        BvGateType::Add => Some("bvadd"),
        BvGateType::Mul => Some("bvmul"),
        BvGateType::Neg => Some("bvneg"),
        BvGateType::Shl => Some("bvshl"),
        BvGateType::Lshr => Some("bvlshr"),
        BvGateType::Ashr => Some("bvashr"),
        BvGateType::Ult => Some("bvult"),
        BvGateType::Concat => Some("concat"),
        BvGateType::Extract => Some("extract"),
        BvGateType::ZeroExtend => Some("zero_extend"),
        BvGateType::SignExtend => Some("sign_extend"),
        BvGateType::Udiv => Some("bvudiv"),
        BvGateType::Urem => Some("bvurem"),
        // Primitive gates: no specific operator symbol required. Generic
        // BV-content check covers these. Any future `BvGateType` variants
        // default to "no specific operator" so we never crash on enum
        // extension.
        BvGateType::Eq | BvGateType::Const | BvGateType::Variable | BvGateType::Ite => None,
        _ => None,
    }
}

/// Return true if any literal in the clause contains (directly or nested) a
/// bitvector constant, bitvector variable, or bitvector-producing term.
fn clause_mentions_bv(terms: &TermStore, clause: &[TermId]) -> bool {
    clause
        .iter()
        .any(|&lit| term_mentions_bv(terms, lit, &mut Vec::new()))
}

fn term_mentions_bv(terms: &TermStore, term: TermId, stack: &mut Vec<TermId>) -> bool {
    // Guard against pathological cyclic/very deep walks. Hash-consing makes
    // cycles impossible in practice but we bound depth defensively.
    if stack.len() > 512 {
        return false;
    }
    stack.push(term);
    let result = if matches!(terms.sort(term), Sort::BitVec(_)) {
        true
    } else {
        match terms.get(term) {
            TermData::App(_, args) => args.iter().any(|&a| term_mentions_bv(terms, a, stack)),
            TermData::Not(inner) | TermData::Ite(_, inner, _) => {
                term_mentions_bv(terms, *inner, stack)
            }
            _ => false,
        }
    };
    stack.pop();
    result
}

/// Return true if any literal in the clause contains an application matching
/// the annotated SMT-LIB operator somewhere in its sub-term tree.
fn clause_mentions_matching_gate(
    terms: &TermStore,
    clause: &[TermId],
    op: &str,
    gate_type: BvGateType,
    width: u32,
) -> bool {
    clause
        .iter()
        .any(|&lit| term_mentions_matching_gate(terms, lit, op, gate_type, width, &mut Vec::new()))
}

fn term_mentions_matching_gate(
    terms: &TermStore,
    term: TermId,
    op: &str,
    gate_type: BvGateType,
    width: u32,
    stack: &mut Vec<TermId>,
) -> bool {
    if stack.len() > 512 {
        return false;
    }
    stack.push(term);
    let result = match terms.get(term) {
        TermData::App(sym, args) => {
            (sym.name() == op && gate_width_matches(terms, term, args, gate_type, width))
                || args
                    .iter()
                    .any(|&a| term_mentions_matching_gate(terms, a, op, gate_type, width, stack))
        }
        TermData::Not(inner) => {
            term_mentions_matching_gate(terms, *inner, op, gate_type, width, stack)
        }
        TermData::Ite(c, t, e) => {
            term_mentions_matching_gate(terms, *c, op, gate_type, width, stack)
                || term_mentions_matching_gate(terms, *t, op, gate_type, width, stack)
                || term_mentions_matching_gate(terms, *e, op, gate_type, width, stack)
        }
        _ => false,
    };
    stack.pop();
    result
}

fn gate_width_matches(
    terms: &TermStore,
    term: TermId,
    args: &[TermId],
    gate_type: BvGateType,
    width: u32,
) -> bool {
    if !same_width_gate_requires_width_check(gate_type) {
        return true;
    }

    bitvec_width(terms.sort(term)) == Some(width)
        && !args.is_empty()
        && args
            .iter()
            .all(|&arg| bitvec_width(terms.sort(arg)) == Some(width))
}

fn same_width_gate_requires_width_check(gate_type: BvGateType) -> bool {
    matches!(
        gate_type,
        BvGateType::And
            | BvGateType::Or
            | BvGateType::Xor
            | BvGateType::Not
            | BvGateType::Add
            | BvGateType::Mul
            | BvGateType::Neg
            | BvGateType::Shl
            | BvGateType::Lshr
            | BvGateType::Ashr
            | BvGateType::Udiv
            | BvGateType::Urem
    )
}

fn bitvec_width(sort: &Sort) -> Option<u32> {
    match sort {
        Sort::BitVec(bv) => Some(bv.width),
        _ => None,
    }
}

// Keep this intentionally small: the checker is a proof validator, not a
// second bit-blaster. These bounds catch small forged gate annotations without
// risking exponential work on real proofs. Wider closed concat evaluation uses
// the separate, non-symbolic `evaluate` validator above.
const MAX_BOUNDED_BV_WIDTH: u32 = 4;
const MAX_BOUNDED_ASSIGNMENT_BITS: u32 = 8;
const MAX_EVALUATED_BV_WIDTH: u32 = u64::BITS;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum EvalValue {
    Bool(bool),
    BitVec { value: u64, width: u32 },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct EvalVar {
    term: TermId,
    kind: EvalVarKind,
    bits: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum EvalVarKind {
    Bool,
    BitVec,
}

const MAX_PROOF_PRODUCING_CLAUSE_LITERALS: usize = 64;
const MAX_PROOF_PRODUCING_TERM_NODES: usize = 4096;
const MAX_PROOF_PRODUCING_EXPR_NODES: usize = 4096;
const MAX_PROOF_PRODUCING_CONSTRUCTED_EXPR_NODES: usize = 100_000;
const MAX_PROOF_PRODUCING_EXPR_DEPTH: usize = 256;
const MAX_PROOF_PRODUCING_GATE_WORK: usize = 100_000;
const MAX_PROOF_PRODUCING_RESOLUTION_STEPS: usize = 250_000;
const PROOF_PRODUCING_DEADLINE: Duration = Duration::from_secs(3);

#[derive(Clone)]
enum ProofProducingExpr {
    Bool(BvExpr),
    BitVec(BvExpr, u32),
}

fn proof_producing_expr_nodes(expr: &ProofProducingExpr) -> Result<usize, String> {
    let root = match expr {
        ProofProducingExpr::Bool(expr) | ProofProducingExpr::BitVec(expr, _) => expr,
    };
    let mut stack = vec![root];
    let mut nodes = 0_usize;
    while let Some(expr) = stack.pop() {
        nodes += 1;
        if nodes > MAX_PROOF_PRODUCING_EXPR_NODES {
            return Err(format!(
                "lowered BvExpr exceeds {MAX_PROOF_PRODUCING_EXPR_NODES} nodes"
            ));
        }
        match expr {
            BvExpr::Leaf { .. } | BvExpr::Const { .. } => {}
            BvExpr::ZeroExt(inner, _)
            | BvExpr::Extract { inner, .. }
            | BvExpr::SignExt(inner, _)
            | BvExpr::Not(inner) => stack.push(inner),
            BvExpr::CarryOut { lhs, rhs, .. }
            | BvExpr::Add(lhs, rhs)
            | BvExpr::Sub(lhs, rhs)
            | BvExpr::Or(lhs, rhs)
            | BvExpr::And(lhs, rhs)
            | BvExpr::Xor(lhs, rhs)
            | BvExpr::Shl(lhs, rhs)
            | BvExpr::Lshr(lhs, rhs)
            | BvExpr::Ashr(lhs, rhs)
            | BvExpr::Eq(lhs, rhs)
            | BvExpr::Mul(lhs, rhs) => {
                stack.push(rhs);
                stack.push(lhs);
            }
        }
    }
    Ok(nodes)
}

/// Prove a symbolic Bool/BV clause by bit-blasting it to CNF, asking the SAT
/// engine for an LRAT-derived resolution DAG, and replaying the resulting
/// [`crate::BvBlastProof`]. This is the scalable complement to exhaustive
/// assignment enumeration: no solver verdict is accepted without the surfaced
/// gate provenance and resolution refutation validating end to end.
///
/// SOURCE BINDING. This strict-checker path accepts no serialized
/// `BvBlastProof`. It lowers the exact live `TermStore` clause into `BvExpr`,
/// constructs the graph from that expression, and bounded-replays the freshly
/// returned object in this same call. Thus there is no artifact-substitution
/// boundary at which `asserted_smt` or `obligation` metadata could replace the
/// checked clause. External stored-proof consumers must instead re-derive and
/// compare the graph before granting authority; `BvBlastProof::validate` alone
/// is deliberately only an internal graph/CNF replay.
fn validate_proof_producing_clause_semantics(
    terms: &TermStore,
    _step_id: ProofId,
    clause: &[TermId],
) -> Result<(), String> {
    if clause.is_empty() || clause.len() > MAX_PROOF_PRODUCING_CLAUSE_LITERALS {
        return Err(format!(
            "clause has {} literals (supported: 1..={MAX_PROOF_PRODUCING_CLAUSE_LITERALS})",
            clause.len()
        ));
    }

    let mut lowerer = ProofProducingLowerer::new(terms);
    let mut disjunction = BvExpr::const_val(0, 1);
    for &literal in clause {
        let literal = lowerer.lower_bool(literal)?;
        disjunction = BvExpr::or(disjunction, literal);
    }
    let truth = BvExpr::const_val(1, 1);
    let limits = proof_producing_limits();
    let proof = export_bv_blast_proof_expr_with_limits(&disjunction, &truth, &limits)
        .map_err(|error| format!("negated clause did not yield a refutation: {error}"))?;
    let replay_limits = BvBlastValidateLimits {
        deadline: limits
            .resolution
            .validation
            .deadline
            .or(limits.resolution.deadline),
        max_vars: limits.resolution.max_num_vars,
        max_bit_lemmas: limits.max_estimated_gate_work,
        max_clauses: limits.resolution.max_input_clauses,
        max_clause_literals: limits.resolution.max_input_clause_literals,
        max_original_literals: limits.resolution.max_input_literals,
        max_resolution_steps: limits.max_resolution_steps,
        max_derived_literals: limits.resolution.max_derived_literals,
        max_work: limits.resolution.validation.max_work,
    };
    proof
        .validate_with_limits(&replay_limits)
        .map_err(|error| format!("surfaced bit-blast refutation failed replay: {error}"))?;
    Ok(())
}

fn proof_producing_limits() -> BvExprProofLimits {
    let deadline = Instant::now() + PROOF_PRODUCING_DEADLINE;
    let mut resolution = ResolutionProofLimits::default();
    resolution.deadline = Some(deadline);
    resolution.max_num_vars = 150_000;
    resolution.max_input_clauses = 700_000;
    resolution.max_input_literals = 3_000_000;
    resolution.max_input_clause_literals = 64;
    resolution.max_input_bytes = 64 * 1024 * 1024;
    resolution.max_conflicts = Some(250_000);
    resolution.max_decisions = Some(2_000_000);
    resolution.solver_clause_db_reduction_threshold_bytes = 64 * 1024 * 1024;
    resolution.max_proof_output_bytes = 64 * 1024 * 1024;
    resolution.max_derived_steps = MAX_PROOF_PRODUCING_RESOLUTION_STEPS;
    resolution.max_derived_literals = 2_000_000;
    resolution.max_hints = 4_000_000;
    resolution.max_pending_deletions = 250_000;
    resolution.max_codec_bytes = 192 * 1024 * 1024;
    resolution.max_backward_reconstruction_bytes = 64 * 1024 * 1024;
    resolution.validation.deadline = Some(deadline);
    resolution.validation.max_original_clauses = resolution.max_input_clauses;
    resolution.validation.max_original_literals = resolution.max_input_literals;
    resolution.validation.max_derived_steps = resolution.max_derived_steps;
    resolution.validation.max_derived_literals = resolution.max_derived_literals;
    resolution.validation.max_hints = resolution.max_hints;
    resolution.validation.max_work = 50_000_000;
    resolution.validation.max_bytes = 128 * 1024 * 1024;
    BvExprProofLimits {
        max_expr_nodes: MAX_PROOF_PRODUCING_EXPR_NODES,
        max_expr_depth: MAX_PROOF_PRODUCING_EXPR_DEPTH,
        max_estimated_gate_work: MAX_PROOF_PRODUCING_GATE_WORK,
        max_resolution_steps: MAX_PROOF_PRODUCING_RESOLUTION_STEPS,
        resolution,
    }
}

struct ProofProducingLowerer<'a> {
    terms: &'a TermStore,
    memo: HashMap<TermId, ProofProducingExpr>,
    memo_node_counts: HashMap<TermId, usize>,
    active: HashSet<TermId>,
    visited_nodes: usize,
    constructed_expr_nodes: usize,
}

impl<'a> ProofProducingLowerer<'a> {
    fn new(terms: &'a TermStore) -> Self {
        Self {
            terms,
            memo: HashMap::new(),
            memo_node_counts: HashMap::new(),
            active: HashSet::new(),
            visited_nodes: 0,
            constructed_expr_nodes: 0,
        }
    }

    fn lower_bool(&mut self, term: TermId) -> Result<BvExpr, String> {
        match self.lower(term)? {
            ProofProducingExpr::Bool(expr) => Ok(expr),
            ProofProducingExpr::BitVec(_, width) => Err(format!(
                "term {} is BitVec({width}), not Bool",
                term.index()
            )),
        }
    }

    fn lower_bv(&mut self, term: TermId) -> Result<(BvExpr, u32), String> {
        match self.lower(term)? {
            ProofProducingExpr::BitVec(expr, width) => Ok((expr, width)),
            ProofProducingExpr::Bool(_) => {
                Err(format!("term {} is Bool, not BitVec", term.index()))
            }
        }
    }

    fn lower(&mut self, term: TermId) -> Result<ProofProducingExpr, String> {
        if self.memo.contains_key(&term) {
            let nodes = self.memo_node_counts[&term];
            self.charge_constructed_expr_nodes(nodes)?;
            return Ok(self.memo[&term].clone());
        }
        self.visited_nodes += 1;
        if self.visited_nodes > MAX_PROOF_PRODUCING_TERM_NODES {
            return Err(format!(
                "term DAG exceeds {MAX_PROOF_PRODUCING_TERM_NODES} nodes"
            ));
        }
        if !self.active.insert(term) {
            return Err("cyclic term DAG".to_string());
        }
        let sort = self.terms.sort(term).clone();
        let data = self.terms.get(term).clone();
        let result = match sort {
            Sort::Bool => self.lower_bool_node(term, data),
            Sort::BitVec(width) if width.width > 0 && width.width <= 64 => {
                self.lower_bv_node(term, width.width, data)
            }
            Sort::BitVec(width) => Err(format!(
                "BitVec width {} is outside proof-producing range 1..=64",
                width.width
            )),
            other => Err(format!("unsupported sort {other:?} in Bool/BV clause")),
        };
        self.active.remove(&term);
        let result = result?;
        let expr_nodes = proof_producing_expr_nodes(&result)?;
        self.charge_constructed_expr_nodes(expr_nodes)?;
        self.memo_node_counts.insert(term, expr_nodes);
        self.memo.insert(term, result.clone());
        Ok(result)
    }

    fn charge_constructed_expr_nodes(&mut self, nodes: usize) -> Result<(), String> {
        let actual = self
            .constructed_expr_nodes
            .checked_add(nodes)
            .unwrap_or(usize::MAX);
        if actual > MAX_PROOF_PRODUCING_CONSTRUCTED_EXPR_NODES {
            return Err(format!(
                "lowered BvExpr construction exceeds {MAX_PROOF_PRODUCING_CONSTRUCTED_EXPR_NODES} nodes"
            ));
        }
        self.constructed_expr_nodes = actual;
        Ok(())
    }

    fn lower_bool_node(
        &mut self,
        term: TermId,
        data: TermData,
    ) -> Result<ProofProducingExpr, String> {
        let expr = match data {
            TermData::Const(Constant::Bool(value)) => BvExpr::const_val(u128::from(value), 1),
            TermData::Var(_, _) => BvExpr::leaf(&format!("proof_bool_{}", term.index()), 1),
            TermData::Not(inner) => BvExpr::not(self.lower_bool(inner)?),
            TermData::App(symbol, args) => self.lower_bool_app(&symbol, &args)?,
            TermData::Ite(..) => {
                return Err("Bool ite is outside the proof-producing fragment".to_string())
            }
            other => return Err(format!("unsupported Bool node {other:?}")),
        };
        Ok(ProofProducingExpr::Bool(expr))
    }

    fn lower_bool_app(&mut self, symbol: &Symbol, args: &[TermId]) -> Result<BvExpr, String> {
        let name = symbol.name();
        match name {
            "and" => {
                let mut out = BvExpr::const_val(1, 1);
                for &arg in args {
                    out = BvExpr::and(out, self.lower_bool(arg)?);
                }
                Ok(out)
            }
            "or" => {
                let mut out = BvExpr::const_val(0, 1);
                for &arg in args {
                    out = BvExpr::or(out, self.lower_bool(arg)?);
                }
                Ok(out)
            }
            "not" if args.len() == 1 => Ok(BvExpr::not(self.lower_bool(args[0])?)),
            "=" if args.len() == 2 => match self.terms.sort(args[0]) {
                Sort::Bool => Ok(BvExpr::eq(
                    self.lower_bool(args[0])?,
                    self.lower_bool(args[1])?,
                )),
                Sort::BitVec(_) => {
                    let (lhs, lhs_width) = self.lower_bv(args[0])?;
                    let (rhs, rhs_width) = self.lower_bv(args[1])?;
                    Self::require_same_width(name, lhs_width, rhs_width)?;
                    Ok(BvExpr::eq(lhs, rhs))
                }
                sort => Err(format!("equality over unsupported sort {sort:?}")),
            },
            "bvult" | "bvule" | "bvugt" | "bvuge" if args.len() == 2 => {
                let (lhs, lhs_width) = self.lower_bv(args[0])?;
                let (rhs, rhs_width) = self.lower_bv(args[1])?;
                Self::require_same_width(name, lhs_width, rhs_width)?;
                let ult = |a: BvExpr, b: BvExpr| BvExpr::not(BvExpr::carry_out_sub(a, b));
                Ok(match name {
                    "bvult" => ult(lhs, rhs),
                    "bvule" => BvExpr::not(ult(rhs, lhs)),
                    "bvugt" => ult(rhs, lhs),
                    "bvuge" => BvExpr::not(ult(lhs, rhs)),
                    _ => unreachable!("guarded comparison"),
                })
            }
            _ => Err(format!("unsupported Bool/BV predicate `{symbol}`")),
        }
    }

    fn lower_bv_node(
        &mut self,
        term: TermId,
        expected_width: u32,
        data: TermData,
    ) -> Result<ProofProducingExpr, String> {
        let (expr, width) = match data {
            TermData::Const(Constant::BitVec { value, width }) => {
                let value = value.to_u128().ok_or_else(|| {
                    "BitVec constant does not fit the 64-bit proof range".to_string()
                })?;
                (BvExpr::const_val(value, width), width)
            }
            TermData::Var(_, _) => (
                BvExpr::leaf(&format!("proof_bv_{}", term.index()), expected_width),
                expected_width,
            ),
            TermData::App(symbol, args) => self.lower_bv_app(&symbol, &args)?,
            TermData::Ite(..) => {
                return Err("BitVec ite is outside the proof-producing fragment".to_string())
            }
            other => return Err(format!("unsupported BitVec node {other:?}")),
        };
        if width != expected_width {
            return Err(format!(
                "term {} lowers to width {width}, expected {expected_width}",
                term.index()
            ));
        }
        Ok(ProofProducingExpr::BitVec(expr, width))
    }

    fn lower_bv_app(&mut self, symbol: &Symbol, args: &[TermId]) -> Result<(BvExpr, u32), String> {
        if let Symbol::Indexed(name, indices) = symbol {
            if args.is_empty() {
                if let (Some(value), [width]) = (name.strip_prefix("bv"), indices.as_slice()) {
                    let value = value
                        .parse::<u128>()
                        .map_err(|_| format!("malformed indexed BV constant `{symbol}`"))?;
                    return Ok((BvExpr::const_val(value, *width), *width));
                }
            }
            let [arg] = args else {
                return Err(format!("indexed operator `{symbol}` requires one argument"));
            };
            return match (name.as_str(), indices.as_slice()) {
                ("zero_extend", [added]) => {
                    let (inner, width) = self.lower_bv(*arg)?;
                    let out = width
                        .checked_add(*added)
                        .ok_or_else(|| "zero_extend width overflow".to_string())?;
                    Ok((BvExpr::zero_ext(inner, *added), out))
                }
                ("sign_extend", [added]) => {
                    let (inner, width) = self.lower_bv(*arg)?;
                    let out = width
                        .checked_add(*added)
                        .ok_or_else(|| "sign_extend width overflow".to_string())?;
                    Ok((BvExpr::sign_ext(inner, *added), out))
                }
                ("extract", [high, low]) if high >= low => {
                    let (inner, width) = self.lower_bv(*arg)?;
                    if *high >= width {
                        return Err(format!("extract high bit {high} exceeds width {width}"));
                    }
                    Ok((BvExpr::extract(inner, *high, *low), high - low + 1))
                }
                _ => Err(format!("unsupported indexed BitVec operator `{symbol}`")),
            };
        }

        let name = symbol.name();
        if name == "bvnot" || name == "bvneg" {
            let [arg] = args else {
                return Err(format!("`{name}` requires one argument"));
            };
            let (inner, width) = self.lower_bv(*arg)?;
            return Ok((
                if name == "bvnot" {
                    BvExpr::not(inner)
                } else {
                    BvExpr::sub(BvExpr::const_val(0, width), inner)
                },
                width,
            ));
        }
        let [lhs_term, rhs_term] = args else {
            return Err(format!("`{name}` requires two arguments"));
        };
        let (lhs, lhs_width) = self.lower_bv(*lhs_term)?;
        let (rhs, rhs_width) = self.lower_bv(*rhs_term)?;
        if name == "concat" {
            let width = lhs_width
                .checked_add(rhs_width)
                .ok_or_else(|| "concat width overflow".to_string())?;
            let high = BvExpr::zero_ext(lhs, rhs_width);
            let low = BvExpr::zero_ext(rhs, lhs_width);
            let shifted = BvExpr::shl(high, BvExpr::const_val(u128::from(rhs_width), width));
            return Ok((BvExpr::or(shifted, low), width));
        }
        Self::require_same_width(name, lhs_width, rhs_width)?;
        let expr = match name {
            "bvadd" => BvExpr::add(lhs, rhs),
            "bvsub" => BvExpr::sub(lhs, rhs),
            "bvmul" => BvExpr::mul(lhs, rhs),
            "bvand" => BvExpr::and(lhs, rhs),
            "bvor" => BvExpr::or(lhs, rhs),
            "bvxor" => BvExpr::xor(lhs, rhs),
            "bvnand" => BvExpr::not(BvExpr::and(lhs, rhs)),
            "bvnor" => BvExpr::not(BvExpr::or(lhs, rhs)),
            "bvxnor" => BvExpr::not(BvExpr::xor(lhs, rhs)),
            "bvshl" => BvExpr::shl(lhs, rhs),
            "bvlshr" => BvExpr::lshr(lhs, rhs),
            "bvashr" => BvExpr::ashr(lhs, rhs),
            _ => return Err(format!("unsupported BitVec operator `{symbol}`")),
        };
        Ok((expr, lhs_width))
    }

    fn require_same_width(name: &str, lhs: u32, rhs: u32) -> Result<(), String> {
        if lhs == rhs {
            Ok(())
        } else {
            Err(format!("`{name}` width mismatch: {lhs} vs {rhs}"))
        }
    }
}

fn validate_bounded_clause_semantics(
    terms: &TermStore,
    step_id: ProofId,
    clause: &[TermId],
) -> Result<(), ProofCheckError> {
    let Some(vars) = collect_bounded_vars(terms, clause) else {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: "bv_bitblast clause contains unsupported or too-wide \
                     Bool/BV terms; strict mode only accepts lemmas it can \
                     exhaustively evaluate"
                .to_string(),
        });
    };
    let total_bits: u32 = vars.iter().map(|v| v.bits).sum();
    if total_bits > MAX_BOUNDED_ASSIGNMENT_BITS {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: format!(
                "bv_bitblast clause needs {total_bits} assignment bits, \
                 above strict bounded checker limit {MAX_BOUNDED_ASSIGNMENT_BITS}"
            ),
        });
    }

    let assignment_count = 1u64 << total_bits;
    for assignment in 0..assignment_count {
        let env = build_eval_env(&vars, assignment);
        let mut clause_true = false;
        for &lit in clause {
            let Some(value) = eval_bool_term(terms, lit, &env) else {
                return Err(ProofCheckError::InvalidTheoryLemma {
                    step: step_id,
                    reason: "bv_bitblast clause contains a literal the strict \
                             bounded checker cannot evaluate"
                        .to_string(),
                });
            };
            if value {
                clause_true = true;
                break;
            }
        }
        if !clause_true {
            return Err(ProofCheckError::InvalidTheoryLemma {
                step: step_id,
                reason: "bv_bitblast clause is falsified by a bounded Bool/BV \
                         assignment"
                    .to_string(),
            });
        }
    }

    Ok(())
}

fn collect_bounded_vars(terms: &TermStore, clause: &[TermId]) -> Option<Vec<EvalVar>> {
    let mut vars = Vec::new();
    for &lit in clause {
        collect_bounded_vars_term(terms, lit, &mut vars, &mut Vec::new())?;
    }
    Some(vars)
}

fn collect_bounded_vars_term(
    terms: &TermStore,
    term: TermId,
    vars: &mut Vec<EvalVar>,
    stack: &mut Vec<TermId>,
) -> Option<()> {
    if stack.len() > 512 {
        return None;
    }
    if matches!(
        terms.sort(term),
        Sort::BitVec(bv) if bv.width > MAX_EVALUATED_BV_WIDTH
    ) {
        return None;
    }
    stack.push(term);
    let result = match terms.get(term) {
        TermData::Const(Constant::Bool(_)) => Some(()),
        TermData::Const(Constant::BitVec { width, .. }) if *width <= MAX_BOUNDED_BV_WIDTH => {
            Some(())
        }
        TermData::Const(_) => None,
        TermData::Var(_, _) => {
            let (kind, bits) = match terms.sort(term) {
                Sort::Bool => (EvalVarKind::Bool, 1),
                Sort::BitVec(bv) if bv.width <= MAX_BOUNDED_BV_WIDTH => {
                    (EvalVarKind::BitVec, bv.width)
                }
                _ => return None,
            };
            if !vars.iter().any(|var| var.term == term) {
                vars.push(EvalVar { term, kind, bits });
            }
            Some(())
        }
        TermData::App(sym, args) if supports_bounded_app(sym.name()) => {
            for &arg in args {
                collect_bounded_vars_term(terms, arg, vars, stack)?;
            }
            Some(())
        }
        TermData::Not(inner) => collect_bounded_vars_term(terms, *inner, vars, stack),
        TermData::Ite(c, t, e) => {
            collect_bounded_vars_term(terms, *c, vars, stack)?;
            collect_bounded_vars_term(terms, *t, vars, stack)?;
            collect_bounded_vars_term(terms, *e, vars, stack)
        }
        _ => None,
    };
    stack.pop();
    result
}

/// Operator names the bounded evaluator ([`eval_app`] / [`eval_indexed_bv`]) can
/// exhaustively evaluate. MUST stay in lock-step with those functions: an op
/// listed here but unhandled there (or vice versa) breaks the collect/evaluate
/// contract and makes the checker either panic-free-but-wrong or fail spuriously.
fn supports_bounded_app(name: &str) -> bool {
    matches!(
        name,
        "=" | "or"
            | "and"
            | "bvand"
            | "bvor"
            | "bvxor"
            | "bvnand"
            | "bvnor"
            | "bvxnor"
            | "bvnot"
            | "bvadd"
            | "bvsub"
            | "bvmul"
            | "bvneg"
            | "bvudiv"
            | "bvurem"
            | "bvsdiv"
            | "bvsrem"
            | "bvsmod"
            | "bvult"
            | "bvule"
            | "bvugt"
            | "bvuge"
            | "bvslt"
            | "bvsle"
            | "bvsgt"
            | "bvsge"
            | "bvshl"
            | "bvlshr"
            | "bvashr"
            | "concat"
            | "extract"
            | "zero_extend"
            | "sign_extend"
            | "rotate_left"
            | "rotate_right"
            | "repeat"
    )
}

fn build_eval_env(vars: &[EvalVar], assignment: u64) -> Vec<(TermId, EvalValue)> {
    let mut env = Vec::with_capacity(vars.len());
    let mut remaining = assignment;
    for var in vars {
        match var.kind {
            EvalVarKind::Bool => {
                env.push((var.term, EvalValue::Bool((remaining & 1) != 0)));
                remaining >>= 1;
            }
            EvalVarKind::BitVec => {
                let mask = bv_mask(var.bits);
                env.push((
                    var.term,
                    EvalValue::BitVec {
                        value: remaining & mask,
                        width: var.bits,
                    },
                ));
                remaining >>= var.bits;
            }
        }
    }
    env
}

fn eval_bool_term(terms: &TermStore, term: TermId, env: &[(TermId, EvalValue)]) -> Option<bool> {
    match eval_term(terms, term, env)? {
        EvalValue::Bool(value) => Some(value),
        EvalValue::BitVec { .. } => None,
    }
}

fn eval_term(terms: &TermStore, term: TermId, env: &[(TermId, EvalValue)]) -> Option<EvalValue> {
    match terms.get(term) {
        TermData::Const(Constant::Bool(value)) => Some(EvalValue::Bool(*value)),
        TermData::Const(Constant::BitVec { value, width }) => {
            let value = value.to_u64()? & bv_mask(*width);
            Some(EvalValue::BitVec {
                value,
                width: *width,
            })
        }
        TermData::Var(_, _) => env
            .iter()
            .find_map(|(var, value)| (*var == term).then_some(*value)),
        TermData::Not(inner) => Some(EvalValue::Bool(!eval_bool_term(terms, *inner, env)?)),
        TermData::Ite(c, t, e) => {
            let branch = if eval_bool_term(terms, *c, env)? {
                *t
            } else {
                *e
            };
            eval_term(terms, branch, env)
        }
        TermData::App(sym, args) => eval_app(terms, sym, args, env),
        _ => None,
    }
}

fn eval_app(
    terms: &TermStore,
    sym: &Symbol,
    args: &[TermId],
    env: &[(TermId, EvalValue)],
) -> Option<EvalValue> {
    // Indexed BV ops (extract / zero_extend / sign_extend) carry their indices in
    // the symbol, so dispatch on them before the name-based match below.
    if let Symbol::Indexed(name, indices) = sym {
        return eval_indexed_bv(terms, name, indices, args, env);
    }
    let name = sym.name();
    match name {
        "=" if args.len() == 2 => Some(EvalValue::Bool(
            eval_term(terms, args[0], env)? == eval_term(terms, args[1], env)?,
        )),
        "or" => {
            let mut any_true = false;
            for &arg in args {
                any_true |= eval_bool_term(terms, arg, env)?;
            }
            Some(EvalValue::Bool(any_true))
        }
        "and" => {
            let mut all_true = true;
            for &arg in args {
                all_true &= eval_bool_term(terms, arg, env)?;
            }
            Some(EvalValue::Bool(all_true))
        }
        "bvnot" if args.len() == 1 => {
            let (value, width) = eval_bv_arg(terms, args[0], env)?;
            Some(EvalValue::BitVec {
                value: (!value) & bv_mask(width),
                width,
            })
        }
        "bvneg" if args.len() == 1 => {
            let (value, width) = eval_bv_arg(terms, args[0], env)?;
            Some(EvalValue::BitVec {
                value: value.wrapping_neg() & bv_mask(width),
                width,
            })
        }
        "bvult" | "bvule" | "bvugt" | "bvuge" | "bvslt" | "bvsle" | "bvsgt" | "bvsge"
            if args.len() == 2 =>
        {
            let (lhs, rhs, width) = eval_same_width_bv_args(terms, args, env)?;
            let (sl, sr) = (to_signed_u64(lhs, width), to_signed_u64(rhs, width));
            let result = match name {
                "bvult" => lhs < rhs,
                "bvule" => lhs <= rhs,
                "bvugt" => lhs > rhs,
                "bvuge" => lhs >= rhs,
                "bvslt" => sl < sr,
                "bvsle" => sl <= sr,
                "bvsgt" => sl > sr,
                "bvsge" => sl >= sr,
                _ => unreachable!("guarded by match arm"),
            };
            Some(EvalValue::Bool(result))
        }
        "bvand" | "bvor" | "bvxor" | "bvnand" | "bvnor" | "bvxnor" | "bvadd" | "bvsub"
        | "bvmul" | "bvudiv" | "bvurem"
            if args.len() == 2 =>
        {
            let (lhs, rhs, width) = eval_same_width_bv_args(terms, args, env)?;
            let value = match name {
                "bvand" => lhs & rhs,
                "bvor" => lhs | rhs,
                "bvxor" => lhs ^ rhs,
                "bvnand" => !(lhs & rhs),
                "bvnor" => !(lhs | rhs),
                "bvxnor" => !(lhs ^ rhs),
                "bvadd" => lhs.wrapping_add(rhs),
                "bvsub" => lhs.wrapping_sub(rhs),
                "bvmul" => lhs.wrapping_mul(rhs),
                // SMT-LIB makes unsigned division/remainder TOTAL: dividing by
                // zero yields all-ones (bvudiv) / the dividend (bvurem).
                "bvudiv" => lhs.checked_div(rhs).unwrap_or_else(|| bv_mask(width)),
                "bvurem" => lhs.checked_rem(rhs).unwrap_or(lhs),
                _ => unreachable!("guarded by match arm"),
            } & bv_mask(width);
            Some(EvalValue::BitVec { value, width })
        }
        "bvsdiv" | "bvsrem" | "bvsmod" if args.len() == 2 => {
            let (lhs, rhs, width) = eval_same_width_bv_args(terms, args, env)?;
            Some(EvalValue::BitVec {
                value: eval_bv_signed_divrem(name, lhs, rhs, width),
                width,
            })
        }
        "bvshl" | "bvlshr" | "bvashr" if args.len() == 2 => {
            let (lhs, rhs, width) = eval_same_width_bv_args(terms, args, env)?;
            Some(EvalValue::BitVec {
                value: eval_bv_shift(name, lhs, rhs, width),
                width,
            })
        }
        "concat" if args.len() == 2 => {
            // SMT-LIB `(concat hi lo)`: first arg is the high part, second the low.
            let (hi, hi_width) = eval_bv_arg(terms, args[0], env)?;
            let (lo, lo_width) = eval_bv_arg(terms, args[1], env)?;
            let width = hi_width.checked_add(lo_width)?;
            if hi_width == 0 || lo_width == 0 || width > MAX_EVALUATED_BV_WIDTH {
                return None;
            }
            Some(EvalValue::BitVec {
                value: ((hi << lo_width) | lo) & bv_mask(width),
                width,
            })
        }
        _ => None,
    }
}

/// Evaluate the indexed bit-vector ops `extract` / `zero_extend` / `sign_extend`,
/// whose width-changing behavior is parameterized by the symbol indices. Kept in
/// lock-step with [`supports_bounded_app`] so collection and evaluation agree.
fn eval_indexed_bv(
    terms: &TermStore,
    name: &str,
    indices: &[u32],
    args: &[TermId],
    env: &[(TermId, EvalValue)],
) -> Option<EvalValue> {
    match name {
        "extract" if indices.len() == 2 && args.len() == 1 => {
            let (high, low) = (indices[0], indices[1]);
            let (value, src_width) = eval_bv_arg(terms, args[0], env)?;
            if high < low || high >= src_width {
                return None;
            }
            let width = high.checked_sub(low)?.checked_add(1)?;
            Some(EvalValue::BitVec {
                value: (value >> low) & bv_mask(width),
                width,
            })
        }
        "zero_extend" if indices.len() == 1 && args.len() == 1 => {
            let (value, src_width) = eval_bv_arg(terms, args[0], env)?;
            let width = src_width.checked_add(indices[0])?;
            if width > MAX_EVALUATED_BV_WIDTH {
                return None;
            }
            // The added high bits are zero; `value` is already masked to src_width.
            Some(EvalValue::BitVec {
                value: value & bv_mask(width),
                width,
            })
        }
        "sign_extend" if indices.len() == 1 && args.len() == 1 => {
            let (value, src_width) = eval_bv_arg(terms, args[0], env)?;
            let width = src_width.checked_add(indices[0])?;
            if src_width == 0 || width > MAX_EVALUATED_BV_WIDTH {
                return None;
            }
            let negative = src_width > 0 && (value >> (src_width - 1)) & 1 == 1;
            let extended = if negative {
                // Fill the added high bits with the sign bit (1).
                value | (bv_mask(width) ^ bv_mask(src_width))
            } else {
                value
            };
            Some(EvalValue::BitVec {
                value: extended & bv_mask(width),
                width,
            })
        }
        "rotate_left" | "rotate_right" if indices.len() == 1 && args.len() == 1 => {
            let (value, width) = eval_bv_arg(terms, args[0], env)?;
            let mask = bv_mask(width);
            let k = indices[0] % width.max(1);
            let rotated = if k == 0 {
                value
            } else if name == "rotate_left" {
                ((value << k) | (value >> (width - k))) & mask
            } else {
                ((value >> k) | (value << (width - k))) & mask
            };
            Some(EvalValue::BitVec {
                value: rotated,
                width,
            })
        }
        "repeat" if indices.len() == 1 && args.len() == 1 => {
            let count = indices[0];
            if count == 0 {
                return None; // (_ repeat 0) is not well-formed
            }
            let (value, width) = eval_bv_arg(terms, args[0], env)?;
            let total = width.checked_mul(count)?;
            if width == 0 || total > MAX_EVALUATED_BV_WIDTH {
                return None;
            }
            let mut result = 0u64;
            for index in 0..count {
                result = if index == 0 {
                    value
                } else {
                    (result << width) | value
                };
            }
            Some(EvalValue::BitVec {
                value: result & bv_mask(total),
                width: total,
            })
        }
        _ => None,
    }
}

/// SMT-LIB bit-vector shift semantics for the strict bounded checker.
///
/// The shift amount is the *unsigned* value of `rhs`; it is NOT reduced modulo
/// `width`, so shifting by `>= width` SATURATES (0 for shl/lshr, sign-fill for
/// ashr). That over-shift case is exactly where machine shifts (x86 masks the
/// count) and LLVM shifts (poison at `s >= bitwidth`) diverge from SMT-LIB, so
/// the checker computes it explicitly to validate shift gates against the spec.
/// `lhs`/`rhs` are already masked to `width`.
fn eval_bv_shift(name: &str, lhs: u64, rhs: u64, width: u32) -> u64 {
    let mask = bv_mask(width);
    let shift = rhs;
    match name {
        "bvshl" if shift < u64::from(width) => (lhs << shift) & mask,
        "bvlshr" if shift < u64::from(width) => (lhs >> shift) & mask,
        // shl / lshr over-shift (shift >= width) saturate to zero.
        "bvshl" | "bvlshr" => 0,
        "bvashr" => {
            let negative = width > 0 && (lhs >> (width - 1)) & 1 == 1;
            if shift >= u64::from(width) {
                // Over-shift fills with the sign bit: all-ones / all-zeros.
                if negative {
                    mask
                } else {
                    0
                }
            } else {
                let logical = (lhs >> shift) & mask;
                if negative {
                    // Set the top `shift` vacated bits to 1 (sign fill).
                    (logical | (mask ^ (mask >> shift))) & mask
                } else {
                    logical
                }
            }
        }
        _ => unreachable!("eval_bv_shift only called for bvshl/bvlshr/bvashr"),
    }
}

/// Interpret a width-`w` bit-vector value as a two's-complement signed integer.
fn to_signed_u64(value: u64, width: u32) -> i64 {
    if width == 0 {
        return 0;
    }
    if width >= u64::BITS {
        return value as i64;
    }
    if (value >> (width - 1)) & 1 == 1 {
        (value as i64).wrapping_sub(1i64 << width)
    } else {
        value as i64
    }
}

/// SMT-LIB signed division / remainder / modulo — all TOTAL. `lhs`/`rhs` are
/// already masked to `width`. Division truncates toward zero; ÷0 yields -1 (a>=0)
/// or 1 (a<0) for bvsdiv and the dividend for bvsrem/bvsmod. bvsrem takes the sign
/// of the dividend; bvsmod takes the sign of the divisor.
fn eval_bv_signed_divrem(name: &str, lhs: u64, rhs: u64, width: u32) -> u64 {
    let mask = bv_mask(width);
    let a = to_signed_u64(lhs, width);
    let b = to_signed_u64(rhs, width);
    let pack = |s: i64| -> u64 { (s as u64) & mask };
    match name {
        "bvsdiv" => {
            if b == 0 {
                pack(if a >= 0 { -1 } else { 1 })
            } else {
                pack(a.wrapping_div(b))
            }
        }
        "bvsrem" => {
            if b == 0 {
                lhs
            } else {
                pack(a.wrapping_rem(b))
            }
        }
        "bvsmod" => {
            if b == 0 {
                lhs
            } else {
                let r = a.wrapping_rem(b);
                let m = if r == 0 || (r < 0) == (b < 0) {
                    r
                } else {
                    r + b
                };
                pack(m)
            }
        }
        _ => unreachable!("eval_bv_signed_divrem only for bvsdiv/bvsrem/bvsmod"),
    }
}

fn eval_bv_arg(terms: &TermStore, arg: TermId, env: &[(TermId, EvalValue)]) -> Option<(u64, u32)> {
    match eval_term(terms, arg, env)? {
        EvalValue::BitVec { value, width } => Some((value & bv_mask(width), width)),
        EvalValue::Bool(_) => None,
    }
}

fn eval_same_width_bv_args(
    terms: &TermStore,
    args: &[TermId],
    env: &[(TermId, EvalValue)],
) -> Option<(u64, u64, u32)> {
    let (lhs, lhs_width) = eval_bv_arg(terms, args[0], env)?;
    let (rhs, rhs_width) = eval_bv_arg(terms, args[1], env)?;
    (lhs_width == rhs_width).then_some((lhs, rhs, lhs_width))
}

fn bv_mask(width: u32) -> u64 {
    if width >= u64::BITS {
        u64::MAX
    } else {
        (1u64 << width) - 1
    }
}
