// Copyright 2026 Andrew Yates
// Author: Andrew Yates <andrewyates.name@gmail.com>
// Licensed under the Apache License, Version 2.0

//! Strict-mode schema validation for `TheoryLemmaKind::BvBitBlast` and
//! `TheoryLemmaKind::BvBitBlastGate` proof steps.
//!
//! Context (#8820): previously these lemmas were accepted structurally — any
//! non-empty clause passed, so an attacker-controlled proof could forge a
//! BV lemma and obtain UNSAT. This module replaces the non-empty check with
//! schema validation that catches the most common forgery patterns:
//!
//! - Every literal in a bit-blast clause must be Boolean-sorted. Non-Boolean
//!   terms cannot appear in a propositional clause generated by the bit
//!   blaster.
//! - The clause must mention at least one sub-term involving a bitvector
//!   constant, variable, or gate operation — a pure propositional clause
//!   with no BV content is not a bit-blast product.
//! - Annotated same-width gate lemmas must reference the declared operator at
//!   the declared bit-width.
//! - The clause must be fully evaluable by the bounded Bool/BV checker, and
//!   every bounded assignment must satisfy it. If the checker cannot prove the
//!   clause under the configured bounds, strict mode rejects it.
//!
//! Full truth-table verification (mirroring CVC5's `proof_bitblaster.cpp`) is
//! still future work tracked by #8071. Until then, strict mode is fail-closed:
//! unsupported or too-wide bit-blast lemmas are rejected instead of being
//! accepted by shape alone.

use ay_core::{BvGateType, Constant, ProofId, Sort, Symbol, TermData, TermId, TermStore};
use num_traits::ToPrimitive;

use super::ProofCheckError;

/// Recognize whether `clause` is a strict-checkable (ungated) bit-blast lemma —
/// i.e. whether [`validate_bv_bitblast`] with no gate annotation would accept it.
///
/// This is the exact inverse of the validator's bounded-semantics check: the
/// proof classifier (`ay-dpll`) calls it to upgrade a `Generic`/trust lemma into
/// the strict-checkable `BvBitBlast` kind ONLY when strict mode will
/// independently re-validate it by exhaustive bounded evaluation — so classifier
/// and checker cannot drift. A non-tautological or too-wide clause is rejected.
#[must_use]
pub fn recognize_bv_bitblast(terms: &TermStore, clause: &[TermId]) -> bool {
    validate_bv_bitblast(terms, ProofId(0), clause, None).is_ok()
}

/// Recognize whether `clause` is a strict-checkable Boolean tautology — every
/// literal is `Bool`-sorted and the clause is TRUE under every assignment of its
/// bounded (Bool / small-BV) variables. The exact inverse of
/// [`validate_bool_tautology`].
#[must_use]
pub fn recognize_bool_tautology(terms: &TermStore, clause: &[TermId]) -> bool {
    validate_bool_tautology(terms, ProofId(0), clause).is_ok()
}

/// Validate a `BoolTautology` lemma in strict mode: a propositional/Boolean
/// equality or formula that is TRUE under every assignment of its bounded
/// variables (e.g. `(= (not (not p)) p)`, `(= (and p p) p)`). Reuses the same
/// exhaustive bounded evaluator as the bit-blast path, but WITHOUT the
/// `clause_mentions_bv` content requirement — a pure-Boolean tautology has no
/// bitvector sub-term, and the exhaustive evaluation IS the soundness check
/// (every assignment satisfies the clause), so no BV content is needed. Every
/// literal must be `Bool`-sorted, and all variables must be bounded (else the
/// checker cannot exhaustively evaluate and fails closed).
pub(crate) fn validate_bool_tautology(
    terms: &TermStore,
    step_id: ProofId,
    clause: &[TermId],
) -> Result<(), ProofCheckError> {
    if clause.is_empty() {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: "bool tautology clause must be non-empty".to_string(),
        });
    }
    for &lit in clause {
        if !matches!(terms.sort(lit), Sort::Bool) {
            return Err(ProofCheckError::InvalidTheoryLemma {
                step: step_id,
                reason: format!(
                    "bool tautology literal has non-Bool sort {:?}; the clause must \
                     be purely propositional",
                    terms.sort(lit)
                ),
            });
        }
    }
    validate_bounded_clause_semantics(terms, step_id, clause)
}

/// Validate a `BvBitBlast` or `BvBitBlastGate` lemma in strict mode.
///
/// See module docs for the schema the clause must match.
pub(crate) fn validate_bv_bitblast(
    terms: &TermStore,
    step_id: ProofId,
    clause: &[TermId],
    gate: Option<(BvGateType, u32)>,
) -> Result<(), ProofCheckError> {
    if clause.is_empty() {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: "bv_bitblast clause must be non-empty".to_string(),
        });
    }

    for &lit in clause {
        // Every literal in a propositional bit-blast clause must be Boolean-
        // sorted. If we see a BV/Int/Real literal directly, the prover is
        // trying to sneak a non-propositional term through the SAT interface.
        let lit_sort = terms.sort(lit);
        if !matches!(lit_sort, Sort::Bool) {
            return Err(ProofCheckError::InvalidTheoryLemma {
                step: step_id,
                reason: format!(
                    "bv_bitblast literal has non-Bool sort {lit_sort:?}; \
                     bit-blast clauses must be purely propositional"
                ),
            });
        }
    }

    // The clause must mention at least one sub-term that is actually a
    // bitvector thing: a BV constant, BV variable, BV gate output, or an
    // equality/comparison between BV terms. A clause with no BV content at
    // all is not a bit-blast product, so we reject it as a forgery.
    if !clause_mentions_bv(terms, clause) {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: "bv_bitblast clause does not mention any bitvector \
                     sub-term; a forged lemma cannot hide behind this rule"
                .to_string(),
        });
    }

    // For the annotated gate form, require at least one sub-term that is an
    // application of an SMT-LIB operator consistent with the declared gate
    // type. This is a lightweight sanity check; it rejects lemmas whose
    // declared `gate_type = bvand` is incompatible with a clause that talks
    // only about `bvor`, etc.
    if let Some((gate_type, width)) = gate {
        let required_op = required_op_name(gate_type);
        // `None` means the gate type corresponds to a primitive shape
        // (const / variable / ite) rather than a concrete SMT-LIB operator.
        // For those we skip the operator check — the generic `clause_mentions_bv`
        // check above already rejects clauses without BV content.
        if let Some(op) = required_op {
            if !clause_mentions_matching_gate(terms, clause, op, gate_type, width) {
                return Err(ProofCheckError::InvalidTheoryLemma {
                    step: step_id,
                    reason: format!(
                        "bv_bitblast annotated gate {gate_type:?} requires \
                         the clause to reference operator `{op}` at width \
                         {width}, but no such sub-term was found"
                    ),
                });
            }
        }
    }

    validate_bounded_clause_semantics(terms, step_id, clause)?;
    Ok(())
}

/// Return the SMT-LIB operator name that must appear somewhere in the clause
/// for the given gate type. Returns `None` for gate types whose encoding
/// does not produce a named SMT-LIB operator (e.g., `Const`, `Variable`,
/// `Ite`).
fn required_op_name(gate_type: BvGateType) -> Option<&'static str> {
    match gate_type {
        BvGateType::And => Some("bvand"),
        BvGateType::Or => Some("bvor"),
        BvGateType::Xor => Some("bvxor"),
        BvGateType::Not => Some("bvnot"),
        BvGateType::Add => Some("bvadd"),
        BvGateType::Mul => Some("bvmul"),
        BvGateType::Neg => Some("bvneg"),
        BvGateType::Shl => Some("bvshl"),
        BvGateType::Lshr => Some("bvlshr"),
        BvGateType::Ashr => Some("bvashr"),
        BvGateType::Ult => Some("bvult"),
        BvGateType::Concat => Some("concat"),
        BvGateType::Extract => Some("extract"),
        BvGateType::ZeroExtend => Some("zero_extend"),
        BvGateType::SignExtend => Some("sign_extend"),
        BvGateType::Udiv => Some("bvudiv"),
        BvGateType::Urem => Some("bvurem"),
        // Primitive gates: no specific operator symbol required. Generic
        // BV-content check covers these. Any future `BvGateType` variants
        // default to "no specific operator" so we never crash on enum
        // extension.
        BvGateType::Eq | BvGateType::Const | BvGateType::Variable | BvGateType::Ite => None,
        _ => None,
    }
}

/// Return true if any literal in the clause contains (directly or nested) a
/// bitvector constant, bitvector variable, or bitvector-producing term.
fn clause_mentions_bv(terms: &TermStore, clause: &[TermId]) -> bool {
    clause
        .iter()
        .any(|&lit| term_mentions_bv(terms, lit, &mut Vec::new()))
}

fn term_mentions_bv(terms: &TermStore, term: TermId, stack: &mut Vec<TermId>) -> bool {
    // Guard against pathological cyclic/very deep walks. Hash-consing makes
    // cycles impossible in practice but we bound depth defensively.
    if stack.len() > 512 {
        return false;
    }
    stack.push(term);
    let result = if matches!(terms.sort(term), Sort::BitVec(_)) {
        true
    } else {
        match terms.get(term) {
            TermData::App(_, args) => args.iter().any(|&a| term_mentions_bv(terms, a, stack)),
            TermData::Not(inner) | TermData::Ite(_, inner, _) => {
                term_mentions_bv(terms, *inner, stack)
            }
            _ => false,
        }
    };
    stack.pop();
    result
}

/// Return true if any literal in the clause contains an application matching
/// the annotated SMT-LIB operator somewhere in its sub-term tree.
fn clause_mentions_matching_gate(
    terms: &TermStore,
    clause: &[TermId],
    op: &str,
    gate_type: BvGateType,
    width: u32,
) -> bool {
    clause
        .iter()
        .any(|&lit| term_mentions_matching_gate(terms, lit, op, gate_type, width, &mut Vec::new()))
}

fn term_mentions_matching_gate(
    terms: &TermStore,
    term: TermId,
    op: &str,
    gate_type: BvGateType,
    width: u32,
    stack: &mut Vec<TermId>,
) -> bool {
    if stack.len() > 512 {
        return false;
    }
    stack.push(term);
    let result = match terms.get(term) {
        TermData::App(sym, args) => {
            (sym.name() == op && gate_width_matches(terms, term, args, gate_type, width))
                || args
                    .iter()
                    .any(|&a| term_mentions_matching_gate(terms, a, op, gate_type, width, stack))
        }
        TermData::Not(inner) => {
            term_mentions_matching_gate(terms, *inner, op, gate_type, width, stack)
        }
        TermData::Ite(c, t, e) => {
            term_mentions_matching_gate(terms, *c, op, gate_type, width, stack)
                || term_mentions_matching_gate(terms, *t, op, gate_type, width, stack)
                || term_mentions_matching_gate(terms, *e, op, gate_type, width, stack)
        }
        _ => false,
    };
    stack.pop();
    result
}

fn gate_width_matches(
    terms: &TermStore,
    term: TermId,
    args: &[TermId],
    gate_type: BvGateType,
    width: u32,
) -> bool {
    if !same_width_gate_requires_width_check(gate_type) {
        return true;
    }

    bitvec_width(terms.sort(term)) == Some(width)
        && !args.is_empty()
        && args
            .iter()
            .all(|&arg| bitvec_width(terms.sort(arg)) == Some(width))
}

fn same_width_gate_requires_width_check(gate_type: BvGateType) -> bool {
    matches!(
        gate_type,
        BvGateType::And
            | BvGateType::Or
            | BvGateType::Xor
            | BvGateType::Not
            | BvGateType::Add
            | BvGateType::Mul
            | BvGateType::Neg
            | BvGateType::Shl
            | BvGateType::Lshr
            | BvGateType::Ashr
            | BvGateType::Udiv
            | BvGateType::Urem
    )
}

fn bitvec_width(sort: &Sort) -> Option<u32> {
    match sort {
        Sort::BitVec(bv) => Some(bv.width),
        _ => None,
    }
}

// Keep this intentionally small: the checker is a proof validator, not a
// second bit-blaster. These bounds catch small forged gate annotations without
// risking exponential work on real proofs.
const MAX_BOUNDED_BV_WIDTH: u32 = 4;
const MAX_BOUNDED_ASSIGNMENT_BITS: u32 = 8;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum EvalValue {
    Bool(bool),
    BitVec { value: u64, width: u32 },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct EvalVar {
    term: TermId,
    kind: EvalVarKind,
    bits: u32,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum EvalVarKind {
    Bool,
    BitVec,
}

fn validate_bounded_clause_semantics(
    terms: &TermStore,
    step_id: ProofId,
    clause: &[TermId],
) -> Result<(), ProofCheckError> {
    let Some(vars) = collect_bounded_vars(terms, clause) else {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: "bv_bitblast clause contains unsupported or too-wide \
                     Bool/BV terms; strict mode only accepts lemmas it can \
                     exhaustively evaluate"
                .to_string(),
        });
    };
    let total_bits: u32 = vars.iter().map(|v| v.bits).sum();
    if total_bits > MAX_BOUNDED_ASSIGNMENT_BITS {
        return Err(ProofCheckError::InvalidTheoryLemma {
            step: step_id,
            reason: format!(
                "bv_bitblast clause needs {total_bits} assignment bits, \
                 above strict bounded checker limit {MAX_BOUNDED_ASSIGNMENT_BITS}"
            ),
        });
    }

    let assignment_count = 1u64 << total_bits;
    for assignment in 0..assignment_count {
        let env = build_eval_env(&vars, assignment);
        let mut clause_true = false;
        for &lit in clause {
            let Some(value) = eval_bool_term(terms, lit, &env) else {
                return Err(ProofCheckError::InvalidTheoryLemma {
                    step: step_id,
                    reason: "bv_bitblast clause contains a literal the strict \
                             bounded checker cannot evaluate"
                        .to_string(),
                });
            };
            if value {
                clause_true = true;
                break;
            }
        }
        if !clause_true {
            return Err(ProofCheckError::InvalidTheoryLemma {
                step: step_id,
                reason: "bv_bitblast clause is falsified by a bounded Bool/BV \
                         assignment"
                    .to_string(),
            });
        }
    }

    Ok(())
}

fn collect_bounded_vars(terms: &TermStore, clause: &[TermId]) -> Option<Vec<EvalVar>> {
    let mut vars = Vec::new();
    for &lit in clause {
        collect_bounded_vars_term(terms, lit, &mut vars, &mut Vec::new())?;
    }
    Some(vars)
}

fn collect_bounded_vars_term(
    terms: &TermStore,
    term: TermId,
    vars: &mut Vec<EvalVar>,
    stack: &mut Vec<TermId>,
) -> Option<()> {
    if stack.len() > 512 {
        return None;
    }
    stack.push(term);
    let result = match terms.get(term) {
        TermData::Const(Constant::Bool(_)) => Some(()),
        TermData::Const(Constant::BitVec { width, .. }) if *width <= MAX_BOUNDED_BV_WIDTH => {
            Some(())
        }
        TermData::Const(_) => None,
        TermData::Var(_, _) => {
            let (kind, bits) = match terms.sort(term) {
                Sort::Bool => (EvalVarKind::Bool, 1),
                Sort::BitVec(bv) if bv.width <= MAX_BOUNDED_BV_WIDTH => {
                    (EvalVarKind::BitVec, bv.width)
                }
                _ => return None,
            };
            if !vars.iter().any(|var| var.term == term) {
                vars.push(EvalVar { term, kind, bits });
            }
            Some(())
        }
        TermData::App(sym, args) if supports_bounded_app(sym.name()) => {
            for &arg in args {
                collect_bounded_vars_term(terms, arg, vars, stack)?;
            }
            Some(())
        }
        TermData::Not(inner) => collect_bounded_vars_term(terms, *inner, vars, stack),
        TermData::Ite(c, t, e) => {
            collect_bounded_vars_term(terms, *c, vars, stack)?;
            collect_bounded_vars_term(terms, *t, vars, stack)?;
            collect_bounded_vars_term(terms, *e, vars, stack)
        }
        _ => None,
    };
    stack.pop();
    result
}

/// Operator names the bounded evaluator ([`eval_app`] / [`eval_indexed_bv`]) can
/// exhaustively evaluate. MUST stay in lock-step with those functions: an op
/// listed here but unhandled there (or vice versa) breaks the collect/evaluate
/// contract and makes the checker either panic-free-but-wrong or fail spuriously.
fn supports_bounded_app(name: &str) -> bool {
    matches!(
        name,
        "=" | "or"
            | "and"
            | "bvand"
            | "bvor"
            | "bvxor"
            | "bvnand"
            | "bvnor"
            | "bvxnor"
            | "bvnot"
            | "bvadd"
            | "bvsub"
            | "bvmul"
            | "bvneg"
            | "bvudiv"
            | "bvurem"
            | "bvsdiv"
            | "bvsrem"
            | "bvsmod"
            | "bvult"
            | "bvule"
            | "bvugt"
            | "bvuge"
            | "bvslt"
            | "bvsle"
            | "bvsgt"
            | "bvsge"
            | "bvshl"
            | "bvlshr"
            | "bvashr"
            | "concat"
            | "extract"
            | "zero_extend"
            | "sign_extend"
            | "rotate_left"
            | "rotate_right"
            | "repeat"
    )
}

fn build_eval_env(vars: &[EvalVar], assignment: u64) -> Vec<(TermId, EvalValue)> {
    let mut env = Vec::with_capacity(vars.len());
    let mut remaining = assignment;
    for var in vars {
        match var.kind {
            EvalVarKind::Bool => {
                env.push((var.term, EvalValue::Bool((remaining & 1) != 0)));
                remaining >>= 1;
            }
            EvalVarKind::BitVec => {
                let mask = bv_mask(var.bits);
                env.push((
                    var.term,
                    EvalValue::BitVec {
                        value: remaining & mask,
                        width: var.bits,
                    },
                ));
                remaining >>= var.bits;
            }
        }
    }
    env
}

fn eval_bool_term(terms: &TermStore, term: TermId, env: &[(TermId, EvalValue)]) -> Option<bool> {
    match eval_term(terms, term, env)? {
        EvalValue::Bool(value) => Some(value),
        EvalValue::BitVec { .. } => None,
    }
}

fn eval_term(terms: &TermStore, term: TermId, env: &[(TermId, EvalValue)]) -> Option<EvalValue> {
    match terms.get(term) {
        TermData::Const(Constant::Bool(value)) => Some(EvalValue::Bool(*value)),
        TermData::Const(Constant::BitVec { value, width }) => {
            let value = value.to_u64()? & bv_mask(*width);
            Some(EvalValue::BitVec {
                value,
                width: *width,
            })
        }
        TermData::Var(_, _) => env
            .iter()
            .find_map(|(var, value)| (*var == term).then_some(*value)),
        TermData::Not(inner) => Some(EvalValue::Bool(!eval_bool_term(terms, *inner, env)?)),
        TermData::Ite(c, t, e) => {
            let branch = if eval_bool_term(terms, *c, env)? {
                *t
            } else {
                *e
            };
            eval_term(terms, branch, env)
        }
        TermData::App(sym, args) => eval_app(terms, sym, args, env),
        _ => None,
    }
}

fn eval_app(
    terms: &TermStore,
    sym: &Symbol,
    args: &[TermId],
    env: &[(TermId, EvalValue)],
) -> Option<EvalValue> {
    // Indexed BV ops (extract / zero_extend / sign_extend) carry their indices in
    // the symbol, so dispatch on them before the name-based match below.
    if let Symbol::Indexed(name, indices) = sym {
        return eval_indexed_bv(terms, name, indices, args, env);
    }
    let name = sym.name();
    match name {
        "=" if args.len() == 2 => Some(EvalValue::Bool(
            eval_term(terms, args[0], env)? == eval_term(terms, args[1], env)?,
        )),
        "or" => {
            let mut any_true = false;
            for &arg in args {
                any_true |= eval_bool_term(terms, arg, env)?;
            }
            Some(EvalValue::Bool(any_true))
        }
        "and" => {
            let mut all_true = true;
            for &arg in args {
                all_true &= eval_bool_term(terms, arg, env)?;
            }
            Some(EvalValue::Bool(all_true))
        }
        "bvnot" if args.len() == 1 => {
            let (value, width) = eval_bv_arg(terms, args[0], env)?;
            Some(EvalValue::BitVec {
                value: (!value) & bv_mask(width),
                width,
            })
        }
        "bvneg" if args.len() == 1 => {
            let (value, width) = eval_bv_arg(terms, args[0], env)?;
            Some(EvalValue::BitVec {
                value: value.wrapping_neg() & bv_mask(width),
                width,
            })
        }
        "bvult" | "bvule" | "bvugt" | "bvuge" | "bvslt" | "bvsle" | "bvsgt" | "bvsge"
            if args.len() == 2 =>
        {
            let (lhs, rhs, width) = eval_same_width_bv_args(terms, args, env)?;
            let (sl, sr) = (to_signed_u64(lhs, width), to_signed_u64(rhs, width));
            let result = match name {
                "bvult" => lhs < rhs,
                "bvule" => lhs <= rhs,
                "bvugt" => lhs > rhs,
                "bvuge" => lhs >= rhs,
                "bvslt" => sl < sr,
                "bvsle" => sl <= sr,
                "bvsgt" => sl > sr,
                "bvsge" => sl >= sr,
                _ => unreachable!("guarded by match arm"),
            };
            Some(EvalValue::Bool(result))
        }
        "bvand" | "bvor" | "bvxor" | "bvnand" | "bvnor" | "bvxnor" | "bvadd" | "bvsub"
        | "bvmul" | "bvudiv" | "bvurem"
            if args.len() == 2 =>
        {
            let (lhs, rhs, width) = eval_same_width_bv_args(terms, args, env)?;
            let value = match name {
                "bvand" => lhs & rhs,
                "bvor" => lhs | rhs,
                "bvxor" => lhs ^ rhs,
                "bvnand" => !(lhs & rhs),
                "bvnor" => !(lhs | rhs),
                "bvxnor" => !(lhs ^ rhs),
                "bvadd" => lhs.wrapping_add(rhs),
                "bvsub" => lhs.wrapping_sub(rhs),
                "bvmul" => lhs.wrapping_mul(rhs),
                // SMT-LIB makes unsigned division/remainder TOTAL: dividing by
                // zero yields all-ones (bvudiv) / the dividend (bvurem).
                "bvudiv" => lhs.checked_div(rhs).unwrap_or_else(|| bv_mask(width)),
                "bvurem" => lhs.checked_rem(rhs).unwrap_or(lhs),
                _ => unreachable!("guarded by match arm"),
            } & bv_mask(width);
            Some(EvalValue::BitVec { value, width })
        }
        "bvsdiv" | "bvsrem" | "bvsmod" if args.len() == 2 => {
            let (lhs, rhs, width) = eval_same_width_bv_args(terms, args, env)?;
            Some(EvalValue::BitVec {
                value: eval_bv_signed_divrem(name, lhs, rhs, width),
                width,
            })
        }
        "bvshl" | "bvlshr" | "bvashr" if args.len() == 2 => {
            let (lhs, rhs, width) = eval_same_width_bv_args(terms, args, env)?;
            Some(EvalValue::BitVec {
                value: eval_bv_shift(name, lhs, rhs, width),
                width,
            })
        }
        "concat" if args.len() == 2 => {
            // SMT-LIB `(concat hi lo)`: first arg is the high part, second the low.
            let (hi, hi_width) = eval_bv_arg(terms, args[0], env)?;
            let (lo, lo_width) = eval_bv_arg(terms, args[1], env)?;
            let width = hi_width + lo_width;
            Some(EvalValue::BitVec {
                value: ((hi << lo_width) | lo) & bv_mask(width),
                width,
            })
        }
        _ => None,
    }
}

/// Evaluate the indexed bit-vector ops `extract` / `zero_extend` / `sign_extend`,
/// whose width-changing behavior is parameterized by the symbol indices. Kept in
/// lock-step with [`supports_bounded_app`] so collection and evaluation agree.
fn eval_indexed_bv(
    terms: &TermStore,
    name: &str,
    indices: &[u32],
    args: &[TermId],
    env: &[(TermId, EvalValue)],
) -> Option<EvalValue> {
    match name {
        "extract" if indices.len() == 2 && args.len() == 1 => {
            let (high, low) = (indices[0], indices[1]);
            if high < low {
                return None;
            }
            let (value, _src_width) = eval_bv_arg(terms, args[0], env)?;
            let width = high - low + 1;
            Some(EvalValue::BitVec {
                value: (value >> low) & bv_mask(width),
                width,
            })
        }
        "zero_extend" if indices.len() == 1 && args.len() == 1 => {
            let (value, src_width) = eval_bv_arg(terms, args[0], env)?;
            let width = src_width + indices[0];
            // The added high bits are zero; `value` is already masked to src_width.
            Some(EvalValue::BitVec {
                value: value & bv_mask(width),
                width,
            })
        }
        "sign_extend" if indices.len() == 1 && args.len() == 1 => {
            let (value, src_width) = eval_bv_arg(terms, args[0], env)?;
            let width = src_width + indices[0];
            let negative = src_width > 0 && (value >> (src_width - 1)) & 1 == 1;
            let extended = if negative {
                // Fill the added high bits with the sign bit (1).
                value | (bv_mask(width) ^ bv_mask(src_width))
            } else {
                value
            };
            Some(EvalValue::BitVec {
                value: extended & bv_mask(width),
                width,
            })
        }
        "rotate_left" | "rotate_right" if indices.len() == 1 && args.len() == 1 => {
            let (value, width) = eval_bv_arg(terms, args[0], env)?;
            let mask = bv_mask(width);
            let k = indices[0] % width.max(1);
            let rotated = if k == 0 {
                value
            } else if name == "rotate_left" {
                ((value << k) | (value >> (width - k))) & mask
            } else {
                ((value >> k) | (value << (width - k))) & mask
            };
            Some(EvalValue::BitVec {
                value: rotated,
                width,
            })
        }
        "repeat" if indices.len() == 1 && args.len() == 1 => {
            let count = indices[0];
            if count == 0 {
                return None; // (_ repeat 0) is not well-formed
            }
            let (value, width) = eval_bv_arg(terms, args[0], env)?;
            let total = width * count;
            let mut result = 0u64;
            for _ in 0..count {
                result = (result << width) | value;
            }
            Some(EvalValue::BitVec {
                value: result & bv_mask(total),
                width: total,
            })
        }
        _ => None,
    }
}

/// SMT-LIB bit-vector shift semantics for the strict bounded checker.
///
/// The shift amount is the *unsigned* value of `rhs`; it is NOT reduced modulo
/// `width`, so shifting by `>= width` SATURATES (0 for shl/lshr, sign-fill for
/// ashr). That over-shift case is exactly where machine shifts (x86 masks the
/// count) and LLVM shifts (poison at `s >= bitwidth`) diverge from SMT-LIB, so
/// the checker computes it explicitly to validate shift gates against the spec.
/// `lhs`/`rhs` are already masked to `width`.
fn eval_bv_shift(name: &str, lhs: u64, rhs: u64, width: u32) -> u64 {
    let mask = bv_mask(width);
    let shift = rhs;
    match name {
        "bvshl" if shift < u64::from(width) => (lhs << shift) & mask,
        "bvlshr" if shift < u64::from(width) => (lhs >> shift) & mask,
        // shl / lshr over-shift (shift >= width) saturate to zero.
        "bvshl" | "bvlshr" => 0,
        "bvashr" => {
            let negative = width > 0 && (lhs >> (width - 1)) & 1 == 1;
            if shift >= u64::from(width) {
                // Over-shift fills with the sign bit: all-ones / all-zeros.
                if negative {
                    mask
                } else {
                    0
                }
            } else {
                let logical = (lhs >> shift) & mask;
                if negative {
                    // Set the top `shift` vacated bits to 1 (sign fill).
                    (logical | (mask ^ (mask >> shift))) & mask
                } else {
                    logical
                }
            }
        }
        _ => unreachable!("eval_bv_shift only called for bvshl/bvlshr/bvashr"),
    }
}

/// Interpret a width-`w` bit-vector value as a two's-complement signed integer.
fn to_signed_u64(value: u64, width: u32) -> i64 {
    if width == 0 {
        return 0;
    }
    if (value >> (width - 1)) & 1 == 1 {
        (value as i64).wrapping_sub(1i64 << width)
    } else {
        value as i64
    }
}

/// SMT-LIB signed division / remainder / modulo — all TOTAL. `lhs`/`rhs` are
/// already masked to `width`. Division truncates toward zero; ÷0 yields -1 (a>=0)
/// or 1 (a<0) for bvsdiv and the dividend for bvsrem/bvsmod. bvsrem takes the sign
/// of the dividend; bvsmod takes the sign of the divisor.
fn eval_bv_signed_divrem(name: &str, lhs: u64, rhs: u64, width: u32) -> u64 {
    let mask = bv_mask(width);
    let a = to_signed_u64(lhs, width);
    let b = to_signed_u64(rhs, width);
    let pack = |s: i64| -> u64 { (s as u64) & mask };
    match name {
        "bvsdiv" => {
            if b == 0 {
                pack(if a >= 0 { -1 } else { 1 })
            } else {
                pack(a.wrapping_div(b))
            }
        }
        "bvsrem" => {
            if b == 0 {
                lhs
            } else {
                pack(a.wrapping_rem(b))
            }
        }
        "bvsmod" => {
            if b == 0 {
                lhs
            } else {
                let r = a.wrapping_rem(b);
                let m = if r == 0 || (r < 0) == (b < 0) {
                    r
                } else {
                    r + b
                };
                pack(m)
            }
        }
        _ => unreachable!("eval_bv_signed_divrem only for bvsdiv/bvsrem/bvsmod"),
    }
}

fn eval_bv_arg(terms: &TermStore, arg: TermId, env: &[(TermId, EvalValue)]) -> Option<(u64, u32)> {
    match eval_term(terms, arg, env)? {
        EvalValue::BitVec { value, width } => Some((value & bv_mask(width), width)),
        EvalValue::Bool(_) => None,
    }
}

fn eval_same_width_bv_args(
    terms: &TermStore,
    args: &[TermId],
    env: &[(TermId, EvalValue)],
) -> Option<(u64, u64, u32)> {
    let (lhs, lhs_width) = eval_bv_arg(terms, args[0], env)?;
    let (rhs, rhs_width) = eval_bv_arg(terms, args[1], env)?;
    (lhs_width == rhs_width).then_some((lhs, rhs, lhs_width))
}

fn bv_mask(width: u32) -> u64 {
    if width >= u64::BITS {
        u64::MAX
    } else {
        (1u64 << width) - 1
    }
}
